#!/usr/bin/env bash
# generate-chatgpt-context.sh — assemble an AI handoff bundle.
#
# Usage:
#   ./scripts/generate-chatgpt-context.sh           # both compact + full
#   ./scripts/generate-chatgpt-context.sh compact   # only the dense file
#   ./scripts/generate-chatgpt-context.sh full      # only the full bundle
#
# Outputs:
#   ./tmp/chatgpt-context-compact.md  — dense AI-to-AI; paste this first.
#   ./tmp/chatgpt-context-full.md     — full reading order, ~30-min onboarding.
#
# Philosophy:
#   - prioritize high-signal documents;
#   - do NOT dump every doc;
#   - preserve business + strategy + runtime philosophy;
#   - stay token-efficient (compact bundle is ≲ 6k lines).
#
# Refresh cadence: any time a load-bearing invariant changes.
# See doc/ai/context-recovery.md "Refreshing this context".

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

mode="${1:-both}"
out_dir="tmp"
mkdir -p "$out_dir"

# --- helpers ---------------------------------------------------------------

emit_header() {
  local out="$1"
  cat > "$out" <<EOF
<!--
 ChatGPT / Claude Code handoff bundle — Polymarket Watchtower.
 Generated by scripts/generate-chatgpt-context.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).

 If you are an AI agent: read top-to-bottom once. Every line carries load.
 If you are a human: this is what an agent sees. To regenerate, re-run the script.
-->

EOF
}

include() {
  local src="$1" out="$2"
  if [[ ! -f "$src" ]]; then
    echo "warning: missing $src" >&2
    return
  fi
  {
    echo ""
    echo "---"
    echo ""
    echo "<!-- ===== source: $src ===== -->"
    echo ""
    cat "$src"
  } >> "$out"
}

# --- compact bundle --------------------------------------------------------
# THE dense AI-to-AI handoff plus the philosophy that grounds it.
# Goal: paste this and a fresh agent can act correctly on 80% of tasks.

build_compact() {
  local out="$out_dir/chatgpt-context-compact.md"
  emit_header "$out"
  include doc/ai/chatgpt-handoff.md       "$out"
  include doc/ai/project-philosophy.md    "$out"
  include doc/ai/strategy-philosophy.md   "$out"
  include doc/ai/current-state.md         "$out"
  echo "wrote $out ($(wc -l < "$out") lines)"
}

# --- full bundle -----------------------------------------------------------
# Compact + runtime model + strategy map + operator runbook + tuning + decisions.
# Goal: 30-minute onboarding for tasks that require gate-level detail.

build_full() {
  local out="$out_dir/chatgpt-context-full.md"
  emit_header "$out"
  include doc/ai/chatgpt-handoff.md       "$out"
  include doc/ai/project-philosophy.md    "$out"
  include doc/ai/strategy-philosophy.md   "$out"
  include doc/ai/runtime-mental-model.md  "$out"
  include doc/ai/current-state.md         "$out"
  include doc/strategies/current-strategy-map.md "$out"
  include doc/project/operator-guide.md   "$out"
  include doc/project/tuning-methodology.md "$out"
  include doc/observability/ai-metrics.md "$out"
  include CLAUDE.md                       "$out"
  echo "wrote $out ($(wc -l < "$out") lines)"
}

# --- dispatcher ------------------------------------------------------------

case "$mode" in
  compact) build_compact ;;
  full)    build_full ;;
  both)    build_compact; build_full ;;
  *)
    echo "usage: $0 [compact|full|both]" >&2
    exit 2
    ;;
esac
