// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_analysis.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAlertOutcomeAnalysis = `-- name: GetAlertOutcomeAnalysis :one
SELECT id, alert_id, outcome_status, won_expected, ai_reason_text, ai_lessons_text, confidence, model, prompt_tokens, completion_tokens, estimated_cost_usd, telegram_message_id, telegram_chat_id, delivery_status, last_delivery_error, created_at FROM polymarket_alert_outcome_analyses
WHERE alert_id = $1::bigint
`

func (q *Queries) GetAlertOutcomeAnalysis(ctx context.Context, alertID int64) (PolymarketAlertOutcomeAnalyses, error) {
	row := q.db.QueryRow(ctx, getAlertOutcomeAnalysis, alertID)
	var i PolymarketAlertOutcomeAnalyses
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.OutcomeStatus,
		&i.WonExpected,
		&i.AiReasonText,
		&i.AiLessonsText,
		&i.Confidence,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.EstimatedCostUsd,
		&i.TelegramMessageID,
		&i.TelegramChatID,
		&i.DeliveryStatus,
		&i.LastDeliveryError,
		&i.CreatedAt,
	)
	return i, err
}

const insertAlertAnalysis = `-- name: InsertAlertAnalysis :one
INSERT INTO polymarket_alert_analyses (
    alert_id, version, trigger_kind, trigger_detail, model,
    prompt_chars, output_chars, prompt_tokens, completion_tokens,
    estimated_cost_usd, analysis_text, verdict, status, last_error
) VALUES (
    $1::bigint,
    $2::int,
    $3::text,
    $4::text,
    $5::text,
    $6::int,
    $7::int,
    $8::int,
    $9::int,
    $10::double precision,
    $11::text,
    $12::text,
    $13::text,
    $14::text
)
ON CONFLICT (alert_id, version) DO NOTHING
RETURNING id, alert_id, version, trigger_kind, trigger_detail, model, prompt_chars, output_chars, prompt_tokens, completion_tokens, estimated_cost_usd, analysis_text, verdict, status, last_error, created_at
`

type InsertAlertAnalysisParams struct {
	AlertID          int64
	Version          int32
	TriggerKind      string
	TriggerDetail    *string
	Model            string
	PromptChars      int32
	OutputChars      int32
	PromptTokens     int32
	CompletionTokens int32
	EstimatedCostUsd float64
	AnalysisText     string
	Verdict          *string
	Status           string
	LastError        *string
}

// Persist one AI alert-analysis row. Versions are append-only; the
// usecase layer chooses the version number (latest+1 on refresh,
// else 1). The trigger fields record WHY this version was generated
// so the lessons dataset can be re-derived later.
func (q *Queries) InsertAlertAnalysis(ctx context.Context, arg InsertAlertAnalysisParams) (PolymarketAlertAnalyses, error) {
	row := q.db.QueryRow(ctx, insertAlertAnalysis,
		arg.AlertID,
		arg.Version,
		arg.TriggerKind,
		arg.TriggerDetail,
		arg.Model,
		arg.PromptChars,
		arg.OutputChars,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.EstimatedCostUsd,
		arg.AnalysisText,
		arg.Verdict,
		arg.Status,
		arg.LastError,
	)
	var i PolymarketAlertAnalyses
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Version,
		&i.TriggerKind,
		&i.TriggerDetail,
		&i.Model,
		&i.PromptChars,
		&i.OutputChars,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.EstimatedCostUsd,
		&i.AnalysisText,
		&i.Verdict,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const insertAlertOutcomeAnalysis = `-- name: InsertAlertOutcomeAnalysis :one
INSERT INTO polymarket_alert_outcome_analyses (
    alert_id, outcome_status, won_expected,
    ai_reason_text, ai_lessons_text, confidence,
    model, prompt_tokens, completion_tokens, estimated_cost_usd,
    telegram_message_id, telegram_chat_id, delivery_status, last_delivery_error
) VALUES (
    $1::bigint,
    $2::text,
    $3::bool,
    $4::text,
    $5::text,
    $6::double precision,
    $7::text,
    $8::int,
    $9::int,
    $10::double precision,
    $11::bigint,
    $12::text,
    $13::text,
    $14::text
)
ON CONFLICT (alert_id) DO NOTHING
RETURNING id, alert_id, outcome_status, won_expected, ai_reason_text, ai_lessons_text, confidence, model, prompt_tokens, completion_tokens, estimated_cost_usd, telegram_message_id, telegram_chat_id, delivery_status, last_delivery_error, created_at
`

type InsertAlertOutcomeAnalysisParams struct {
	AlertID           int64
	OutcomeStatus     string
	WonExpected       *bool
	AiReasonText      string
	AiLessonsText     *string
	Confidence        float64
	Model             string
	PromptTokens      int32
	CompletionTokens  int32
	EstimatedCostUsd  float64
	TelegramMessageID *int64
	TelegramChatID    *string
	DeliveryStatus    string
	LastDeliveryError *string
}

// One row per alert; the outcomes worker calls this once per alert
// when the market resolves. Unique constraint on alert_id makes the
// write idempotent.
func (q *Queries) InsertAlertOutcomeAnalysis(ctx context.Context, arg InsertAlertOutcomeAnalysisParams) (PolymarketAlertOutcomeAnalyses, error) {
	row := q.db.QueryRow(ctx, insertAlertOutcomeAnalysis,
		arg.AlertID,
		arg.OutcomeStatus,
		arg.WonExpected,
		arg.AiReasonText,
		arg.AiLessonsText,
		arg.Confidence,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.EstimatedCostUsd,
		arg.TelegramMessageID,
		arg.TelegramChatID,
		arg.DeliveryStatus,
		arg.LastDeliveryError,
	)
	var i PolymarketAlertOutcomeAnalyses
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.OutcomeStatus,
		&i.WonExpected,
		&i.AiReasonText,
		&i.AiLessonsText,
		&i.Confidence,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.EstimatedCostUsd,
		&i.TelegramMessageID,
		&i.TelegramChatID,
		&i.DeliveryStatus,
		&i.LastDeliveryError,
		&i.CreatedAt,
	)
	return i, err
}

const insertMarketIntelligenceReport = `-- name: InsertMarketIntelligenceReport :one
INSERT INTO polymarket_market_intelligence_reports (
    period_key, period_start, period_end, summary_hash, report_text, markets_json,
    model, prompt_tokens, completion_tokens, estimated_cost_usd,
    telegram_message_id, telegram_chat_id, delivery_status, last_delivery_error
) VALUES (
    $1::text,
    $2::timestamptz,
    $3::timestamptz,
    $4::text,
    $5::text,
    $6::jsonb,
    $7::text,
    $8::int,
    $9::int,
    $10::double precision,
    $11::bigint,
    $12::text,
    $13::text,
    $14::text
)
ON CONFLICT (period_key) DO NOTHING
RETURNING id, generated_at, period_start, period_end, summary_hash, report_text, markets_json, model, prompt_tokens, completion_tokens, estimated_cost_usd, telegram_message_id, telegram_chat_id, delivery_status, last_delivery_error, created_at, period_key
`

type InsertMarketIntelligenceReportParams struct {
	PeriodKey         string
	PeriodStart       pgtype.Timestamptz
	PeriodEnd         pgtype.Timestamptz
	SummaryHash       string
	ReportText        string
	MarketsJson       []byte
	Model             string
	PromptTokens      int32
	CompletionTokens  int32
	EstimatedCostUsd  float64
	TelegramMessageID *int64
	TelegramChatID    *string
	DeliveryStatus    string
	LastDeliveryError *string
}

// Persist one 2h report. period_key UNIQUE — two ticks landing in the
// same bucket (computed deterministically in the worker) collapse to
// a single row, eliminating the duplicate-Telegram-send class of bug
// that prompted migration 00014.
func (q *Queries) InsertMarketIntelligenceReport(ctx context.Context, arg InsertMarketIntelligenceReportParams) (PolymarketMarketIntelligenceReports, error) {
	row := q.db.QueryRow(ctx, insertMarketIntelligenceReport,
		arg.PeriodKey,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.SummaryHash,
		arg.ReportText,
		arg.MarketsJson,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.EstimatedCostUsd,
		arg.TelegramMessageID,
		arg.TelegramChatID,
		arg.DeliveryStatus,
		arg.LastDeliveryError,
	)
	var i PolymarketMarketIntelligenceReports
	err := row.Scan(
		&i.ID,
		&i.GeneratedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SummaryHash,
		&i.ReportText,
		&i.MarketsJson,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.EstimatedCostUsd,
		&i.TelegramMessageID,
		&i.TelegramChatID,
		&i.DeliveryStatus,
		&i.LastDeliveryError,
		&i.CreatedAt,
		&i.PeriodKey,
	)
	return i, err
}

const latestAlertAnalysis = `-- name: LatestAlertAnalysis :one
SELECT id, alert_id, version, trigger_kind, trigger_detail, model, prompt_chars, output_chars, prompt_tokens, completion_tokens, estimated_cost_usd, analysis_text, verdict, status, last_error, created_at FROM polymarket_alert_analyses
WHERE alert_id = $1::bigint
ORDER BY version DESC
LIMIT 1
`

// Returns the most recent analysis row for the alert. Telegram
// formatter and operators reading the alert page consume this.
func (q *Queries) LatestAlertAnalysis(ctx context.Context, alertID int64) (PolymarketAlertAnalyses, error) {
	row := q.db.QueryRow(ctx, latestAlertAnalysis, alertID)
	var i PolymarketAlertAnalyses
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Version,
		&i.TriggerKind,
		&i.TriggerDetail,
		&i.Model,
		&i.PromptChars,
		&i.OutputChars,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.EstimatedCostUsd,
		&i.AnalysisText,
		&i.Verdict,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const latestAlertAnalysisVersion = `-- name: LatestAlertAnalysisVersion :one
SELECT COALESCE(MAX(version), 0)::int FROM polymarket_alert_analyses
WHERE alert_id = $1::bigint
`

// Returns the highest version number recorded for the alert, or 0
// when none. Used by the refresh policy to compute next-version.
func (q *Queries) LatestAlertAnalysisVersion(ctx context.Context, alertID int64) (int32, error) {
	row := q.db.QueryRow(ctx, latestAlertAnalysisVersion, alertID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const latestMarketIntelligenceReport = `-- name: LatestMarketIntelligenceReport :one
SELECT id, generated_at, period_start, period_end, summary_hash, report_text, markets_json, model, prompt_tokens, completion_tokens, estimated_cost_usd, telegram_message_id, telegram_chat_id, delivery_status, last_delivery_error, created_at, period_key FROM polymarket_market_intelligence_reports
ORDER BY generated_at DESC
LIMIT 1
`

func (q *Queries) LatestMarketIntelligenceReport(ctx context.Context) (PolymarketMarketIntelligenceReports, error) {
	row := q.db.QueryRow(ctx, latestMarketIntelligenceReport)
	var i PolymarketMarketIntelligenceReports
	err := row.Scan(
		&i.ID,
		&i.GeneratedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SummaryHash,
		&i.ReportText,
		&i.MarketsJson,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.EstimatedCostUsd,
		&i.TelegramMessageID,
		&i.TelegramChatID,
		&i.DeliveryStatus,
		&i.LastDeliveryError,
		&i.CreatedAt,
		&i.PeriodKey,
	)
	return i, err
}

const listMarketIntelligenceCandidates = `-- name: ListMarketIntelligenceCandidates :many
SELECT
    m.condition_id,
    m.question,
    c.name AS category,
    (100.0 * EXTRACT(EPOCH FROM (NOW() - m.start_date)) /
            NULLIF(EXTRACT(EPOCH FROM (m.end_date - m.start_date)), 0))::double precision AS lifecycle_pct,
    -- last 24h aggregates over polymarket_trades for this market
    COALESCE(
      (SELECT COUNT(*) FROM polymarket_trades t
       WHERE t.market_id = m.id AND t.traded_at >= NOW() - INTERVAL '24 hours'),
      0)::bigint AS trades_24h,
    COALESCE(
      (SELECT SUM(t.notional_usd) FROM polymarket_trades t
       WHERE t.market_id = m.id AND t.traded_at >= NOW() - INTERVAL '24 hours'),
      0)::double precision AS volume_24h_usd,
    -- last observed price on the first outcome token (proxy probability)
    COALESCE(
      (SELECT t.price FROM polymarket_trades t
       WHERE t.market_id = m.id
       ORDER BY t.traded_at DESC LIMIT 1),
      0)::double precision AS last_price,
    -- alerts emitted on this market in the last 24h
    COALESCE(
      (SELECT COUNT(*) FROM polymarket_alerts a
       WHERE a.market_id = m.id AND a.created_at >= NOW() - INTERVAL '24 hours'),
      0)::bigint AS alerts_24h
FROM polymarket_markets m
LEFT JOIN polymarket_market_categories mc ON mc.market_id = m.id
LEFT JOIN polymarket_categories c ON c.id = mc.category_id
WHERE m.active = TRUE
  AND m.deleted_at IS NULL
  AND m.purged_at  IS NULL
  AND m.start_date IS NOT NULL
  AND m.end_date   IS NOT NULL
  AND m.end_date    > NOW()
ORDER BY (100.0 * EXTRACT(EPOCH FROM (NOW() - m.start_date)) /
                NULLIF(EXTRACT(EPOCH FROM (m.end_date - m.start_date)), 0))::double precision DESC NULLS LAST,
         volume_24h_usd DESC
LIMIT $1::integer
`

type ListMarketIntelligenceCandidatesRow struct {
	ConditionID  string
	Question     string
	Category     *string
	LifecyclePct float64
	Trades24h    int64
	Volume24hUsd float64
	LastPrice    float64
	Alerts24h    int64
}

// Top-N candidate markets for the 2h intelligence report. Selection
// philosophy: deep into lifecycle + recent activity + non-trivial
// liquidity. The query is intentionally simple — the AI does the
// ranking; we provide a generous shortlist.
func (q *Queries) ListMarketIntelligenceCandidates(ctx context.Context, limitCount int32) ([]ListMarketIntelligenceCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listMarketIntelligenceCandidates, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketIntelligenceCandidatesRow
	for rows.Next() {
		var i ListMarketIntelligenceCandidatesRow
		if err := rows.Scan(
			&i.ConditionID,
			&i.Question,
			&i.Category,
			&i.LifecyclePct,
			&i.Trades24h,
			&i.Volume24hUsd,
			&i.LastPrice,
			&i.Alerts24h,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAlertStrategyDimensions = `-- name: UpsertAlertStrategyDimensions :exec
INSERT INTO polymarket_alert_strategy_dimensions (
    alert_id, strategy_family, lifecycle_bucket, odds_bucket,
    notional_bucket, return_bucket, category, accumulation_window,
    ownership_share_bucket, volatility_regime, new_wallet,
    quiet_market, dormant_wallet, drift_regime, ai_verdict
) VALUES (
    $1::bigint,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::text,
    $9::text,
    $10::text,
    $11::bool,
    $12::bool,
    $13::bool,
    $14::text,
    $15::text
)
ON CONFLICT (alert_id) DO UPDATE SET
    strategy_family       = EXCLUDED.strategy_family,
    lifecycle_bucket      = EXCLUDED.lifecycle_bucket,
    odds_bucket           = EXCLUDED.odds_bucket,
    notional_bucket       = EXCLUDED.notional_bucket,
    return_bucket         = EXCLUDED.return_bucket,
    category              = EXCLUDED.category,
    accumulation_window   = EXCLUDED.accumulation_window,
    ownership_share_bucket = EXCLUDED.ownership_share_bucket,
    volatility_regime     = EXCLUDED.volatility_regime,
    new_wallet            = EXCLUDED.new_wallet,
    quiet_market          = EXCLUDED.quiet_market,
    dormant_wallet        = EXCLUDED.dormant_wallet,
    drift_regime          = EXCLUDED.drift_regime,
    ai_verdict            = EXCLUDED.ai_verdict
`

type UpsertAlertStrategyDimensionsParams struct {
	AlertID              int64
	StrategyFamily       string
	LifecycleBucket      string
	OddsBucket           *string
	NotionalBucket       *string
	ReturnBucket         *string
	Category             *string
	AccumulationWindow   *string
	OwnershipShareBucket *string
	VolatilityRegime     *string
	NewWallet            bool
	QuietMarket          bool
	DormantWallet        bool
	DriftRegime          *string
	AiVerdict            *string
}

// One row per alert; idempotent. Called by the alertsender worker
// BEFORE Telegram delivery so the attribution row exists by the
// time the operator sees the alert. Overwrites any prior bucketing
// (so a re-run after schema fix doesn't accumulate ghosts).
func (q *Queries) UpsertAlertStrategyDimensions(ctx context.Context, arg UpsertAlertStrategyDimensionsParams) error {
	_, err := q.db.Exec(ctx, upsertAlertStrategyDimensions,
		arg.AlertID,
		arg.StrategyFamily,
		arg.LifecycleBucket,
		arg.OddsBucket,
		arg.NotionalBucket,
		arg.ReturnBucket,
		arg.Category,
		arg.AccumulationWindow,
		arg.OwnershipShareBucket,
		arg.VolatilityRegime,
		arg.NewWallet,
		arg.QuietMarket,
		arg.DormantWallet,
		arg.DriftRegime,
		arg.AiVerdict,
	)
	return err
}
