// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_analysis.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAlertOutcomeAnalysis = `-- name: GetAlertOutcomeAnalysis :one
SELECT id, alert_id, outcome_status, won_expected, ai_reason_text, ai_lessons_text, confidence, model, prompt_tokens, completion_tokens, estimated_cost_usd, telegram_message_id, telegram_chat_id, delivery_status, last_delivery_error, created_at FROM polymarket_alert_outcome_analyses
WHERE alert_id = $1::bigint
`

func (q *Queries) GetAlertOutcomeAnalysis(ctx context.Context, alertID int64) (PolymarketAlertOutcomeAnalyses, error) {
	row := q.db.QueryRow(ctx, getAlertOutcomeAnalysis, alertID)
	var i PolymarketAlertOutcomeAnalyses
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.OutcomeStatus,
		&i.WonExpected,
		&i.AiReasonText,
		&i.AiLessonsText,
		&i.Confidence,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.EstimatedCostUsd,
		&i.TelegramMessageID,
		&i.TelegramChatID,
		&i.DeliveryStatus,
		&i.LastDeliveryError,
		&i.CreatedAt,
	)
	return i, err
}

const insertAlertAnalysis = `-- name: InsertAlertAnalysis :one
INSERT INTO polymarket_alert_analyses (
    alert_id, version, trigger_kind, trigger_detail, model,
    prompt_chars, output_chars, prompt_tokens, completion_tokens,
    estimated_cost_usd, analysis_text, verdict, status, last_error
) VALUES (
    $1::bigint,
    $2::int,
    $3::text,
    $4::text,
    $5::text,
    $6::int,
    $7::int,
    $8::int,
    $9::int,
    $10::double precision,
    $11::text,
    $12::text,
    $13::text,
    $14::text
)
ON CONFLICT (alert_id, version) DO NOTHING
RETURNING id, alert_id, version, trigger_kind, trigger_detail, model, prompt_chars, output_chars, prompt_tokens, completion_tokens, estimated_cost_usd, analysis_text, verdict, status, last_error, created_at
`

type InsertAlertAnalysisParams struct {
	AlertID          int64
	Version          int32
	TriggerKind      string
	TriggerDetail    *string
	Model            string
	PromptChars      int32
	OutputChars      int32
	PromptTokens     int32
	CompletionTokens int32
	EstimatedCostUsd float64
	AnalysisText     string
	Verdict          *string
	Status           string
	LastError        *string
}

// Persist one AI alert-analysis row. Versions are append-only; the
// usecase layer chooses the version number (latest+1 on refresh,
// else 1). The trigger fields record WHY this version was generated
// so the lessons dataset can be re-derived later.
func (q *Queries) InsertAlertAnalysis(ctx context.Context, arg InsertAlertAnalysisParams) (PolymarketAlertAnalyses, error) {
	row := q.db.QueryRow(ctx, insertAlertAnalysis,
		arg.AlertID,
		arg.Version,
		arg.TriggerKind,
		arg.TriggerDetail,
		arg.Model,
		arg.PromptChars,
		arg.OutputChars,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.EstimatedCostUsd,
		arg.AnalysisText,
		arg.Verdict,
		arg.Status,
		arg.LastError,
	)
	var i PolymarketAlertAnalyses
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Version,
		&i.TriggerKind,
		&i.TriggerDetail,
		&i.Model,
		&i.PromptChars,
		&i.OutputChars,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.EstimatedCostUsd,
		&i.AnalysisText,
		&i.Verdict,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const insertAlertOutcomeAnalysis = `-- name: InsertAlertOutcomeAnalysis :one
INSERT INTO polymarket_alert_outcome_analyses (
    alert_id, outcome_status, won_expected,
    ai_reason_text, ai_lessons_text, confidence,
    model, prompt_tokens, completion_tokens, estimated_cost_usd,
    telegram_message_id, telegram_chat_id, delivery_status, last_delivery_error
) VALUES (
    $1::bigint,
    $2::text,
    $3::bool,
    $4::text,
    $5::text,
    $6::double precision,
    $7::text,
    $8::int,
    $9::int,
    $10::double precision,
    $11::bigint,
    $12::text,
    $13::text,
    $14::text
)
ON CONFLICT (alert_id) DO NOTHING
RETURNING id, alert_id, outcome_status, won_expected, ai_reason_text, ai_lessons_text, confidence, model, prompt_tokens, completion_tokens, estimated_cost_usd, telegram_message_id, telegram_chat_id, delivery_status, last_delivery_error, created_at
`

type InsertAlertOutcomeAnalysisParams struct {
	AlertID           int64
	OutcomeStatus     string
	WonExpected       *bool
	AiReasonText      string
	AiLessonsText     *string
	Confidence        float64
	Model             string
	PromptTokens      int32
	CompletionTokens  int32
	EstimatedCostUsd  float64
	TelegramMessageID *int64
	TelegramChatID    *string
	DeliveryStatus    string
	LastDeliveryError *string
}

// One row per alert; the outcomes worker calls this once per alert
// when the market resolves. Unique constraint on alert_id makes the
// write idempotent.
func (q *Queries) InsertAlertOutcomeAnalysis(ctx context.Context, arg InsertAlertOutcomeAnalysisParams) (PolymarketAlertOutcomeAnalyses, error) {
	row := q.db.QueryRow(ctx, insertAlertOutcomeAnalysis,
		arg.AlertID,
		arg.OutcomeStatus,
		arg.WonExpected,
		arg.AiReasonText,
		arg.AiLessonsText,
		arg.Confidence,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.EstimatedCostUsd,
		arg.TelegramMessageID,
		arg.TelegramChatID,
		arg.DeliveryStatus,
		arg.LastDeliveryError,
	)
	var i PolymarketAlertOutcomeAnalyses
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.OutcomeStatus,
		&i.WonExpected,
		&i.AiReasonText,
		&i.AiLessonsText,
		&i.Confidence,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.EstimatedCostUsd,
		&i.TelegramMessageID,
		&i.TelegramChatID,
		&i.DeliveryStatus,
		&i.LastDeliveryError,
		&i.CreatedAt,
	)
	return i, err
}

const insertMarketIntelligenceReport = `-- name: InsertMarketIntelligenceReport :one
INSERT INTO polymarket_market_intelligence_reports (
    period_start, period_end, summary_hash, report_text, markets_json,
    model, prompt_tokens, completion_tokens, estimated_cost_usd,
    telegram_message_id, telegram_chat_id, delivery_status, last_delivery_error
) VALUES (
    $1::timestamptz,
    $2::timestamptz,
    $3::text,
    $4::text,
    $5::jsonb,
    $6::text,
    $7::int,
    $8::int,
    $9::double precision,
    $10::bigint,
    $11::text,
    $12::text,
    $13::text
)
ON CONFLICT (summary_hash) DO NOTHING
RETURNING id, generated_at, period_start, period_end, summary_hash, report_text, markets_json, model, prompt_tokens, completion_tokens, estimated_cost_usd, telegram_message_id, telegram_chat_id, delivery_status, last_delivery_error, created_at
`

type InsertMarketIntelligenceReportParams struct {
	PeriodStart       pgtype.Timestamptz
	PeriodEnd         pgtype.Timestamptz
	SummaryHash       string
	ReportText        string
	MarketsJson       []byte
	Model             string
	PromptTokens      int32
	CompletionTokens  int32
	EstimatedCostUsd  float64
	TelegramMessageID *int64
	TelegramChatID    *string
	DeliveryStatus    string
	LastDeliveryError *string
}

// Persist one 2h report. summary_hash unique-conflict skips silently
// so the caller can decide whether to retry-with-fresh-content.
func (q *Queries) InsertMarketIntelligenceReport(ctx context.Context, arg InsertMarketIntelligenceReportParams) (PolymarketMarketIntelligenceReports, error) {
	row := q.db.QueryRow(ctx, insertMarketIntelligenceReport,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.SummaryHash,
		arg.ReportText,
		arg.MarketsJson,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.EstimatedCostUsd,
		arg.TelegramMessageID,
		arg.TelegramChatID,
		arg.DeliveryStatus,
		arg.LastDeliveryError,
	)
	var i PolymarketMarketIntelligenceReports
	err := row.Scan(
		&i.ID,
		&i.GeneratedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SummaryHash,
		&i.ReportText,
		&i.MarketsJson,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.EstimatedCostUsd,
		&i.TelegramMessageID,
		&i.TelegramChatID,
		&i.DeliveryStatus,
		&i.LastDeliveryError,
		&i.CreatedAt,
	)
	return i, err
}

const latestAlertAnalysis = `-- name: LatestAlertAnalysis :one
SELECT id, alert_id, version, trigger_kind, trigger_detail, model, prompt_chars, output_chars, prompt_tokens, completion_tokens, estimated_cost_usd, analysis_text, verdict, status, last_error, created_at FROM polymarket_alert_analyses
WHERE alert_id = $1::bigint
ORDER BY version DESC
LIMIT 1
`

// Returns the most recent analysis row for the alert. Telegram
// formatter and operators reading the alert page consume this.
func (q *Queries) LatestAlertAnalysis(ctx context.Context, alertID int64) (PolymarketAlertAnalyses, error) {
	row := q.db.QueryRow(ctx, latestAlertAnalysis, alertID)
	var i PolymarketAlertAnalyses
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Version,
		&i.TriggerKind,
		&i.TriggerDetail,
		&i.Model,
		&i.PromptChars,
		&i.OutputChars,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.EstimatedCostUsd,
		&i.AnalysisText,
		&i.Verdict,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const latestAlertAnalysisVersion = `-- name: LatestAlertAnalysisVersion :one
SELECT COALESCE(MAX(version), 0)::int FROM polymarket_alert_analyses
WHERE alert_id = $1::bigint
`

// Returns the highest version number recorded for the alert, or 0
// when none. Used by the refresh policy to compute next-version.
func (q *Queries) LatestAlertAnalysisVersion(ctx context.Context, alertID int64) (int32, error) {
	row := q.db.QueryRow(ctx, latestAlertAnalysisVersion, alertID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const latestMarketIntelligenceReport = `-- name: LatestMarketIntelligenceReport :one
SELECT id, generated_at, period_start, period_end, summary_hash, report_text, markets_json, model, prompt_tokens, completion_tokens, estimated_cost_usd, telegram_message_id, telegram_chat_id, delivery_status, last_delivery_error, created_at FROM polymarket_market_intelligence_reports
ORDER BY generated_at DESC
LIMIT 1
`

func (q *Queries) LatestMarketIntelligenceReport(ctx context.Context) (PolymarketMarketIntelligenceReports, error) {
	row := q.db.QueryRow(ctx, latestMarketIntelligenceReport)
	var i PolymarketMarketIntelligenceReports
	err := row.Scan(
		&i.ID,
		&i.GeneratedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SummaryHash,
		&i.ReportText,
		&i.MarketsJson,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.EstimatedCostUsd,
		&i.TelegramMessageID,
		&i.TelegramChatID,
		&i.DeliveryStatus,
		&i.LastDeliveryError,
		&i.CreatedAt,
	)
	return i, err
}
