// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const alertExistsByDedupKey = `-- name: AlertExistsByDedupKey :one
SELECT EXISTS (
    SELECT 1 FROM polymarket_alerts WHERE dedup_key = $1
) AS exists
`

func (q *Queries) AlertExistsByDedupKey(ctx context.Context, dedupKey string) (bool, error) {
	row := q.db.QueryRow(ctx, alertExistsByDedupKey, dedupKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const claimPendingAlertsForSend = `-- name: ClaimPendingAlertsForSend :many
UPDATE polymarket_alerts
SET status     = 'sending',
    updated_at = NOW()
WHERE id IN (
    SELECT id FROM polymarket_alerts
    WHERE status = 'pending'
    ORDER BY created_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, dedup_key, strategy_version, kind, reason, severity, market_id, trader_id, trade_id, payload, status, telegram_message_id, send_attempts, last_send_error, sent_at, created_at, updated_at
`

// Atomically transition up to $1 pending alerts to 'sending' and return
// them. The inner SELECT … FOR UPDATE SKIP LOCKED guarantees concurrent
// senders see disjoint batches even though the outer UPDATE runs in its
// own short-lived transaction. A row in `sending` is invisible to the
// next claimer until MarkAlertSent / MarkAlertSendFailed advances it, or
// ResetStaleSendingAlerts recovers it after a crashed sender.
func (q *Queries) ClaimPendingAlertsForSend(ctx context.Context, limit int32) ([]PolymarketAlerts, error) {
	rows, err := q.db.Query(ctx, claimPendingAlertsForSend, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketAlerts
	for rows.Next() {
		var i PolymarketAlerts
		if err := rows.Scan(
			&i.ID,
			&i.DedupKey,
			&i.StrategyVersion,
			&i.Kind,
			&i.Reason,
			&i.Severity,
			&i.MarketID,
			&i.TraderID,
			&i.TradeID,
			&i.Payload,
			&i.Status,
			&i.TelegramMessageID,
			&i.SendAttempts,
			&i.LastSendError,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestClusterAlertForCategory = `-- name: LatestClusterAlertForCategory :one
SELECT id, dedup_key, strategy_version, kind, reason, severity, market_id, trader_id, trade_id, payload, status, telegram_message_id, send_attempts, last_send_error, sent_at, created_at, updated_at FROM polymarket_alerts
WHERE kind             = 'category_watch'
  AND market_id        = $1
  AND strategy_version = $2
ORDER BY created_at DESC
LIMIT 1
`

type LatestClusterAlertForCategoryParams struct {
	MarketID        *int64
	StrategyVersion string
}

// Used by the cluster cooldown gate. Returns NULL when there's been no
// cluster alert for this market+outcome under the current strategy.
func (q *Queries) LatestClusterAlertForCategory(ctx context.Context, arg LatestClusterAlertForCategoryParams) (PolymarketAlerts, error) {
	row := q.db.QueryRow(ctx, latestClusterAlertForCategory, arg.MarketID, arg.StrategyVersion)
	var i PolymarketAlerts
	err := row.Scan(
		&i.ID,
		&i.DedupKey,
		&i.StrategyVersion,
		&i.Kind,
		&i.Reason,
		&i.Severity,
		&i.MarketID,
		&i.TraderID,
		&i.TradeID,
		&i.Payload,
		&i.Status,
		&i.TelegramMessageID,
		&i.SendAttempts,
		&i.LastSendError,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAlertSendFailed = `-- name: MarkAlertSendFailed :exec
UPDATE polymarket_alerts
SET status          = 'pending',
    send_attempts   = send_attempts + 1,
    last_send_error = $2,
    updated_at      = NOW()
WHERE id     = $1
  AND status = 'sending'
`

type MarkAlertSendFailedParams struct {
	ID            int64
	LastSendError *string
}

// Releases the claim back to 'pending' so the next ClaimPending tick can
// retry. The send_attempts column is bumped + the error message stored so
// operators can spot poison rows.
func (q *Queries) MarkAlertSendFailed(ctx context.Context, arg MarkAlertSendFailedParams) error {
	_, err := q.db.Exec(ctx, markAlertSendFailed, arg.ID, arg.LastSendError)
	return err
}

const markAlertSent = `-- name: MarkAlertSent :exec
UPDATE polymarket_alerts
SET status              = 'sent',
    sent_at             = NOW(),
    telegram_message_id = $2,
    last_send_error     = NULL,
    updated_at          = NOW()
WHERE id     = $1
  AND status = 'sending'
`

type MarkAlertSentParams struct {
	ID                int64
	TelegramMessageID *int64
}

// Completes a claim. Guarded by status='sending' so a duplicate sender
// racing on a row that was already MarkFailed cannot resurrect it.
func (q *Queries) MarkAlertSent(ctx context.Context, arg MarkAlertSentParams) error {
	_, err := q.db.Exec(ctx, markAlertSent, arg.ID, arg.TelegramMessageID)
	return err
}

const resetStaleSendingAlerts = `-- name: ResetStaleSendingAlerts :exec
UPDATE polymarket_alerts
SET status     = 'pending',
    updated_at = NOW()
WHERE status     = 'sending'
  AND updated_at < $1
`

// Crash recovery: any row that's been in 'sending' for longer than the
// supplied cutoff is moved back to 'pending'. Called by the sender worker
// on each tick (cheap when zero rows match).
func (q *Queries) ResetStaleSendingAlerts(ctx context.Context, updatedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, resetStaleSendingAlerts, updatedAt)
	return err
}

const tryCreatePendingAlert = `-- name: TryCreatePendingAlert :one
INSERT INTO polymarket_alerts (
    dedup_key, strategy_version,
    kind, reason, severity,
    market_id, trader_id, trade_id,
    payload, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'pending')
ON CONFLICT (dedup_key) DO NOTHING
RETURNING id, dedup_key, strategy_version, kind, reason, severity, market_id, trader_id, trade_id, payload, status, telegram_message_id, send_attempts, last_send_error, sent_at, created_at, updated_at
`

type TryCreatePendingAlertParams struct {
	DedupKey        string
	StrategyVersion string
	Kind            string
	Reason          string
	Severity        string
	MarketID        *int64
	TraderID        *int64
	TradeID         *int64
	Payload         []byte
}

// Atomic dedup primitive. INSERT ON CONFLICT DO NOTHING returns zero rows
// when an alert with the same dedup_key already exists — the caller maps
// that to "skip send". Concurrent detectors arriving at the same finding
// still produce exactly one row.
func (q *Queries) TryCreatePendingAlert(ctx context.Context, arg TryCreatePendingAlertParams) (PolymarketAlerts, error) {
	row := q.db.QueryRow(ctx, tryCreatePendingAlert,
		arg.DedupKey,
		arg.StrategyVersion,
		arg.Kind,
		arg.Reason,
		arg.Severity,
		arg.MarketID,
		arg.TraderID,
		arg.TradeID,
		arg.Payload,
	)
	var i PolymarketAlerts
	err := row.Scan(
		&i.ID,
		&i.DedupKey,
		&i.StrategyVersion,
		&i.Kind,
		&i.Reason,
		&i.Severity,
		&i.MarketID,
		&i.TraderID,
		&i.TradeID,
		&i.Payload,
		&i.Status,
		&i.TelegramMessageID,
		&i.SendAttempts,
		&i.LastSendError,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
