// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotation_intel.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyPoliticalIntelReport = `-- name: GetDailyPoliticalIntelReport :one
SELECT
    id, report_date, period_start, period_end,
    selected_markets_json, selected_annotations_json, catalysts_json,
    ai_report_text, telegram_message_ids_json, delivery_status, last_delivery_error,
    created_at, updated_at
FROM polymarket_daily_political_intel_reports
WHERE report_date = $1
`

func (q *Queries) GetDailyPoliticalIntelReport(ctx context.Context, reportDate pgtype.Date) (PolymarketDailyPoliticalIntelReports, error) {
	row := q.db.QueryRow(ctx, getDailyPoliticalIntelReport, reportDate)
	var i PolymarketDailyPoliticalIntelReports
	err := row.Scan(
		&i.ID,
		&i.ReportDate,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SelectedMarketsJson,
		&i.SelectedAnnotationsJson,
		&i.CatalystsJson,
		&i.AiReportText,
		&i.TelegramMessageIdsJson,
		&i.DeliveryStatus,
		&i.LastDeliveryError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLatestRankingForPeriod = `-- name: ListLatestRankingForPeriod :many
SELECT
    id, period_start, period_end, event_slug, market_slug, annotation_hash,
    rank, importance, volatility_potential, probability_impact,
    affected_outcome, title, reason, market_read, created_at
FROM polymarket_event_annotation_rankings
WHERE period_start = $1
ORDER BY rank, importance DESC
`

func (q *Queries) ListLatestRankingForPeriod(ctx context.Context, periodStart pgtype.Timestamptz) ([]PolymarketEventAnnotationRankings, error) {
	rows, err := q.db.Query(ctx, listLatestRankingForPeriod, periodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketEventAnnotationRankings
	for rows.Next() {
		var i PolymarketEventAnnotationRankings
		if err := rows.Scan(
			&i.ID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.EventSlug,
			&i.MarketSlug,
			&i.AnnotationHash,
			&i.Rank,
			&i.Importance,
			&i.VolatilityPotential,
			&i.ProbabilityImpact,
			&i.AffectedOutcome,
			&i.Title,
			&i.Reason,
			&i.MarketRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyPoliticalIntelReport = `-- name: UpsertDailyPoliticalIntelReport :one
INSERT INTO polymarket_daily_political_intel_reports (
    report_date, period_start, period_end,
    selected_markets_json, selected_annotations_json, catalysts_json,
    ai_report_text, telegram_message_ids_json, delivery_status, last_delivery_error,
    updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10,
    NOW()
)
ON CONFLICT (report_date) DO UPDATE SET
    period_start              = EXCLUDED.period_start,
    period_end                = EXCLUDED.period_end,
    selected_markets_json     = EXCLUDED.selected_markets_json,
    selected_annotations_json = EXCLUDED.selected_annotations_json,
    catalysts_json            = EXCLUDED.catalysts_json,
    ai_report_text            = COALESCE(NULLIF(EXCLUDED.ai_report_text, ''), polymarket_daily_political_intel_reports.ai_report_text),
    telegram_message_ids_json = EXCLUDED.telegram_message_ids_json,
    delivery_status           = EXCLUDED.delivery_status,
    last_delivery_error       = EXCLUDED.last_delivery_error,
    updated_at                = NOW()
RETURNING id
`

type UpsertDailyPoliticalIntelReportParams struct {
	ReportDate              pgtype.Date
	PeriodStart             pgtype.Timestamptz
	PeriodEnd               pgtype.Timestamptz
	SelectedMarketsJson     []byte
	SelectedAnnotationsJson []byte
	CatalystsJson           []byte
	AiReportText            string
	TelegramMessageIdsJson  []byte
	DeliveryStatus          string
	LastDeliveryError       string
}

func (q *Queries) UpsertDailyPoliticalIntelReport(ctx context.Context, arg UpsertDailyPoliticalIntelReportParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDailyPoliticalIntelReport,
		arg.ReportDate,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.SelectedMarketsJson,
		arg.SelectedAnnotationsJson,
		arg.CatalystsJson,
		arg.AiReportText,
		arg.TelegramMessageIdsJson,
		arg.DeliveryStatus,
		arg.LastDeliveryError,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertEventAnnotationRanking = `-- name: UpsertEventAnnotationRanking :exec
INSERT INTO polymarket_event_annotation_rankings (
    period_start, period_end, event_slug, market_slug, annotation_hash,
    rank, importance, volatility_potential, probability_impact,
    affected_outcome, title, reason, market_read
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13
)
ON CONFLICT (period_start, event_slug, annotation_hash) DO UPDATE SET
    period_end           = EXCLUDED.period_end,
    market_slug          = COALESCE(EXCLUDED.market_slug, polymarket_event_annotation_rankings.market_slug),
    rank                 = EXCLUDED.rank,
    importance           = EXCLUDED.importance,
    volatility_potential = EXCLUDED.volatility_potential,
    probability_impact   = EXCLUDED.probability_impact,
    affected_outcome     = COALESCE(EXCLUDED.affected_outcome, polymarket_event_annotation_rankings.affected_outcome),
    title                = EXCLUDED.title,
    reason               = EXCLUDED.reason,
    market_read          = EXCLUDED.market_read
`

type UpsertEventAnnotationRankingParams struct {
	PeriodStart         pgtype.Timestamptz
	PeriodEnd           pgtype.Timestamptz
	EventSlug           string
	MarketSlug          *string
	AnnotationHash      string
	Rank                int32
	Importance          float64
	VolatilityPotential float64
	ProbabilityImpact   string
	AffectedOutcome     *string
	Title               string
	Reason              string
	MarketRead          string
}

// Idempotent insert keyed on (period_start, event_slug, annotation_hash).
func (q *Queries) UpsertEventAnnotationRanking(ctx context.Context, arg UpsertEventAnnotationRankingParams) error {
	_, err := q.db.Exec(ctx, upsertEventAnnotationRanking,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.EventSlug,
		arg.MarketSlug,
		arg.AnnotationHash,
		arg.Rank,
		arg.Importance,
		arg.VolatilityPotential,
		arg.ProbabilityImpact,
		arg.AffectedOutcome,
		arg.Title,
		arg.Reason,
		arg.MarketRead,
	)
	return err
}
