// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: categories.sql

package sqlc

import (
	"context"
)

const getCategoryByExternalID = `-- name: GetCategoryByExternalID :one
SELECT id, external_id, slug, name, enabled, active, created_at, updated_at FROM polymarket_categories WHERE external_id = $1
`

func (q *Queries) GetCategoryByExternalID(ctx context.Context, externalID string) (PolymarketCategories, error) {
	row := q.db.QueryRow(ctx, getCategoryByExternalID, externalID)
	var i PolymarketCategories
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Slug,
		&i.Name,
		&i.Enabled,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, external_id, slug, name, enabled, active, created_at, updated_at FROM polymarket_categories ORDER BY id
`

func (q *Queries) ListAllCategories(ctx context.Context) ([]PolymarketCategories, error) {
	rows, err := q.db.Query(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketCategories
	for rows.Next() {
		var i PolymarketCategories
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Slug,
			&i.Name,
			&i.Enabled,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledCategories = `-- name: ListEnabledCategories :many
SELECT id, external_id, slug, name, enabled, active, created_at, updated_at FROM polymarket_categories
WHERE enabled = TRUE AND active = TRUE
ORDER BY id
`

func (q *Queries) ListEnabledCategories(ctx context.Context) ([]PolymarketCategories, error) {
	rows, err := q.db.Query(ctx, listEnabledCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketCategories
	for rows.Next() {
		var i PolymarketCategories
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Slug,
			&i.Name,
			&i.Enabled,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCategoriesNotInListInactive = `-- name: MarkCategoriesNotInListInactive :exec
UPDATE polymarket_categories
SET active = FALSE, updated_at = NOW()
WHERE active = TRUE
  AND NOT (external_id = ANY($1::text[]))
`

// Mark categories as inactive when they did not appear in the latest
// Polymarket /tags response. `enabled` is left alone — operator intent is
// preserved across upstream churn.
func (q *Queries) MarkCategoriesNotInListInactive(ctx context.Context, seenExternalIds []string) error {
	_, err := q.db.Exec(ctx, markCategoriesNotInListInactive, seenExternalIds)
	return err
}

const markCategoryEnabled = `-- name: MarkCategoryEnabled :exec
UPDATE polymarket_categories
SET enabled = $2, updated_at = NOW()
WHERE id = $1
`

type MarkCategoryEnabledParams struct {
	ID      int64
	Enabled bool
}

// Set the local `enabled` flag for one category. Called once per
// CATEGORY_WHITELIST entry on app boot.
func (q *Queries) MarkCategoryEnabled(ctx context.Context, arg MarkCategoryEnabledParams) error {
	_, err := q.db.Exec(ctx, markCategoryEnabled, arg.ID, arg.Enabled)
	return err
}

const upsertCategory = `-- name: UpsertCategory :one
INSERT INTO polymarket_categories (external_id, slug, name, active)
VALUES ($1, $2, $3, TRUE)
ON CONFLICT (external_id) DO UPDATE SET
    slug         = EXCLUDED.slug,
    name         = EXCLUDED.name,
    active       = TRUE,
    updated_at   = NOW()
RETURNING id, external_id, slug, name, enabled, active, created_at, updated_at
`

type UpsertCategoryParams struct {
	ExternalID string
	Slug       string
	Name       string
}

// Insert-or-update a Polymarket category. `enabled` is preserved on update
// (it's a local setting driven by CATEGORY_WHITELIST, not Polymarket data).
func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) (PolymarketCategories, error) {
	row := q.db.QueryRow(ctx, upsertCategory, arg.ExternalID, arg.Slug, arg.Name)
	var i PolymarketCategories
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Slug,
		&i.Name,
		&i.Enabled,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
