// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: concentration.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recentAlertsForEventConcentration = `-- name: RecentAlertsForEventConcentration :many

SELECT
    a.created_at,
    pm.event_slug,
    (a.payload->'Trade'->>'Wallet')           AS wallet,
    COALESCE((a.payload->'Trade'->>'NotionalUSD')::double precision, 0)::double precision AS notional_usd,
    a.severity
FROM polymarket_alerts a
JOIN polymarket_markets pm ON pm.id = a.market_id
WHERE pm.event_slug   = $1
  AND a.created_at    > $2
  AND a.status        = 'sent'
`

type RecentAlertsForEventConcentrationParams struct {
	EventSlug *string
	Since     pgtype.Timestamptz
}

type RecentAlertsForEventConcentrationRow struct {
	CreatedAt   pgtype.Timestamptz
	EventSlug   *string
	Wallet      interface{}
	NotionalUsd float64
	Severity    string
}

// v10.8 alert-concentration queries.
//
// These are the two seam queries the concentration.Gate calls before
// an alert is persisted. Both intentionally scan only the recent
// window so they stay cheap; the existing
// idx_alerts_created_at + idx_alerts_market_id indexes already cover
// them.
// Returns the recent alerts on an event, oldest-first. The caller
// (concentration.Gate) sorts internally; row order isn't load-bearing.
// Only `status='sent'` rows count — pending/failed rows didn't reach
// the operator and shouldn't constrain future emits.
func (q *Queries) RecentAlertsForEventConcentration(ctx context.Context, arg RecentAlertsForEventConcentrationParams) ([]RecentAlertsForEventConcentrationRow, error) {
	rows, err := q.db.Query(ctx, recentAlertsForEventConcentration, arg.EventSlug, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentAlertsForEventConcentrationRow
	for rows.Next() {
		var i RecentAlertsForEventConcentrationRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.EventSlug,
			&i.Wallet,
			&i.NotionalUsd,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentAlertsForWalletConcentration = `-- name: RecentAlertsForWalletConcentration :many
SELECT
    a.created_at,
    pm.event_slug,
    (a.payload->'Trade'->>'Wallet')           AS wallet,
    COALESCE((a.payload->'Trade'->>'NotionalUSD')::double precision, 0)::double precision AS notional_usd,
    a.severity
FROM polymarket_alerts a
JOIN polymarket_markets pm ON pm.id = a.market_id
WHERE pm.event_slug                  = $1
  AND (a.payload->'Trade'->>'Wallet') = $2
  AND a.created_at                   > $3
  AND a.status                       = 'sent'
`

type RecentAlertsForWalletConcentrationParams struct {
	EventSlug *string
	Wallet    []byte
	Since     pgtype.Timestamptz
}

type RecentAlertsForWalletConcentrationRow struct {
	CreatedAt   pgtype.Timestamptz
	EventSlug   *string
	Wallet      interface{}
	NotionalUsd float64
	Severity    string
}

// Returns the wallet's recent alerts on the event. Same shape; the
// wallet column comes from polymarket_alerts.payload (Pascal-case
// key `Wallet`). The check is operator-targeted, so unsent rows
// don't count here either.
func (q *Queries) RecentAlertsForWalletConcentration(ctx context.Context, arg RecentAlertsForWalletConcentrationParams) ([]RecentAlertsForWalletConcentrationRow, error) {
	rows, err := q.db.Query(ctx, recentAlertsForWalletConcentration, arg.EventSlug, arg.Wallet, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentAlertsForWalletConcentrationRow
	for rows.Next() {
		var i RecentAlertsForWalletConcentrationRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.EventSlug,
			&i.Wallet,
			&i.NotionalUsd,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
