// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_catalysts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveEventCatalysts = `-- name: ListActiveEventCatalysts :many
SELECT
    id, event_slug, condition_id, catalyst_type, title, description,
    expected_at, confidence, source, source_url, status,
    bullish_scenario, bearish_scenario, invalidation_scenario,
    created_at, updated_at
FROM polymarket_event_catalysts
WHERE event_slug = $1
  AND status IN ('expected', 'active')
ORDER BY
    CASE status WHEN 'active' THEN 0 ELSE 1 END,
    expected_at NULLS LAST,
    id
`

// Returns the catalysts the operator + AI should reason about: any
// row in (expected, active) status. Newest-first by expected_at
// (NULL-last) so the renderer prefers near-term events.
func (q *Queries) ListActiveEventCatalysts(ctx context.Context, eventSlug string) ([]PolymarketEventCatalysts, error) {
	rows, err := q.db.Query(ctx, listActiveEventCatalysts, eventSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketEventCatalysts
	for rows.Next() {
		var i PolymarketEventCatalysts
		if err := rows.Scan(
			&i.ID,
			&i.EventSlug,
			&i.ConditionID,
			&i.CatalystType,
			&i.Title,
			&i.Description,
			&i.ExpectedAt,
			&i.Confidence,
			&i.Source,
			&i.SourceUrl,
			&i.Status,
			&i.BullishScenario,
			&i.BearishScenario,
			&i.InvalidationScenario,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventCatalysts = `-- name: ListEventCatalysts :many
SELECT
    id, event_slug, condition_id, catalyst_type, title, description,
    expected_at, confidence, source, source_url, status,
    bullish_scenario, bearish_scenario, invalidation_scenario,
    created_at, updated_at
FROM polymarket_event_catalysts
WHERE event_slug = $1
ORDER BY
    CASE status WHEN 'active' THEN 0 WHEN 'expected' THEN 1 ELSE 2 END,
    expected_at NULLS LAST,
    id
`

// Returns ALL catalysts for an event (including resolved + stale +
// invalidated). Used by the postmortem AI path so the model can
// reason about whether a previously expected catalyst actually
// materialised.
func (q *Queries) ListEventCatalysts(ctx context.Context, eventSlug string) ([]PolymarketEventCatalysts, error) {
	rows, err := q.db.Query(ctx, listEventCatalysts, eventSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketEventCatalysts
	for rows.Next() {
		var i PolymarketEventCatalysts
		if err := rows.Scan(
			&i.ID,
			&i.EventSlug,
			&i.ConditionID,
			&i.CatalystType,
			&i.Title,
			&i.Description,
			&i.ExpectedAt,
			&i.Confidence,
			&i.Source,
			&i.SourceUrl,
			&i.Status,
			&i.BullishScenario,
			&i.BearishScenario,
			&i.InvalidationScenario,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventCatalystStatus = `-- name: SetEventCatalystStatus :exec
UPDATE polymarket_event_catalysts
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type SetEventCatalystStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) SetEventCatalystStatus(ctx context.Context, arg SetEventCatalystStatusParams) error {
	_, err := q.db.Exec(ctx, setEventCatalystStatus, arg.Status, arg.ID)
	return err
}

const upsertEventCatalyst = `-- name: UpsertEventCatalyst :exec
INSERT INTO polymarket_event_catalysts (
    event_slug, condition_id, catalyst_type, title, description,
    expected_at, confidence, source, source_url, status,
    bullish_scenario, bearish_scenario, invalidation_scenario
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13
)
ON CONFLICT (event_slug, catalyst_type, title) DO UPDATE SET
    condition_id          = COALESCE(NULLIF(EXCLUDED.condition_id, ''), polymarket_event_catalysts.condition_id),
    description           = COALESCE(NULLIF(EXCLUDED.description, ''), polymarket_event_catalysts.description),
    expected_at           = COALESCE(EXCLUDED.expected_at, polymarket_event_catalysts.expected_at),
    confidence            = GREATEST(EXCLUDED.confidence, polymarket_event_catalysts.confidence),
    source                = COALESCE(NULLIF(EXCLUDED.source, ''), polymarket_event_catalysts.source),
    source_url            = COALESCE(NULLIF(EXCLUDED.source_url, ''), polymarket_event_catalysts.source_url),
    status                = EXCLUDED.status,
    bullish_scenario      = COALESCE(NULLIF(EXCLUDED.bullish_scenario, ''), polymarket_event_catalysts.bullish_scenario),
    bearish_scenario      = COALESCE(NULLIF(EXCLUDED.bearish_scenario, ''), polymarket_event_catalysts.bearish_scenario),
    invalidation_scenario = COALESCE(NULLIF(EXCLUDED.invalidation_scenario, ''), polymarket_event_catalysts.invalidation_scenario),
    updated_at            = NOW()
`

type UpsertEventCatalystParams struct {
	EventSlug            string
	ConditionID          *string
	CatalystType         string
	Title                string
	Description          string
	ExpectedAt           pgtype.Timestamptz
	Confidence           float64
	Source               string
	SourceUrl            string
	Status               string
	BullishScenario      string
	BearishScenario      string
	InvalidationScenario string
}

// Idempotent insert keyed on (event_slug, catalyst_type, title).
// Mutable fields refresh on conflict; created_at stays frozen.
func (q *Queries) UpsertEventCatalyst(ctx context.Context, arg UpsertEventCatalystParams) error {
	_, err := q.db.Exec(ctx, upsertEventCatalyst,
		arg.EventSlug,
		arg.ConditionID,
		arg.CatalystType,
		arg.Title,
		arg.Description,
		arg.ExpectedAt,
		arg.Confidence,
		arg.Source,
		arg.SourceUrl,
		arg.Status,
		arg.BullishScenario,
		arg.BearishScenario,
		arg.InvalidationScenario,
	)
	return err
}
