// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_page.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventPageFetchState = `-- name: GetEventPageFetchState :one
SELECT
    event_slug, last_fetched_at, last_success_at, last_error,
    last_build_id, last_annotations, updated_at
FROM polymarket_event_page_fetches
WHERE event_slug = $1
`

func (q *Queries) GetEventPageFetchState(ctx context.Context, eventSlug string) (PolymarketEventPageFetches, error) {
	row := q.db.QueryRow(ctx, getEventPageFetchState, eventSlug)
	var i PolymarketEventPageFetches
	err := row.Scan(
		&i.EventSlug,
		&i.LastFetchedAt,
		&i.LastSuccessAt,
		&i.LastError,
		&i.LastBuildID,
		&i.LastAnnotations,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEventPageMarket = `-- name: InsertEventPageMarket :exec
INSERT INTO polymarket_event_page_markets (
    snapshot_id, event_slug, market_id, condition_id, market_slug,
    question, group_item_title, outcomes_json, outcome_prices_json,
    volume, volume_24h, liquidity, active, closed, end_date,
    one_hour_price_change, one_day_price_change, one_week_price_change,
    last_trade_price, best_bid, best_ask, clob_token_ids_json, raw_json
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15,
    $16, $17, $18,
    $19, $20, $21, $22, $23
)
`

type InsertEventPageMarketParams struct {
	SnapshotID         int64
	EventSlug          string
	MarketID           string
	ConditionID        string
	MarketSlug         string
	Question           string
	GroupItemTitle     *string
	OutcomesJson       []byte
	OutcomePricesJson  []byte
	Volume             float64
	Volume24h          float64
	Liquidity          float64
	Active             bool
	Closed             bool
	EndDate            pgtype.Timestamptz
	OneHourPriceChange *float64
	OneDayPriceChange  *float64
	OneWeekPriceChange *float64
	LastTradePrice     *float64
	BestBid            *float64
	BestAsk            *float64
	ClobTokenIdsJson   []byte
	RawJson            []byte
}

func (q *Queries) InsertEventPageMarket(ctx context.Context, arg InsertEventPageMarketParams) error {
	_, err := q.db.Exec(ctx, insertEventPageMarket,
		arg.SnapshotID,
		arg.EventSlug,
		arg.MarketID,
		arg.ConditionID,
		arg.MarketSlug,
		arg.Question,
		arg.GroupItemTitle,
		arg.OutcomesJson,
		arg.OutcomePricesJson,
		arg.Volume,
		arg.Volume24h,
		arg.Liquidity,
		arg.Active,
		arg.Closed,
		arg.EndDate,
		arg.OneHourPriceChange,
		arg.OneDayPriceChange,
		arg.OneWeekPriceChange,
		arg.LastTradePrice,
		arg.BestBid,
		arg.BestAsk,
		arg.ClobTokenIdsJson,
		arg.RawJson,
	)
	return err
}

const insertEventPageSnapshot = `-- name: InsertEventPageSnapshot :one
INSERT INTO polymarket_event_page_snapshots (
    event_slug, build_id, fetched_at, raw_hash, raw_json
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id
`

type InsertEventPageSnapshotParams struct {
	EventSlug string
	BuildID   string
	FetchedAt pgtype.Timestamptz
	RawHash   string
	RawJson   []byte
}

// Inserts a snapshot row. raw_json is capped by the writer before
// this call lands so the column stays bounded.
func (q *Queries) InsertEventPageSnapshot(ctx context.Context, arg InsertEventPageSnapshotParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEventPageSnapshot,
		arg.EventSlug,
		arg.BuildID,
		arg.FetchedAt,
		arg.RawHash,
		arg.RawJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLatestEventPageMarkets = `-- name: ListLatestEventPageMarkets :many
SELECT DISTINCT ON (market_id)
    id, snapshot_id, event_slug, market_id, condition_id, market_slug,
    question, group_item_title, outcomes_json, outcome_prices_json,
    volume, volume_24h, liquidity, active, closed, end_date,
    one_hour_price_change, one_day_price_change, one_week_price_change,
    last_trade_price, best_bid, best_ask, clob_token_ids_json, raw_json,
    created_at
FROM polymarket_event_page_markets
WHERE event_slug = $1
ORDER BY market_id, created_at DESC
`

// Returns one row per (event_slug, market_id) — the newest snapshot
// wins via the DISTINCT ON ordering. Used by the renderer + lag
// detector so we always read the freshest event-wide pricing.
func (q *Queries) ListLatestEventPageMarkets(ctx context.Context, eventSlug string) ([]PolymarketEventPageMarkets, error) {
	rows, err := q.db.Query(ctx, listLatestEventPageMarkets, eventSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketEventPageMarkets
	for rows.Next() {
		var i PolymarketEventPageMarkets
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.EventSlug,
			&i.MarketID,
			&i.ConditionID,
			&i.MarketSlug,
			&i.Question,
			&i.GroupItemTitle,
			&i.OutcomesJson,
			&i.OutcomePricesJson,
			&i.Volume,
			&i.Volume24h,
			&i.Liquidity,
			&i.Active,
			&i.Closed,
			&i.EndDate,
			&i.OneHourPriceChange,
			&i.OneDayPriceChange,
			&i.OneWeekPriceChange,
			&i.LastTradePrice,
			&i.BestBid,
			&i.BestAsk,
			&i.ClobTokenIdsJson,
			&i.RawJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEventAnnotations = `-- name: ListRecentEventAnnotations :many
SELECT
    id, event_slug, item_hash, timestamp, unix_time, time_range,
    title, summary, outcome,
    price_before, price_after, price_change,
    source, sources_json, tweets_json, raw_json,
    first_seen_at, last_seen_at
FROM polymarket_event_annotations
WHERE event_slug = $1
ORDER BY timestamp DESC NULLS LAST, id DESC
LIMIT $2
`

type ListRecentEventAnnotationsParams struct {
	EventSlug  string
	LimitCount int32
}

func (q *Queries) ListRecentEventAnnotations(ctx context.Context, arg ListRecentEventAnnotationsParams) ([]PolymarketEventAnnotations, error) {
	rows, err := q.db.Query(ctx, listRecentEventAnnotations, arg.EventSlug, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketEventAnnotations
	for rows.Next() {
		var i PolymarketEventAnnotations
		if err := rows.Scan(
			&i.ID,
			&i.EventSlug,
			&i.ItemHash,
			&i.Timestamp,
			&i.UnixTime,
			&i.TimeRange,
			&i.Title,
			&i.Summary,
			&i.Outcome,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChange,
			&i.Source,
			&i.SourcesJson,
			&i.TweetsJson,
			&i.RawJson,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEventAnnotation = `-- name: UpsertEventAnnotation :exec
INSERT INTO polymarket_event_annotations (
    event_slug, item_hash, timestamp, unix_time, time_range,
    title, summary, outcome,
    price_before, price_after, price_change,
    source, sources_json, tweets_json, raw_json,
    first_seen_at, last_seen_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14, $15,
    NOW(), NOW()
)
ON CONFLICT (event_slug, item_hash) DO UPDATE SET
    timestamp     = COALESCE(EXCLUDED.timestamp, polymarket_event_annotations.timestamp),
    unix_time     = GREATEST(EXCLUDED.unix_time, polymarket_event_annotations.unix_time),
    time_range    = COALESCE(EXCLUDED.time_range, polymarket_event_annotations.time_range),
    title         = EXCLUDED.title,
    summary       = COALESCE(EXCLUDED.summary, polymarket_event_annotations.summary),
    outcome       = COALESCE(EXCLUDED.outcome, polymarket_event_annotations.outcome),
    price_before  = COALESCE(EXCLUDED.price_before, polymarket_event_annotations.price_before),
    price_after   = COALESCE(EXCLUDED.price_after, polymarket_event_annotations.price_after),
    price_change  = COALESCE(EXCLUDED.price_change, polymarket_event_annotations.price_change),
    source        = COALESCE(EXCLUDED.source, polymarket_event_annotations.source),
    sources_json  = COALESCE(EXCLUDED.sources_json, polymarket_event_annotations.sources_json),
    tweets_json   = COALESCE(EXCLUDED.tweets_json, polymarket_event_annotations.tweets_json),
    raw_json      = COALESCE(EXCLUDED.raw_json, polymarket_event_annotations.raw_json),
    last_seen_at  = NOW()
`

type UpsertEventAnnotationParams struct {
	EventSlug   string
	ItemHash    string
	Timestamp   pgtype.Timestamptz
	UnixTime    int64
	TimeRange   *string
	Title       string
	Summary     *string
	Outcome     *string
	PriceBefore *float64
	PriceAfter  *float64
	PriceChange *float64
	Source      *string
	SourcesJson []byte
	TweetsJson  []byte
	RawJson     []byte
}

// Idempotent insert keyed on (event_slug, item_hash). On conflict we
// bump last_seen_at + refresh mutable fields (Polymarket sometimes
// edits a summary in place) but keep first_seen_at frozen.
func (q *Queries) UpsertEventAnnotation(ctx context.Context, arg UpsertEventAnnotationParams) error {
	_, err := q.db.Exec(ctx, upsertEventAnnotation,
		arg.EventSlug,
		arg.ItemHash,
		arg.Timestamp,
		arg.UnixTime,
		arg.TimeRange,
		arg.Title,
		arg.Summary,
		arg.Outcome,
		arg.PriceBefore,
		arg.PriceAfter,
		arg.PriceChange,
		arg.Source,
		arg.SourcesJson,
		arg.TweetsJson,
		arg.RawJson,
	)
	return err
}

const upsertEventPageFetchState = `-- name: UpsertEventPageFetchState :exec
INSERT INTO polymarket_event_page_fetches (
    event_slug, last_fetched_at, last_success_at, last_error,
    last_build_id, last_annotations, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, NOW()
)
ON CONFLICT (event_slug) DO UPDATE SET
    last_fetched_at  = EXCLUDED.last_fetched_at,
    last_success_at  = COALESCE(EXCLUDED.last_success_at, polymarket_event_page_fetches.last_success_at),
    last_error       = EXCLUDED.last_error,
    last_build_id    = COALESCE(NULLIF(EXCLUDED.last_build_id, ''), polymarket_event_page_fetches.last_build_id),
    last_annotations = EXCLUDED.last_annotations,
    updated_at       = NOW()
`

type UpsertEventPageFetchStateParams struct {
	EventSlug       string
	LastFetchedAt   pgtype.Timestamptz
	LastSuccessAt   pgtype.Timestamptz
	LastError       *string
	LastBuildID     *string
	LastAnnotations int32
}

func (q *Queries) UpsertEventPageFetchState(ctx context.Context, arg UpsertEventPageFetchStateParams) error {
	_, err := q.db.Exec(ctx, upsertEventPageFetchState,
		arg.EventSlug,
		arg.LastFetchedAt,
		arg.LastSuccessAt,
		arg.LastError,
		arg.LastBuildID,
		arg.LastAnnotations,
	)
	return err
}
