// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_flow.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateEventAlertsByKindAndSeverity = `-- name: AggregateEventAlertsByKindAndSeverity :many
SELECT
    a.kind     AS kind,
    a.severity AS severity,
    COUNT(*)::bigint AS count
FROM polymarket_alerts a
JOIN polymarket_markets m ON m.id = a.market_id
WHERE m.event_slug = $1
  AND a.created_at >= $2
GROUP BY a.kind, a.severity
`

type AggregateEventAlertsByKindAndSeverityParams struct {
	EventSlug *string
	Since     pgtype.Timestamptz
}

type AggregateEventAlertsByKindAndSeverityRow struct {
	Kind     string
	Severity string
	Count    int64
}

// Returns per-(kind, severity) counts for all alerts whose market
// has the given event_slug within the lookback window.
func (q *Queries) AggregateEventAlertsByKindAndSeverity(ctx context.Context, arg AggregateEventAlertsByKindAndSeverityParams) ([]AggregateEventAlertsByKindAndSeverityRow, error) {
	rows, err := q.db.Query(ctx, aggregateEventAlertsByKindAndSeverity, arg.EventSlug, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateEventAlertsByKindAndSeverityRow
	for rows.Next() {
		var i AggregateEventAlertsByKindAndSeverityRow
		if err := rows.Scan(&i.Kind, &i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventTopAlerts = `-- name: ListEventTopAlerts :many
SELECT
    a.id, a.kind, a.severity, a.reason, a.created_at,
    m.condition_id, m.question, m.slug AS market_slug
FROM polymarket_alerts a
JOIN polymarket_markets m ON m.id = a.market_id
WHERE m.event_slug = $1
  AND a.created_at >= $2
ORDER BY
    CASE a.severity
        WHEN 'hard'     THEN 4
        WHEN 'critical' THEN 3
        WHEN 'warning'  THEN 2
        WHEN 'info'     THEN 1
        ELSE 0
    END DESC,
    a.created_at DESC
LIMIT $3
`

type ListEventTopAlertsParams struct {
	EventSlug  *string
	Since      pgtype.Timestamptz
	LimitCount int32
}

type ListEventTopAlertsRow struct {
	ID          int64
	Kind        string
	Severity    string
	Reason      string
	CreatedAt   pgtype.Timestamptz
	ConditionID string
	Question    string
	MarketSlug  string
}

// Top N alerts (highest severity first, then newest) for one event.
func (q *Queries) ListEventTopAlerts(ctx context.Context, arg ListEventTopAlertsParams) ([]ListEventTopAlertsRow, error) {
	rows, err := q.db.Query(ctx, listEventTopAlerts, arg.EventSlug, arg.Since, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventTopAlertsRow
	for rows.Next() {
		var i ListEventTopAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Severity,
			&i.Reason,
			&i.CreatedAt,
			&i.ConditionID,
			&i.Question,
			&i.MarketSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventTopTrades = `-- name: ListEventTopTrades :many
SELECT
    t.id, t.market_id, t.outcome_token, t.side, t.price, t.notional_usd, t.traded_at,
    m.condition_id, m.question, m.slug AS market_slug,
    COALESCE(tr.wallet_address, '') AS wallet
FROM polymarket_trades t
JOIN polymarket_markets m ON m.id = t.market_id
LEFT JOIN polymarket_traders tr ON tr.id = t.trader_id
WHERE m.event_slug = $1
  AND t.traded_at >= $2
  AND t.notional_usd >= $3
ORDER BY t.notional_usd DESC, t.traded_at DESC
LIMIT $4
`

type ListEventTopTradesParams struct {
	EventSlug  *string
	Since      pgtype.Timestamptz
	MinUsd     float64
	LimitCount int32
}

type ListEventTopTradesRow struct {
	ID           int64
	MarketID     int64
	OutcomeToken string
	Side         string
	Price        float64
	NotionalUsd  float64
	TradedAt     pgtype.Timestamptz
	ConditionID  string
	Question     string
	MarketSlug   string
	Wallet       string
}

// Top N trades by notional for one event in the lookback window.
func (q *Queries) ListEventTopTrades(ctx context.Context, arg ListEventTopTradesParams) ([]ListEventTopTradesRow, error) {
	rows, err := q.db.Query(ctx, listEventTopTrades,
		arg.EventSlug,
		arg.Since,
		arg.MinUsd,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventTopTradesRow
	for rows.Next() {
		var i ListEventTopTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.OutcomeToken,
			&i.Side,
			&i.Price,
			&i.NotionalUsd,
			&i.TradedAt,
			&i.ConditionID,
			&i.Question,
			&i.MarketSlug,
			&i.Wallet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumConditionTradesInWindow = `-- name: SumConditionTradesInWindow :many
SELECT
    t.outcome_token,
    t.side,
    SUM(t.notional_usd)::double precision AS notional_usd,
    COUNT(*)::bigint AS trade_count
FROM polymarket_trades t
JOIN polymarket_markets m ON m.id = t.market_id
WHERE m.condition_id = $1
  AND t.traded_at >= $2
  AND t.traded_at < $3
GROUP BY t.outcome_token, t.side
`

type SumConditionTradesInWindowParams struct {
	ConditionID string
	Since       pgtype.Timestamptz
	Until       pgtype.Timestamptz
}

type SumConditionTradesInWindowRow struct {
	OutcomeToken string
	Side         string
	NotionalUsd  float64
	TradeCount   int64
}

// Per-(outcome_token, side) sums for ONE condition_id between two
// timestamps. Repricing pre/post-annotation flow uses this twice
// (once for [annotation−preWindow, annotation] and once for
// [annotation, annotation+postWindow]).
func (q *Queries) SumConditionTradesInWindow(ctx context.Context, arg SumConditionTradesInWindowParams) ([]SumConditionTradesInWindowRow, error) {
	rows, err := q.db.Query(ctx, sumConditionTradesInWindow, arg.ConditionID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumConditionTradesInWindowRow
	for rows.Next() {
		var i SumConditionTradesInWindowRow
		if err := rows.Scan(
			&i.OutcomeToken,
			&i.Side,
			&i.NotionalUsd,
			&i.TradeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumEventTradesByConditionAndSide = `-- name: SumEventTradesByConditionAndSide :many
SELECT
    m.condition_id,
    t.outcome_token,
    t.side,
    SUM(t.notional_usd)::double precision AS notional_usd,
    COUNT(*)::bigint AS trade_count
FROM polymarket_trades t
JOIN polymarket_markets m ON m.id = t.market_id
WHERE m.event_slug = $1
  AND t.traded_at >= $2
GROUP BY m.condition_id, t.outcome_token, t.side
`

type SumEventTradesByConditionAndSideParams struct {
	EventSlug *string
	Since     pgtype.Timestamptz
}

type SumEventTradesByConditionAndSideRow struct {
	ConditionID  string
	OutcomeToken string
	Side         string
	NotionalUsd  float64
	TradeCount   int64
}

// Per-(condition_id, outcome_token, side) sums + counts for the
// event. Drives the strongest-side + directional-imbalance fields.
func (q *Queries) SumEventTradesByConditionAndSide(ctx context.Context, arg SumEventTradesByConditionAndSideParams) ([]SumEventTradesByConditionAndSideRow, error) {
	rows, err := q.db.Query(ctx, sumEventTradesByConditionAndSide, arg.EventSlug, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumEventTradesByConditionAndSideRow
	for rows.Next() {
		var i SumEventTradesByConditionAndSideRow
		if err := rows.Scan(
			&i.ConditionID,
			&i.OutcomeToken,
			&i.Side,
			&i.NotionalUsd,
			&i.TradeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
