// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginMarketBackfill = `-- name: BeginMarketBackfill :exec
UPDATE polymarket_markets
SET backfill_status     = 'running',
    backfill_started_at = NOW(),
    backfill_attempts   = backfill_attempts + 1,
    updated_at          = NOW()
WHERE id = $1
  AND backfill_status IN ('pending','partial_api_limit')
`

// Atomic transition pending|partial_api_limit → running. Idempotent: a
// second caller picking up the same id will not flip status (status check
// in the WHERE clause guarantees one writer wins).
func (q *Queries) BeginMarketBackfill(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, beginMarketBackfill, id)
	return err
}

const completeMarketBackfill = `-- name: CompleteMarketBackfill :exec
UPDATE polymarket_markets
SET backfill_status            = $4::text,
    backfill_oldest_fetched_at = $2,
    backfill_newest_fetched_at = $3,
    backfill_completed_at      = NOW(),
    backfill_last_error        = NULL,
    updated_at                 = NOW()
WHERE id = $1
`

type CompleteMarketBackfillParams struct {
	ID                      int64
	BackfillOldestFetchedAt pgtype.Timestamptz
	BackfillNewestFetchedAt pgtype.Timestamptz
	Status                  string
}

func (q *Queries) CompleteMarketBackfill(ctx context.Context, arg CompleteMarketBackfillParams) error {
	_, err := q.db.Exec(ctx, completeMarketBackfill,
		arg.ID,
		arg.BackfillOldestFetchedAt,
		arg.BackfillNewestFetchedAt,
		arg.Status,
	)
	return err
}

const failMarketBackfill = `-- name: FailMarketBackfill :exec
UPDATE polymarket_markets
SET backfill_status     = 'failed',
    backfill_last_error = $2,
    updated_at          = NOW()
WHERE id = $1
`

type FailMarketBackfillParams struct {
	ID                int64
	BackfillLastError *string
}

func (q *Queries) FailMarketBackfill(ctx context.Context, arg FailMarketBackfillParams) error {
	_, err := q.db.Exec(ctx, failMarketBackfill, arg.ID, arg.BackfillLastError)
	return err
}

const getMarketByConditionID = `-- name: GetMarketByConditionID :one
SELECT id, condition_id, slug, question, event_slug, event_title, start_date, end_date, active, closed, last_seen_at, backfill_status, backfill_oldest_fetched_at, backfill_newest_fetched_at, backfill_attempts, backfill_last_error, backfill_started_at, backfill_completed_at, created_at, updated_at FROM polymarket_markets WHERE condition_id = $1
`

func (q *Queries) GetMarketByConditionID(ctx context.Context, conditionID string) (PolymarketMarkets, error) {
	row := q.db.QueryRow(ctx, getMarketByConditionID, conditionID)
	var i PolymarketMarkets
	err := row.Scan(
		&i.ID,
		&i.ConditionID,
		&i.Slug,
		&i.Question,
		&i.EventSlug,
		&i.EventTitle,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
		&i.Closed,
		&i.LastSeenAt,
		&i.BackfillStatus,
		&i.BackfillOldestFetchedAt,
		&i.BackfillNewestFetchedAt,
		&i.BackfillAttempts,
		&i.BackfillLastError,
		&i.BackfillStartedAt,
		&i.BackfillCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketByID = `-- name: GetMarketByID :one
SELECT id, condition_id, slug, question, event_slug, event_title, start_date, end_date, active, closed, last_seen_at, backfill_status, backfill_oldest_fetched_at, backfill_newest_fetched_at, backfill_attempts, backfill_last_error, backfill_started_at, backfill_completed_at, created_at, updated_at FROM polymarket_markets WHERE id = $1
`

func (q *Queries) GetMarketByID(ctx context.Context, id int64) (PolymarketMarkets, error) {
	row := q.db.QueryRow(ctx, getMarketByID, id)
	var i PolymarketMarkets
	err := row.Scan(
		&i.ID,
		&i.ConditionID,
		&i.Slug,
		&i.Question,
		&i.EventSlug,
		&i.EventTitle,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
		&i.Closed,
		&i.LastSeenAt,
		&i.BackfillStatus,
		&i.BackfillOldestFetchedAt,
		&i.BackfillNewestFetchedAt,
		&i.BackfillAttempts,
		&i.BackfillLastError,
		&i.BackfillStartedAt,
		&i.BackfillCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkMarketCategory = `-- name: LinkMarketCategory :exec
INSERT INTO polymarket_market_categories (market_id, category_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkMarketCategoryParams struct {
	MarketID   int64
	CategoryID int64
}

func (q *Queries) LinkMarketCategory(ctx context.Context, arg LinkMarketCategoryParams) error {
	_, err := q.db.Exec(ctx, linkMarketCategory, arg.MarketID, arg.CategoryID)
	return err
}

const listActiveMarketsForBackfill = `-- name: ListActiveMarketsForBackfill :many
SELECT id, condition_id, slug, question, event_slug, event_title, start_date, end_date, active, closed, last_seen_at, backfill_status, backfill_oldest_fetched_at, backfill_newest_fetched_at, backfill_attempts, backfill_last_error, backfill_started_at, backfill_completed_at, created_at, updated_at FROM polymarket_markets
WHERE active = TRUE
  AND backfill_status IN ('pending','partial_api_limit')
ORDER BY end_date ASC NULLS LAST
LIMIT $1
`

// Pick the next batch of markets to backfill, prioritised by upcoming
// end_date (markets nearer resolution have the most actionable history).
// Limit is the per-tick claim count.
func (q *Queries) ListActiveMarketsForBackfill(ctx context.Context, limit int32) ([]PolymarketMarkets, error) {
	rows, err := q.db.Query(ctx, listActiveMarketsForBackfill, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketMarkets
	for rows.Next() {
		var i PolymarketMarkets
		if err := rows.Scan(
			&i.ID,
			&i.ConditionID,
			&i.Slug,
			&i.Question,
			&i.EventSlug,
			&i.EventTitle,
			&i.StartDate,
			&i.EndDate,
			&i.Active,
			&i.Closed,
			&i.LastSeenAt,
			&i.BackfillStatus,
			&i.BackfillOldestFetchedAt,
			&i.BackfillNewestFetchedAt,
			&i.BackfillAttempts,
			&i.BackfillLastError,
			&i.BackfillStartedAt,
			&i.BackfillCompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveMarketsForCollection = `-- name: ListActiveMarketsForCollection :many
SELECT id, condition_id, slug, question, event_slug, event_title, start_date, end_date, active, closed, last_seen_at, backfill_status, backfill_oldest_fetched_at, backfill_newest_fetched_at, backfill_attempts, backfill_last_error, backfill_started_at, backfill_completed_at, created_at, updated_at FROM polymarket_markets
WHERE active = TRUE
  AND backfill_status IN ('completed','partial_api_limit')
ORDER BY id
`

// Active markets that have at least started backfill — collection of
// recent trades only makes sense once we know how far back history goes.
func (q *Queries) ListActiveMarketsForCollection(ctx context.Context) ([]PolymarketMarkets, error) {
	rows, err := q.db.Query(ctx, listActiveMarketsForCollection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketMarkets
	for rows.Next() {
		var i PolymarketMarkets
		if err := rows.Scan(
			&i.ID,
			&i.ConditionID,
			&i.Slug,
			&i.Question,
			&i.EventSlug,
			&i.EventTitle,
			&i.StartDate,
			&i.EndDate,
			&i.Active,
			&i.Closed,
			&i.LastSeenAt,
			&i.BackfillStatus,
			&i.BackfillOldestFetchedAt,
			&i.BackfillNewestFetchedAt,
			&i.BackfillAttempts,
			&i.BackfillLastError,
			&i.BackfillStartedAt,
			&i.BackfillCompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketCategoryIDs = `-- name: ListMarketCategoryIDs :many
SELECT category_id FROM polymarket_market_categories WHERE market_id = $1
`

func (q *Queries) ListMarketCategoryIDs(ctx context.Context, marketID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listMarketCategoryIDs, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var category_id int64
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMarketsInactiveNotIn = `-- name: MarkMarketsInactiveNotIn :exec
UPDATE polymarket_markets m
SET active = FALSE, updated_at = NOW()
WHERE m.active = TRUE
  AND NOT (m.condition_id = ANY($1::text[]))
  AND EXISTS (
      SELECT 1
      FROM polymarket_market_categories mc
      JOIN polymarket_categories c ON c.id = mc.category_id
      WHERE mc.market_id = m.id AND c.id = ANY($2::bigint[])
  )
`

type MarkMarketsInactiveNotInParams struct {
	SeenConditionIds []string
	ScopeCategoryIds []int64
}

// Mark active markets inactive when they did not appear in the latest
// whitelisted-categories discovery sweep. Scoped by category to avoid
// penalising markets in categories we don't currently sync.
func (q *Queries) MarkMarketsInactiveNotIn(ctx context.Context, arg MarkMarketsInactiveNotInParams) error {
	_, err := q.db.Exec(ctx, markMarketsInactiveNotIn, arg.SeenConditionIds, arg.ScopeCategoryIds)
	return err
}

const resetStaleRunningBackfills = `-- name: ResetStaleRunningBackfills :exec
UPDATE polymarket_markets
SET backfill_status = 'pending', updated_at = NOW()
WHERE backfill_status = 'running'
  AND backfill_started_at < $1
`

// Recovery: a process that crashed mid-backfill leaves rows in 'running'.
// This resets any 'running' row whose backfill_started_at is older than
// the supplied threshold, so the next scheduler tick re-claims them.
func (q *Queries) ResetStaleRunningBackfills(ctx context.Context, backfillStartedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, resetStaleRunningBackfills, backfillStartedAt)
	return err
}

const unlinkMarketCategoriesNotIn = `-- name: UnlinkMarketCategoriesNotIn :exec
DELETE FROM polymarket_market_categories
WHERE market_id = $1
  AND NOT (category_id = ANY($2::bigint[]))
`

type UnlinkMarketCategoriesNotInParams struct {
	MarketID        int64
	KeepCategoryIds []int64
}

func (q *Queries) UnlinkMarketCategoriesNotIn(ctx context.Context, arg UnlinkMarketCategoriesNotInParams) error {
	_, err := q.db.Exec(ctx, unlinkMarketCategoriesNotIn, arg.MarketID, arg.KeepCategoryIds)
	return err
}

const upsertMarket = `-- name: UpsertMarket :one
INSERT INTO polymarket_markets (
    condition_id, slug, question, event_slug, event_title,
    start_date, end_date, active, closed, last_seen_at
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, TRUE, $8, NOW()
)
ON CONFLICT (condition_id) DO UPDATE SET
    slug         = EXCLUDED.slug,
    question     = EXCLUDED.question,
    event_slug   = EXCLUDED.event_slug,
    event_title  = EXCLUDED.event_title,
    start_date   = EXCLUDED.start_date,
    end_date     = EXCLUDED.end_date,
    active       = TRUE,
    closed       = EXCLUDED.closed,
    last_seen_at = NOW(),
    updated_at   = NOW()
RETURNING id, condition_id, slug, question, event_slug, event_title, start_date, end_date, active, closed, last_seen_at, backfill_status, backfill_oldest_fetched_at, backfill_newest_fetched_at, backfill_attempts, backfill_last_error, backfill_started_at, backfill_completed_at, created_at, updated_at
`

type UpsertMarketParams struct {
	ConditionID string
	Slug        string
	Question    string
	EventSlug   *string
	EventTitle  *string
	StartDate   pgtype.Timestamptz
	EndDate     pgtype.Timestamptz
	Closed      bool
}

// Insert or update a market by condition_id. Backfill state fields are
// preserved on update — only discovery-sourced fields are touched. A
// previously-inactive market that reappears flips `active=TRUE` and the
// next BackfillWorker tick will pick up missing history.
func (q *Queries) UpsertMarket(ctx context.Context, arg UpsertMarketParams) (PolymarketMarkets, error) {
	row := q.db.QueryRow(ctx, upsertMarket,
		arg.ConditionID,
		arg.Slug,
		arg.Question,
		arg.EventSlug,
		arg.EventTitle,
		arg.StartDate,
		arg.EndDate,
		arg.Closed,
	)
	var i PolymarketMarkets
	err := row.Scan(
		&i.ID,
		&i.ConditionID,
		&i.Slug,
		&i.Question,
		&i.EventSlug,
		&i.EventTitle,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
		&i.Closed,
		&i.LastSeenAt,
		&i.BackfillStatus,
		&i.BackfillOldestFetchedAt,
		&i.BackfillNewestFetchedAt,
		&i.BackfillAttempts,
		&i.BackfillLastError,
		&i.BackfillStartedAt,
		&i.BackfillCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMarketOutcome = `-- name: UpsertMarketOutcome :exec
INSERT INTO polymarket_market_outcomes (market_id, token_id, label)
VALUES ($1, $2, $3)
ON CONFLICT (market_id, token_id) DO UPDATE SET
    label = EXCLUDED.label
`

type UpsertMarketOutcomeParams struct {
	MarketID int64
	TokenID  string
	Label    string
}

func (q *Queries) UpsertMarketOutcome(ctx context.Context, arg UpsertMarketOutcomeParams) error {
	_, err := q.db.Exec(ctx, upsertMarketOutcome, arg.MarketID, arg.TokenID, arg.Label)
	return err
}
