// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: market_close_reviews.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishMarketCloseReviewFailed = `-- name: FinishMarketCloseReviewFailed :exec
UPDATE polymarket_market_close_reviews
SET status        = 'failed',
    reviewed_at   = NOW(),
    error         = $1,
    next_retry_at = $2,
    attempts      = attempts + 1,
    updated_at    = NOW()
WHERE id = $3
`

type FinishMarketCloseReviewFailedParams struct {
	Error       string
	NextRetryAt pgtype.Timestamptz
	ID          int64
}

func (q *Queries) FinishMarketCloseReviewFailed(ctx context.Context, arg FinishMarketCloseReviewFailedParams) error {
	_, err := q.db.Exec(ctx, finishMarketCloseReviewFailed, arg.Error, arg.NextRetryAt, arg.ID)
	return err
}

const finishMarketCloseReviewSkipped = `-- name: FinishMarketCloseReviewSkipped :exec
UPDATE polymarket_market_close_reviews
SET status      = 'skipped',
    skip_reason = $1,
    reviewed_at = NOW(),
    updated_at  = NOW()
WHERE id = $2
`

type FinishMarketCloseReviewSkippedParams struct {
	SkipReason string
	ID         int64
}

func (q *Queries) FinishMarketCloseReviewSkipped(ctx context.Context, arg FinishMarketCloseReviewSkippedParams) error {
	_, err := q.db.Exec(ctx, finishMarketCloseReviewSkipped, arg.SkipReason, arg.ID)
	return err
}

const finishMarketCloseReviewSucceeded = `-- name: FinishMarketCloseReviewSucceeded :exec
UPDATE polymarket_market_close_reviews
SET status            = 'succeeded',
    reviewed_at       = NOW(),
    verdict           = $1,
    confidence        = $2,
    admin_summary     = $3,
    ai_json           = $4,
    evidence_json     = $5,
    ai_model          = $6,
    input_tokens      = $7,
    output_tokens     = $8,
    estimated_cost_usd = $9,
    error             = '',
    updated_at        = NOW()
WHERE id = $10
`

type FinishMarketCloseReviewSucceededParams struct {
	Verdict          string
	Confidence       *float64
	AdminSummary     string
	AiJson           []byte
	EvidenceJson     []byte
	AiModel          string
	InputTokens      *int32
	OutputTokens     *int32
	EstimatedCostUsd *float64
	ID               int64
}

func (q *Queries) FinishMarketCloseReviewSucceeded(ctx context.Context, arg FinishMarketCloseReviewSucceededParams) error {
	_, err := q.db.Exec(ctx, finishMarketCloseReviewSucceeded,
		arg.Verdict,
		arg.Confidence,
		arg.AdminSummary,
		arg.AiJson,
		arg.EvidenceJson,
		arg.AiModel,
		arg.InputTokens,
		arg.OutputTokens,
		arg.EstimatedCostUsd,
		arg.ID,
	)
	return err
}

const getMarketCloseReview = `-- name: GetMarketCloseReview :one
SELECT id, market_id, condition_id, event_slug,
       closed_at, resolved_at, reviewed_at,
       status, skip_reason, verdict, confidence,
       admin_summary, ai_json, evidence_json,
       ai_model, input_tokens, output_tokens, estimated_cost_usd,
       error, attempts, next_retry_at, created_at, updated_at
FROM polymarket_market_close_reviews
WHERE condition_id = $1 AND status = 'succeeded'
LIMIT 1
`

func (q *Queries) GetMarketCloseReview(ctx context.Context, conditionID string) (PolymarketMarketCloseReviews, error) {
	row := q.db.QueryRow(ctx, getMarketCloseReview, conditionID)
	var i PolymarketMarketCloseReviews
	err := row.Scan(
		&i.ID,
		&i.MarketID,
		&i.ConditionID,
		&i.EventSlug,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ReviewedAt,
		&i.Status,
		&i.SkipReason,
		&i.Verdict,
		&i.Confidence,
		&i.AdminSummary,
		&i.AiJson,
		&i.EvidenceJson,
		&i.AiModel,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCostUsd,
		&i.Error,
		&i.Attempts,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMarketCloseReviewRunning = `-- name: InsertMarketCloseReviewRunning :one
INSERT INTO polymarket_market_close_reviews (
    market_id, condition_id, event_slug,
    closed_at, resolved_at,
    status, attempts, created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    'running', 1, NOW(), NOW()
)
RETURNING id
`

type InsertMarketCloseReviewRunningParams struct {
	MarketID    *int64
	ConditionID string
	EventSlug   string
	ClosedAt    pgtype.Timestamptz
	ResolvedAt  pgtype.Timestamptz
}

// Inserts a fresh running row OR upserts the previous failed/
// pending row for the same condition_id by status transition.
// Returns the row id so the worker can FinishMarketCloseReview()
// against it.
func (q *Queries) InsertMarketCloseReviewRunning(ctx context.Context, arg InsertMarketCloseReviewRunningParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMarketCloseReviewRunning,
		arg.MarketID,
		arg.ConditionID,
		arg.EventSlug,
		arg.ClosedAt,
		arg.ResolvedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAlertsForMarketCloseReview = `-- name: ListAlertsForMarketCloseReview :many
SELECT id, dedup_key, strategy_version, kind, reason, severity,
       market_id, trader_id, trade_id, payload,
       telegram_message_id, sent_at, outcome_status, drift_status,
       clv_15m, clv_1h, clv_6h, clv_24h, created_at
FROM polymarket_alerts
WHERE market_id = $1
  AND status = 'sent'
  AND sent_at >= $2
ORDER BY sent_at ASC
LIMIT $3
`

type ListAlertsForMarketCloseReviewParams struct {
	MarketID  *int64
	SentSince pgtype.Timestamptz
	RowLimit  int32
}

type ListAlertsForMarketCloseReviewRow struct {
	ID                int64
	DedupKey          string
	StrategyVersion   string
	Kind              string
	Reason            string
	Severity          string
	MarketID          *int64
	TraderID          *int64
	TradeID           *int64
	Payload           []byte
	TelegramMessageID *int64
	SentAt            pgtype.Timestamptz
	OutcomeStatus     string
	DriftStatus       string
	Clv15m            *float64
	Clv1h             *float64
	Clv6h             *float64
	Clv24h            *float64
	CreatedAt         pgtype.Timestamptz
}

// Pulls alerts for a market within the review history lookback.
// Capped via @row_limit so the evidence package stays bounded.
func (q *Queries) ListAlertsForMarketCloseReview(ctx context.Context, arg ListAlertsForMarketCloseReviewParams) ([]ListAlertsForMarketCloseReviewRow, error) {
	rows, err := q.db.Query(ctx, listAlertsForMarketCloseReview, arg.MarketID, arg.SentSince, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertsForMarketCloseReviewRow
	for rows.Next() {
		var i ListAlertsForMarketCloseReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.DedupKey,
			&i.StrategyVersion,
			&i.Kind,
			&i.Reason,
			&i.Severity,
			&i.MarketID,
			&i.TraderID,
			&i.TradeID,
			&i.Payload,
			&i.TelegramMessageID,
			&i.SentAt,
			&i.OutcomeStatus,
			&i.DriftStatus,
			&i.Clv15m,
			&i.Clv1h,
			&i.Clv6h,
			&i.Clv24h,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketCloseReviewCandidates = `-- name: ListMarketCloseReviewCandidates :many

SELECT m.id, m.condition_id, m.event_slug, m.question,
       m.end_date, m.closed, m.active
FROM polymarket_markets m
LEFT JOIN polymarket_market_close_reviews r
       ON r.condition_id = m.condition_id AND r.status = 'succeeded'
WHERE m.closed = TRUE
  AND m.end_date >= $1
  AND m.end_date <= $2
  AND r.id IS NULL
ORDER BY m.end_date DESC
LIMIT $3
`

type ListMarketCloseReviewCandidatesParams struct {
	ClosedSince pgtype.Timestamptz
	ClosedUntil pgtype.Timestamptz
	RowLimit    int32
}

type ListMarketCloseReviewCandidatesRow struct {
	ID          int64
	ConditionID string
	EventSlug   *string
	Question    string
	EndDate     pgtype.Timestamptz
	Closed      bool
	Active      bool
}

// v11.4 Market Close Review queries.
// Returns recently-closed/resolved markets that have no succeeded
// review row, ordered by closed_at DESC. The worker fetches the
// newest candidates per tick and rejects each in code if the
// evidence package is empty / outside the window.
//
// Bounded: lookback + limit are both required (no full table scan).
func (q *Queries) ListMarketCloseReviewCandidates(ctx context.Context, arg ListMarketCloseReviewCandidatesParams) ([]ListMarketCloseReviewCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listMarketCloseReviewCandidates, arg.ClosedSince, arg.ClosedUntil, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketCloseReviewCandidatesRow
	for rows.Next() {
		var i ListMarketCloseReviewCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConditionID,
			&i.EventSlug,
			&i.Question,
			&i.EndDate,
			&i.Closed,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
