// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PolymarketAiRequestLogs struct {
	ID               int64
	TargetKind       string
	TargetID         *int64
	Provider         string
	Model            string
	RequestKind      string
	Status           string
	ErrorCategory    *string
	ErrorCode        *string
	ErrorMessage     *string
	HttpStatus       *int32
	PromptChars      int32
	OutputChars      int32
	PromptTokens     int32
	CompletionTokens int32
	EstimatedCostUsd float64
	LatencyMs        int64
	CreatedAt        pgtype.Timestamptz
}

type PolymarketAlertAnalyses struct {
	ID                    int64
	AlertID               int64
	Version               int32
	TriggerKind           string
	TriggerDetail         *string
	Model                 string
	PromptChars           int32
	OutputChars           int32
	PromptTokens          int32
	CompletionTokens      int32
	EstimatedCostUsd      float64
	AnalysisText          string
	Verdict               *string
	Status                string
	LastError             *string
	CreatedAt             pgtype.Timestamptz
	LegacyProviderFailure bool
}

type PolymarketAlertOutcomeAnalyses struct {
	ID                int64
	AlertID           int64
	OutcomeStatus     string
	WonExpected       *bool
	AiReasonText      string
	AiLessonsText     *string
	Confidence        float64
	Model             string
	PromptTokens      int32
	CompletionTokens  int32
	EstimatedCostUsd  float64
	TelegramMessageID *int64
	TelegramChatID    *string
	DeliveryStatus    string
	LastDeliveryError *string
	CreatedAt         pgtype.Timestamptz
}

type PolymarketAlertStrategyDimensions struct {
	AlertID              int64
	StrategyFamily       string
	LifecycleBucket      string
	OddsBucket           *string
	NotionalBucket       *string
	ReturnBucket         *string
	Category             *string
	AccumulationWindow   *string
	OwnershipShareBucket *string
	VolatilityRegime     *string
	NewWallet            bool
	QuietMarket          bool
	DormantWallet        bool
	DriftRegime          *string
	AiVerdict            *string
	CreatedAt            pgtype.Timestamptz
}

type PolymarketAlerts struct {
	ID                     int64
	DedupKey               string
	StrategyVersion        string
	Kind                   string
	Reason                 string
	Severity               string
	MarketID               *int64
	TraderID               *int64
	TradeID                *int64
	Payload                []byte
	Status                 string
	TelegramMessageID      *int64
	SendAttempts           int32
	LastSendError          *string
	SentAt                 pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	NextRetryAt            pgtype.Timestamptz
	LastAttemptAt          pgtype.Timestamptz
	OutcomeStatus          string
	OutcomeCheckedAt       pgtype.Timestamptz
	ResolvedAt             pgtype.Timestamptz
	WinningOutcomeToken    *string
	WinningOutcomeLabel    *string
	DriftStatus            string
	DriftCheckedAt         pgtype.Timestamptz
	Clv15m                 *float64
	Clv1h                  *float64
	Clv6h                  *float64
	Clv24h                 *float64
	TelegramReactionStatus string
	TelegramReactionEmoji  *string
	LastReactionAt         pgtype.Timestamptz
}

type PolymarketCategories struct {
	ID         int64
	ExternalID string
	Slug       string
	Name       string
	Enabled    bool
	Active     bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type PolymarketDailyPoliticalIntelReports struct {
	ID                      int64
	ReportDate              pgtype.Date
	PeriodStart             pgtype.Timestamptz
	PeriodEnd               pgtype.Timestamptz
	SelectedMarketsJson     []byte
	SelectedAnnotationsJson []byte
	CatalystsJson           []byte
	AiReportText            string
	TelegramMessageIdsJson  []byte
	DeliveryStatus          string
	LastDeliveryError       string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type PolymarketEventAnnotationRankings struct {
	ID                  int64
	PeriodStart         pgtype.Timestamptz
	PeriodEnd           pgtype.Timestamptz
	EventSlug           string
	MarketSlug          *string
	AnnotationHash      string
	Rank                int32
	Importance          float64
	VolatilityPotential float64
	ProbabilityImpact   string
	AffectedOutcome     *string
	Title               string
	Reason              string
	MarketRead          string
	CreatedAt           pgtype.Timestamptz
}

type PolymarketEventAnnotations struct {
	ID          int64
	EventSlug   string
	ItemHash    string
	Timestamp   pgtype.Timestamptz
	UnixTime    int64
	TimeRange   *string
	Title       string
	Summary     *string
	Outcome     *string
	PriceBefore *float64
	PriceAfter  *float64
	PriceChange *float64
	Source      *string
	SourcesJson []byte
	TweetsJson  []byte
	RawJson     []byte
	FirstSeenAt pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}

type PolymarketEventCatalysts struct {
	ID                   int64
	EventSlug            string
	ConditionID          *string
	CatalystType         string
	Title                string
	Description          string
	ExpectedAt           pgtype.Timestamptz
	Confidence           float64
	Source               string
	SourceUrl            string
	Status               string
	BullishScenario      string
	BearishScenario      string
	InvalidationScenario string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type PolymarketEventNewsFingerprints struct {
	EventSlug               string
	NewsFingerprint         string
	AnnotationCount         int32
	LatestAnnotationAt      pgtype.Timestamptz
	FirstSeenAt             pgtype.Timestamptz
	LastSeenAt              pgtype.Timestamptz
	ChangedAt               pgtype.Timestamptz
	LastSeenUnchangedAt     pgtype.Timestamptz
	LastAiCalledAt          pgtype.Timestamptz
	LastSemanticFingerprint *string
	LastSemanticAt          pgtype.Timestamptz
	LastSemanticCode        *string
	RepeatedCount           int32
}

type PolymarketEventPageFetches struct {
	EventSlug       string
	LastFetchedAt   pgtype.Timestamptz
	LastSuccessAt   pgtype.Timestamptz
	LastError       *string
	LastBuildID     *string
	LastAnnotations int32
	UpdatedAt       pgtype.Timestamptz
}

type PolymarketEventPageMarkets struct {
	ID                 int64
	SnapshotID         int64
	EventSlug          string
	MarketID           string
	ConditionID        string
	MarketSlug         string
	Question           string
	GroupItemTitle     *string
	OutcomesJson       []byte
	OutcomePricesJson  []byte
	Volume             float64
	Volume24h          float64
	Liquidity          float64
	Active             bool
	Closed             bool
	EndDate            pgtype.Timestamptz
	OneHourPriceChange *float64
	OneDayPriceChange  *float64
	OneWeekPriceChange *float64
	LastTradePrice     *float64
	BestBid            *float64
	BestAsk            *float64
	ClobTokenIdsJson   []byte
	RawJson            []byte
	CreatedAt          pgtype.Timestamptz
}

type PolymarketEventPageSnapshots struct {
	ID        int64
	EventSlug string
	BuildID   string
	FetchedAt pgtype.Timestamptz
	RawHash   string
	RawJson   []byte
	CreatedAt pgtype.Timestamptz
}

type PolymarketEventSlugAliases struct {
	OriginalSlug  string
	CanonicalSlug string
	Source        string
	FirstSeenAt   pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
}

type PolymarketLiveMarketState struct {
	ConditionID   string
	EventSlug     *string
	MarketSlug    *string
	BestBid       *float64
	BestAsk       *float64
	Mid           *float64
	LastPrice     *float64
	LastTradeAt   pgtype.Timestamptz
	LastWsEventAt pgtype.Timestamptz
	WsConnected   bool
	UpdatedAt     pgtype.Timestamptz
}

type PolymarketMarketCategories struct {
	MarketID   int64
	CategoryID int64
}

type PolymarketMarketIntelligenceReports struct {
	ID                int64
	GeneratedAt       pgtype.Timestamptz
	PeriodStart       pgtype.Timestamptz
	PeriodEnd         pgtype.Timestamptz
	SummaryHash       string
	ReportText        string
	MarketsJson       []byte
	Model             string
	PromptTokens      int32
	CompletionTokens  int32
	EstimatedCostUsd  float64
	TelegramMessageID *int64
	TelegramChatID    *string
	DeliveryStatus    string
	LastDeliveryError *string
	CreatedAt         pgtype.Timestamptz
	PeriodKey         string
}

type PolymarketMarketOutcomes struct {
	ID       int64
	MarketID int64
	TokenID  string
	Label    string
}

type PolymarketMarketPredictionStates struct {
	ID            int64
	PredictionID  int64
	PreviousState string
	NewState      string
	Reason        string
	EvidenceJson  []byte
	CreatedAt     pgtype.Timestamptz
}

type PolymarketMarketPredictions struct {
	ID                        int64
	EventSlug                 string
	ConditionID               string
	Outcome                   string
	SideBias                  string
	Summary                   string
	CurrentState              string
	StateReason               string
	PreviousPredictionID      *int64
	SupersedesPredictionID    *int64
	LastRepricedAt            pgtype.Timestamptz
	LastConfirmedByAlertAt    pgtype.Timestamptz
	LastContradictedByAlertAt pgtype.Timestamptz
	Confidence                float64
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	LastEvolvedAt             pgtype.Timestamptz
	ArchivedAt                pgtype.Timestamptz
	TerminalReason            *string
}

type PolymarketMarkets struct {
	ID                      int64
	ConditionID             string
	Slug                    string
	Question                string
	EventSlug               *string
	EventTitle              *string
	StartDate               pgtype.Timestamptz
	EndDate                 pgtype.Timestamptz
	Active                  bool
	Closed                  bool
	LastSeenAt              pgtype.Timestamptz
	BackfillStatus          string
	BackfillOldestFetchedAt pgtype.Timestamptz
	BackfillNewestFetchedAt pgtype.Timestamptz
	BackfillAttempts        int32
	BackfillLastError       *string
	BackfillStartedAt       pgtype.Timestamptz
	BackfillCompletedAt     pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
	PurgedAt                pgtype.Timestamptz
	// Cursor for the collect loop. MAX(traded_at) of trades the COLLECT path persisted. Backfill never updates this column.
	LastCollectTradedAt pgtype.Timestamptz
}

type PolymarketPredictionEvaluations struct {
	ID           int64
	PredictionID int64
	Horizon      string
	Evaluation   string
	Score        float64
	EvidenceJson []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type PolymarketPredictionFeedback struct {
	ID                       int64
	PredictionID             int64
	Horizon                  string
	PriceAtPrediction        *float64
	PriceAtHorizon           *float64
	PriceDelta               *float64
	DirectionCorrect         *bool
	StateAtHorizon           *string
	RepricingStatusAtHorizon *string
	CatalystStatusAtHorizon  *string
	FlowConfirmed            bool
	CreatedAt                pgtype.Timestamptz
}

type PolymarketPredictionUsefulnessScores struct {
	ID             int64
	PredictionID   int64
	Score          float64
	ComponentsJson []byte
	Reason         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type PolymarketRealtimeWorkQueue struct {
	ID          int64
	ConditionID *string
	EventSlug   *string
	Reason      string
	Priority    int16
	DedupeKey   string
	AvailableAt pgtype.Timestamptz
	ClaimedAt   pgtype.Timestamptz
	Attempts    int32
	LastError   *string
	CreatedAt   pgtype.Timestamptz
}

type PolymarketRepricingSignals struct {
	ID                      int64
	EventSlug               string
	ConditionID             string
	Outcome                 string
	AnnotationHash          string
	AnnotationTime          pgtype.Timestamptz
	AnnotationTitle         string
	PriceBefore             *float64
	PriceAfter              *float64
	AnnotationPriceChange   *float64
	CurrentPrice            *float64
	CurrentVsPriceAfter     float64
	DriftSinceAnnotation    float64
	PreAnnotationFlowUsd    float64
	PostAnnotationFlowUsd   float64
	SameSidePostFlowUsd     float64
	OppositeSidePostFlowUsd float64
	FlowTiming              string
	RepricingStatus         string
	Confidence              float64
	Explanation             string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type PolymarketSignalReports struct {
	ID                int64
	PeriodType        string
	PeriodStart       pgtype.Timestamptz
	PeriodEnd         pgtype.Timestamptz
	ScheduledAt       pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
	Status            string
	TelegramMessageID *int64
	LastError         *string
	Payload           []byte
	DedupKey          string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PolymarketTraders struct {
	ID            int64
	WalletAddress string
	FirstSeenAt   pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
}

type PolymarketTrades struct {
	ID                  int64
	MarketID            int64
	TraderID            *int64
	OutcomeToken        string
	Side                string
	Price               float64
	SizeShares          float64
	NotionalUsd         float64
	TradedAt            pgtype.Timestamptz
	ExternalID          *string
	TxHash              *string
	IngestedAt          pgtype.Timestamptz
	DedupKey            string
	DetectedAt          pgtype.Timestamptz
	DetectionStatus     *string
	DetectionSkipReason *string
	DetectionAttempts   int32
	LastDetectionError  *string
	DetectionClaimedAt  pgtype.Timestamptz
	DetectionWorkerID   *string
}

type PolymarketWsEvents struct {
	ID                int64
	ReceivedAt        pgtype.Timestamptz
	ExchangeTimestamp pgtype.Timestamptz
	EventType         string
	EventSlug         *string
	ConditionID       *string
	MarketSlug        *string
	ClobTokenID       *string
	Outcome           *string
	Price             *float64
	Size              *float64
	Side              *string
	SideSource        string
	SideConfidence    float64
	BestBid           *float64
	BestAsk           *float64
	Mid               *float64
	TxHash            *string
	TradeID           *string
	Wallet            *string
	Sequence          *string
	RawJson           []byte
	RawHash           *string
	CreatedAt         pgtype.Timestamptz
}

type PolymarketWsGapRecoveries struct {
	ID              int64
	ConditionID     string
	StartedAt       pgtype.Timestamptz
	EndedAt         pgtype.Timestamptz
	LookbackStart   pgtype.Timestamptz
	LookbackEnd     pgtype.Timestamptz
	RecoveredTrades int32
	Status          string
	LastError       *string
	CreatedAt       pgtype.Timestamptz
}
