// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PolymarketAlerts struct {
	ID                int64
	DedupKey          string
	StrategyVersion   string
	Kind              string
	Reason            string
	Severity          string
	MarketID          *int64
	TraderID          *int64
	TradeID           *int64
	Payload           []byte
	Status            string
	TelegramMessageID *int64
	SendAttempts      int32
	LastSendError     *string
	SentAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PolymarketCategories struct {
	ID         int64
	ExternalID string
	Slug       string
	Name       string
	Enabled    bool
	Active     bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type PolymarketMarketCategories struct {
	MarketID   int64
	CategoryID int64
}

type PolymarketMarketOutcomes struct {
	ID       int64
	MarketID int64
	TokenID  string
	Label    string
}

type PolymarketMarkets struct {
	ID                      int64
	ConditionID             string
	Slug                    string
	Question                string
	EventSlug               *string
	EventTitle              *string
	StartDate               pgtype.Timestamptz
	EndDate                 pgtype.Timestamptz
	Active                  bool
	Closed                  bool
	LastSeenAt              pgtype.Timestamptz
	BackfillStatus          string
	BackfillOldestFetchedAt pgtype.Timestamptz
	BackfillNewestFetchedAt pgtype.Timestamptz
	BackfillAttempts        int32
	BackfillLastError       *string
	BackfillStartedAt       pgtype.Timestamptz
	BackfillCompletedAt     pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type PolymarketTraders struct {
	ID            int64
	WalletAddress string
	FirstSeenAt   pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
}

type PolymarketTrades struct {
	ID           int64
	MarketID     int64
	TraderID     *int64
	OutcomeToken string
	Side         string
	Price        float64
	SizeShares   float64
	NotionalUsd  float64
	TradedAt     pgtype.Timestamptz
	ExternalID   *string
	TxHash       *string
	IngestedAt   pgtype.Timestamptz
	DedupKey     string
}
