// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: news_fingerprints.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventNewsFingerprint = `-- name: GetEventNewsFingerprint :one
SELECT event_slug, news_fingerprint, annotation_count, latest_annotation_at,
       first_seen_at, last_seen_at, changed_at, last_seen_unchanged_at,
       last_ai_called_at, last_semantic_fingerprint, last_semantic_at,
       last_semantic_code, repeated_count
FROM polymarket_event_news_fingerprints
WHERE event_slug = $1
`

func (q *Queries) GetEventNewsFingerprint(ctx context.Context, eventSlug string) (PolymarketEventNewsFingerprints, error) {
	row := q.db.QueryRow(ctx, getEventNewsFingerprint, eventSlug)
	var i PolymarketEventNewsFingerprints
	err := row.Scan(
		&i.EventSlug,
		&i.NewsFingerprint,
		&i.AnnotationCount,
		&i.LatestAnnotationAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ChangedAt,
		&i.LastSeenUnchangedAt,
		&i.LastAiCalledAt,
		&i.LastSemanticFingerprint,
		&i.LastSemanticAt,
		&i.LastSemanticCode,
		&i.RepeatedCount,
	)
	return i, err
}

const touchEventNewsAICalled = `-- name: TouchEventNewsAICalled :exec
UPDATE polymarket_event_news_fingerprints
SET last_ai_called_at = NOW()
WHERE event_slug = $1
`

func (q *Queries) TouchEventNewsAICalled(ctx context.Context, eventSlug string) error {
	_, err := q.db.Exec(ctx, touchEventNewsAICalled, eventSlug)
	return err
}

const upsertEventNewsFingerprint = `-- name: UpsertEventNewsFingerprint :exec
INSERT INTO polymarket_event_news_fingerprints (
    event_slug, news_fingerprint, annotation_count, latest_annotation_at,
    first_seen_at, last_seen_at, changed_at, last_seen_unchanged_at
) VALUES (
    $1, $2, $3, $4,
    NOW(), NOW(), NOW(), NULL
)
ON CONFLICT (event_slug) DO UPDATE SET
    news_fingerprint = EXCLUDED.news_fingerprint,
    annotation_count = EXCLUDED.annotation_count,
    latest_annotation_at = EXCLUDED.latest_annotation_at,
    last_seen_at = NOW(),
    changed_at = CASE
        WHEN polymarket_event_news_fingerprints.news_fingerprint = EXCLUDED.news_fingerprint
        THEN polymarket_event_news_fingerprints.changed_at
        ELSE NOW()
    END,
    last_seen_unchanged_at = CASE
        WHEN polymarket_event_news_fingerprints.news_fingerprint = EXCLUDED.news_fingerprint
        THEN NOW()
        ELSE polymarket_event_news_fingerprints.last_seen_unchanged_at
    END
`

type UpsertEventNewsFingerprintParams struct {
	EventSlug          string
	NewsFingerprint    string
	AnnotationCount    int32
	LatestAnnotationAt pgtype.Timestamptz
}

// Idempotent. Flips changed_at only when the fingerprint string
// actually moved. last_seen_at refreshes every call.
func (q *Queries) UpsertEventNewsFingerprint(ctx context.Context, arg UpsertEventNewsFingerprintParams) error {
	_, err := q.db.Exec(ctx, upsertEventNewsFingerprint,
		arg.EventSlug,
		arg.NewsFingerprint,
		arg.AnnotationCount,
		arg.LatestAnnotationAt,
	)
	return err
}

const upsertSemanticFingerprint = `-- name: UpsertSemanticFingerprint :exec
UPDATE polymarket_event_news_fingerprints
SET last_semantic_fingerprint = $1,
    last_semantic_at = NOW(),
    last_semantic_code = $2,
    repeated_count = CASE
        WHEN polymarket_event_news_fingerprints.last_semantic_fingerprint = $1
        THEN polymarket_event_news_fingerprints.repeated_count + 1
        ELSE 0
    END
WHERE event_slug = $3
`

type UpsertSemanticFingerprintParams struct {
	SemanticFingerprint *string
	SemanticCode        *string
	EventSlug           string
}

// Records the most recent semantic-fingerprint + code we shipped for
// this event so the cooldown check can suppress repeats.
func (q *Queries) UpsertSemanticFingerprint(ctx context.Context, arg UpsertSemanticFingerprintParams) error {
	_, err := q.db.Exec(ctx, upsertSemanticFingerprint, arg.SemanticFingerprint, arg.SemanticCode, arg.EventSlug)
	return err
}
