// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AlertExistsByDedupKey(ctx context.Context, dedupKey string) (bool, error)
	// Single-roundtrip statistical summary for the per-bucket reservoir.
	// Powers the DB-backed detector's hot path: count + total + mean + median
	// + p95 + observed time-span, server-side. PERCENTILE_CONT does the heavy
	// lifting so Go code never sorts more than this one row.
	//
	// $3 is the inclusive lower bound; pass NULL (pgtype.Timestamptz{Valid:false})
	// to lift the bound (use all stored history for the bucket).
	BaselineDistribution(ctx context.Context, arg BaselineDistributionParams) (BaselineDistributionRow, error)
	// Compact summary of the per-bucket reservoir without pulling all rows.
	// Used by the readiness gate to skip listing when the baseline is plainly
	// too thin to bother with.
	BaselineSpan(ctx context.Context, arg BaselineSpanParams) (BaselineSpanRow, error)
	// Atomic transition pending|partial_api_limit → running. Idempotent: a
	// second caller picking up the same id will not flip status (status check
	// in the WHERE clause guarantees one writer wins).
	BeginMarketBackfill(ctx context.Context, id int64) error
	// Atomically transition up to $1 pending alerts to 'sending' and return
	// them. The inner SELECT … FOR UPDATE SKIP LOCKED guarantees concurrent
	// senders see disjoint batches even though the outer UPDATE runs in its
	// own short-lived transaction. A row in `sending` is invisible to the
	// next claimer until MarkAlertSent / MarkAlertSendFailed advances it, or
	// ResetStaleSendingAlerts recovers it after a crashed sender.
	ClaimPendingAlertsForSend(ctx context.Context, limit int32) ([]PolymarketAlerts, error)
	CompleteMarketBackfill(ctx context.Context, arg CompleteMarketBackfillParams) error
	FailMarketBackfill(ctx context.Context, arg FailMarketBackfillParams) error
	GetCategoryByExternalID(ctx context.Context, externalID string) (PolymarketCategories, error)
	GetMarketByConditionID(ctx context.Context, conditionID string) (PolymarketMarkets, error)
	GetMarketByID(ctx context.Context, id int64) (PolymarketMarkets, error)
	GetTraderByWallet(ctx context.Context, walletAddress string) (PolymarketTraders, error)
	// Insert a single trade. ON CONFLICT (dedup_key) DO NOTHING is the dedup
	// primitive — concurrent inserters of the same trade race to the unique
	// constraint and exactly one wins. The caller maps pgx.ErrNoRows to
	// "already existed".
	InsertTrade(ctx context.Context, arg InsertTradeParams) (PolymarketTrades, error)
	// Used by the cluster cooldown gate. Returns NULL when there's been no
	// cluster alert for this market+outcome under the current strategy.
	LatestClusterAlertForCategory(ctx context.Context, arg LatestClusterAlertForCategoryParams) (PolymarketAlerts, error)
	// Used by the collector to advance the per-market sync cursor without
	// keeping an in-process map. Returns NULL when no trades yet exist.
	LatestTradeAt(ctx context.Context, marketID int64) (pgtype.Timestamptz, error)
	LinkMarketCategory(ctx context.Context, arg LinkMarketCategoryParams) error
	// Pick the next batch of markets to backfill, prioritised by upcoming
	// end_date (markets nearer resolution have the most actionable history).
	// Limit is the per-tick claim count.
	ListActiveMarketsForBackfill(ctx context.Context, limit int32) ([]PolymarketMarkets, error)
	// Active markets that have at least started backfill — collection of
	// recent trades only makes sense once we know how far back history goes.
	ListActiveMarketsForCollection(ctx context.Context) ([]PolymarketMarkets, error)
	ListAllCategories(ctx context.Context) ([]PolymarketCategories, error)
	// Per-(market, outcome) baseline samples within the lookback window.
	// Returned newest-first; callers compute median/mean/p95 in domain code
	// (deliberately not in SQL so the same statistics live next to the score
	// function and can be unit-tested without a database).
	ListBaselineTrades(ctx context.Context, arg ListBaselineTradesParams) ([]PolymarketTrades, error)
	// All trades in the per-category cluster window. Used by the cluster
	// detector to count distinct wallets and total notional.
	ListClusterWindowTrades(ctx context.Context, arg ListClusterWindowTradesParams) ([]ListClusterWindowTradesRow, error)
	ListEnabledCategories(ctx context.Context) ([]PolymarketCategories, error)
	ListMarketCategoryIDs(ctx context.Context, marketID int64) ([]int64, error)
	// Used by the BackfillWorker to verify which fetched trade dedup_keys are
	// already persisted (defence in depth on top of ON CONFLICT DO NOTHING).
	ListTradesForBackfillPage(ctx context.Context, arg ListTradesForBackfillPageParams) ([]string, error)
	// Releases the claim back to 'pending' so the next ClaimPending tick can
	// retry. The send_attempts column is bumped + the error message stored so
	// operators can spot poison rows.
	MarkAlertSendFailed(ctx context.Context, arg MarkAlertSendFailedParams) error
	// Completes a claim. Guarded by status='sending' so a duplicate sender
	// racing on a row that was already MarkFailed cannot resurrect it.
	MarkAlertSent(ctx context.Context, arg MarkAlertSentParams) error
	// Mark categories as inactive when they did not appear in the latest
	// Polymarket /tags response. `enabled` is left alone — operator intent is
	// preserved across upstream churn.
	MarkCategoriesNotInListInactive(ctx context.Context, seenExternalIds []string) error
	// Set the local `enabled` flag for one category. Called once per
	// CATEGORY_WHITELIST entry on app boot.
	MarkCategoryEnabled(ctx context.Context, arg MarkCategoryEnabledParams) error
	// Mark active markets inactive when they did not appear in the latest
	// whitelisted-categories discovery sweep. Scoped by category to avoid
	// penalising markets in categories we don't currently sync.
	MarkMarketsInactiveNotIn(ctx context.Context, arg MarkMarketsInactiveNotInParams) error
	OldestTradeAt(ctx context.Context, marketID int64) (pgtype.Timestamptz, error)
	// Recovery: a process that crashed mid-backfill leaves rows in 'running'.
	// This resets any 'running' row whose backfill_started_at is older than
	// the supplied threshold, so the next scheduler tick re-claims them.
	ResetStaleRunningBackfills(ctx context.Context, backfillStartedAt pgtype.Timestamptz) error
	// Crash recovery: any row that's been in 'sending' for longer than the
	// supplied cutoff is moved back to 'pending'. Called by the sender worker
	// on each tick (cheap when zero rows match).
	ResetStaleSendingAlerts(ctx context.Context, updatedAt pgtype.Timestamptz) error
	// Aggregate stats for one trader since the given timestamp. Used to enrich
	// the alert payload ("this wallet's typical bet size over the last 90d").
	TraderStats(ctx context.Context, arg TraderStatsParams) (TraderStatsRow, error)
	// Atomic dedup primitive. INSERT ON CONFLICT DO NOTHING returns zero rows
	// when an alert with the same dedup_key already exists — the caller maps
	// that to "skip send". Concurrent detectors arriving at the same finding
	// still produce exactly one row.
	TryCreatePendingAlert(ctx context.Context, arg TryCreatePendingAlertParams) (PolymarketAlerts, error)
	UnlinkMarketCategoriesNotIn(ctx context.Context, arg UnlinkMarketCategoriesNotInParams) error
	// Insert-or-update a Polymarket category. `enabled` is preserved on update
	// (it's a local setting driven by CATEGORY_WHITELIST, not Polymarket data).
	UpsertCategory(ctx context.Context, arg UpsertCategoryParams) (PolymarketCategories, error)
	// Insert or update a market by condition_id. Backfill state fields are
	// preserved on update — only discovery-sourced fields are touched. A
	// previously-inactive market that reappears flips `active=TRUE` and the
	// next BackfillWorker tick will pick up missing history.
	UpsertMarket(ctx context.Context, arg UpsertMarketParams) (PolymarketMarkets, error)
	UpsertMarketOutcome(ctx context.Context, arg UpsertMarketOutcomeParams) error
	// Insert a trader by wallet address; on conflict bump last_seen_at.
	UpsertTrader(ctx context.Context, walletAddress string) (PolymarketTraders, error)
}

var _ Querier = (*Queries)(nil)
