// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Server-side aggregate over one wallet's recent trades on a single
	// (market, outcome, side) bucket. Powers the same-trader accumulation
	// detector — the entire line scoring runs from this one row, with no
	// per-trade transfer. Backed by idx_trades_trader_market_outcome_side_time.
	//
	// $5 is the inclusive lower bound on traded_at; pass NULL to lift the
	// bound (use the wallet's full stored history on this bucket).
	//
	// avg_price is the mean of `price`. Callers convert to mean odds via
	// 1/avg_price when price > 0. max_odds is computed server-side as the
	// minimum price's inverse (price closest to 0 ⇒ largest odds).
	AccumulationLineSummary(ctx context.Context, arg AccumulationLineSummaryParams) (AccumulationLineSummaryRow, error)
	AlertExistsByDedupKey(ctx context.Context, dedupKey string) (bool, error)
	// Single-roundtrip statistical summary for the per-bucket reservoir.
	// Powers the DB-backed detector's hot path: count + total + mean + median
	// + p95 + observed time-span, server-side. PERCENTILE_CONT does the heavy
	// lifting so Go code never sorts more than this one row.
	//
	// $3 is the inclusive lower bound; pass NULL (pgtype.Timestamptz{Valid:false})
	// to lift the bound (use all stored history for the bucket).
	BaselineDistribution(ctx context.Context, arg BaselineDistributionParams) (BaselineDistributionRow, error)
	// Compact summary of the per-bucket reservoir without pulling all rows.
	// Used by the readiness gate to skip listing when the baseline is plainly
	// too thin to bother with.
	BaselineSpan(ctx context.Context, arg BaselineSpanParams) (BaselineSpanRow, error)
	// Atomic transition pending|partial_api_limit → running. Idempotent: a
	// second caller picking up the same id will not flip status (status check
	// in the WHERE clause guarantees one writer wins).
	BeginMarketBackfill(ctx context.Context, id int64) error
	// Atomically transition up to $1 alerts to 'sending' and return them. The
	// inner SELECT … FOR UPDATE SKIP LOCKED guarantees concurrent senders see
	// disjoint batches even though the outer UPDATE runs in its own short-
	// lived transaction. A row in `sending` is invisible to the next claimer
	// until MarkAlertSent / MarkAlertSendFailed advances it, or
	// ResetStaleSendingAlerts recovers it after a crashed sender.
	//
	// v4 hardening: the claim picks up BOTH pending rows AND retry-eligible
	// failed rows (status='failed' AND next_retry_at <= now()). The retry
	// worker is the same alertsender; there is no separate retry path.
	ClaimPendingAlertsForSend(ctx context.Context, limit int32) ([]PolymarketAlerts, error)
	CompleteMarketBackfill(ctx context.Context, arg CompleteMarketBackfillParams) error
	FailMarketBackfill(ctx context.Context, arg FailMarketBackfillParams) error
	GetCategoryByExternalID(ctx context.Context, externalID string) (PolymarketCategories, error)
	GetMarketByConditionID(ctx context.Context, conditionID string) (PolymarketMarkets, error)
	GetMarketByID(ctx context.Context, id int64) (PolymarketMarkets, error)
	GetTraderByWallet(ctx context.Context, walletAddress string) (PolymarketTraders, error)
	// Insert a single trade. ON CONFLICT (dedup_key) DO NOTHING is the dedup
	// primitive — concurrent inserters of the same trade race to the unique
	// constraint and exactly one wins. The caller maps pgx.ErrNoRows to
	// "already existed".
	InsertTrade(ctx context.Context, arg InsertTradeParams) (PolymarketTrades, error)
	// Returns the most recent traded_at for a (market, outcome) STRICTLY before
	// the supplied timestamp. NULL when no prior trade exists. Powers the
	// quiet-market wake-up detector — given the current trade's timestamp it
	// yields the gap to the previous historical trade so the detector can
	// judge "idle for how long?" without re-listing rows.
	LastTradeAtBefore(ctx context.Context, arg LastTradeAtBeforeParams) (pgtype.Timestamptz, error)
	// Used by the cluster cooldown gate. Returns NULL when there's been no
	// cluster alert for this market+outcome under the current strategy.
	LatestClusterAlertForCategory(ctx context.Context, arg LatestClusterAlertForCategoryParams) (PolymarketAlerts, error)
	// Used by the collector to advance the per-market sync cursor without
	// keeping an in-process map. Returns NULL when no trades yet exist.
	LatestTradeAt(ctx context.Context, marketID int64) (pgtype.Timestamptz, error)
	LinkMarketCategory(ctx context.Context, arg LinkMarketCategoryParams) error
	// Pick the next batch of markets to backfill, prioritised by upcoming
	// end_date (markets nearer resolution have the most actionable history).
	// Excludes soft-deleted and purged markets — backfill never wastes API
	// pages on a market we have no intent to monitor.
	ListActiveMarketsForBackfill(ctx context.Context, limit int32) ([]PolymarketMarkets, error)
	// Active markets that have at least started backfill — collection of
	// recent trades only makes sense once we know how far back history goes.
	// Excludes soft-deleted and purged markets.
	ListActiveMarketsForCollection(ctx context.Context) ([]PolymarketMarkets, error)
	ListAllCategories(ctx context.Context) ([]PolymarketCategories, error)
	// Per-(market, outcome) baseline samples within the lookback window.
	// Returned newest-first; callers compute median/mean/p95 in domain code
	// (deliberately not in SQL so the same statistics live next to the score
	// function and can be unit-tested without a database).
	ListBaselineTrades(ctx context.Context, arg ListBaselineTradesParams) ([]PolymarketTrades, error)
	// All trades in the per-category cluster window. Used by the cluster
	// detector to count distinct wallets and total notional.
	ListClusterWindowTrades(ctx context.Context, arg ListClusterWindowTradesParams) ([]ListClusterWindowTradesRow, error)
	ListEnabledCategories(ctx context.Context) ([]PolymarketCategories, error)
	ListMarketCategoryIDs(ctx context.Context, marketID int64) ([]int64, error)
	// Used by the drift worker. Returns sent alerts whose drift is still
	// pending AND whose oldest reference window (15m by convention) has
	// already elapsed. Bounded by claim_limit per tick.
	ListSentAlertsForDrift(ctx context.Context, arg ListSentAlertsForDriftParams) ([]PolymarketAlerts, error)
	// Used by the outcomes worker. Returns sent alerts whose outcome is
	// still pending, prioritised by oldest-unchecked-first so a single
	// alert that keeps failing the upstream lookup doesn't starve fresher
	// candidates. The query joins polymarket_markets to filter for markets
	// whose end_date has passed (or which are flagged closed) — we only
	// check markets that could plausibly be resolved.
	ListSentAlertsForOutcomeCheck(ctx context.Context, claimLimit int32) ([]PolymarketAlerts, error)
	// Used by the sanity worker (internal/app/usecase/sanity) to find markets
	// whose soft-delete retention window has elapsed. Returns markets that:
	//   - have been soft-deleted (deleted_at IS NOT NULL)
	//   - are not already purged (purged_at IS NULL)
	//   - crossed the retention cutoff
	// The worker then re-checks the market against the latest discover sweep;
	// a market that has resumed flips back via UpsertMarket; one that is
	// still gone gets stamped purged_at.
	ListSoftDeletedForPurge(ctx context.Context, arg ListSoftDeletedForPurgeParams) ([]PolymarketMarkets, error)
	// Used by the BackfillWorker to verify which fetched trade dedup_keys are
	// already persisted (defence in depth on top of ON CONFLICT DO NOTHING).
	ListTradesForBackfillPage(ctx context.Context, arg ListTradesForBackfillPageParams) ([]string, error)
	// Persists the four CLV-lite windows. A NULL CLV column means the
	// reference price for that window was unavailable (e.g. no later trade
	// on the same (market, outcome)). drift_status flips to 'available'
	// when at least one window produced a number; 'unavailable' otherwise.
	MarkAlertDrift(ctx context.Context, arg MarkAlertDriftParams) error
	// Stamps the outcome verdict on a sent alert. Called by the outcomes
	// worker after it has consulted Polymarket's market state. status must
	// be one of: resolved_correct, resolved_wrong, unknown, unavailable.
	MarkAlertOutcome(ctx context.Context, arg MarkAlertOutcomeParams) error
	// Bumps outcome_checked_at on alerts where the upstream check failed
	// transiently (e.g. Polymarket /markets/{id} returned an error or a
	// not-yet-resolved market). Keeps the row scheduled for re-check at the
	// next tick without changing the verdict.
	MarkAlertOutcomeUnavailableTouch(ctx context.Context, id int64) error
	// Records a failed delivery attempt. The caller has already computed
	// next_retry_at (NULL = exhausted / permanent; non-NULL = retryable
	// at the supplied wall-clock time). Status flips to 'failed' regardless
	// — the claim query picks up retryable-failed rows on the next tick.
	MarkAlertSendFailed(ctx context.Context, arg MarkAlertSendFailedParams) error
	// Completes a claim. Guarded by status='sending' so a duplicate sender
	// racing on a row that was already MarkFailed cannot resurrect it. Clears
	// retry state so a row that succeeded after a failure does not keep its
	// schedule.
	MarkAlertSent(ctx context.Context, arg MarkAlertSentParams) error
	// Mark categories as inactive when they did not appear in the latest
	// Polymarket /tags response. `enabled` is left alone — operator intent is
	// preserved across upstream churn.
	MarkCategoriesNotInListInactive(ctx context.Context, seenExternalIds []string) error
	// Set the local `enabled` flag for one category. Called once per
	// CATEGORY_WHITELIST entry on app boot.
	MarkCategoryEnabled(ctx context.Context, arg MarkCategoryEnabledParams) error
	// Stamps purged_at and leaves the row intact. Trades retained for
	// analytics — the FK from polymarket_trades.market_id does not CASCADE
	// on the trade side, so a row delete would orphan trades.
	MarkMarketPurged(ctx context.Context, id int64) error
	// Mark active markets inactive AND stamp deleted_at when they did not
	// appear in the latest whitelisted-categories discovery sweep. Scoped by
	// category so markets in non-whitelisted categories are untouched.
	// The soft-delete marker (deleted_at) is set only on the active→inactive
	// transition — if a market was already inactive we leave its marker alone
	// so the sanity worker's retention window starts at the original
	// disappearance, not at every subsequent tick.
	MarkMarketsInactiveNotIn(ctx context.Context, arg MarkMarketsInactiveNotInParams) error
	OldestTradeAt(ctx context.Context, marketID int64) (pgtype.Timestamptz, error)
	// Called by the sanity worker (or future supervised paths) when a market
	// is resumed: clears deleted_at, flips active, resets backfill to pending
	// so the BackfillWorker picks up missing history on the next tick.
	// Discovery's UpsertMarket already handles the live-sweep case; this
	// query covers the path where the sanity worker confirms resumption via
	// a fresh DB read.
	RequeueResumedMarket(ctx context.Context, id int64) error
	// Recovery: a process that crashed mid-backfill leaves rows in 'running'.
	// This resets any 'running' row whose backfill_started_at is older than
	// the supplied threshold, so the next scheduler tick re-claims them.
	ResetStaleRunningBackfills(ctx context.Context, backfillStartedAt pgtype.Timestamptz) error
	// Crash recovery: any row that's been in 'sending' for longer than the
	// supplied cutoff is moved back to 'pending'. Called by the sender worker
	// on each tick (cheap when zero rows match).
	ResetStaleSendingAlerts(ctx context.Context, updatedAt pgtype.Timestamptz) error
	// Returns the price of the FIRST trade on (market, outcome_token) at or
	// after the supplied timestamp. NULL when no later trade exists yet.
	// Powers the CLV-lite drift worker's per-window reference price lookup.
	TradePriceAtOrAfter(ctx context.Context, arg TradePriceAtOrAfterParams) (float64, error)
	// Per-(trader, market, outcome) two-sided activity over the supplied
	// lookback. Powers the MM/arbitrage suppression filter: a wallet that
	// has been hitting BUY and SELL on the same outcome in roughly balanced
	// notional is almost certainly a market maker or arbitrageur, not an
	// informed-flow candidate, so the detector suppresses single-trade
	// alerts on that wallet/market/outcome.
	//
	// $4 is the inclusive lower bound on traded_at; pass NULL to lift the
	// bound (use the trader's full stored history on this bucket).
	TraderMarketSideActivity(ctx context.Context, arg TraderMarketSideActivityParams) (TraderMarketSideActivityRow, error)
	// Per-wallet distributional summary computed server-side in a single
	// roundtrip. Powers the trader-history multiplier in the detector — a
	// $50k bet from a wallet whose typical trade is $200 is qualitatively
	// different from a $50k bet from a $1M whale, and that distinction is
	// what this query exposes. Shape mirrors BaselineDistribution so callers
	// can reuse the same readiness gates and Stats type.
	//
	// $2 is the inclusive lower bound on traded_at; pass NULL to lift the
	// bound (use the trader's full stored history).
	TraderStats(ctx context.Context, arg TraderStatsParams) (TraderStatsRow, error)
	// Atomic dedup primitive. INSERT ON CONFLICT DO NOTHING returns zero rows
	// when an alert with the same dedup_key already exists — the caller maps
	// that to "skip send". Concurrent detectors arriving at the same finding
	// still produce exactly one row.
	TryCreatePendingAlert(ctx context.Context, arg TryCreatePendingAlertParams) (PolymarketAlerts, error)
	UnlinkMarketCategoriesNotIn(ctx context.Context, arg UnlinkMarketCategoriesNotInParams) error
	// Insert-or-update a Polymarket category. `enabled` is preserved on update
	// (it's a local setting driven by CATEGORY_WHITELIST, not Polymarket data).
	UpsertCategory(ctx context.Context, arg UpsertCategoryParams) (PolymarketCategories, error)
	// Insert or update a market by condition_id. Backfill state fields are
	// preserved on update — only discovery-sourced fields are touched. A
	// market resurfacing after a soft-delete:
	//   - active flips to TRUE
	//   - deleted_at is cleared (the sanity worker would otherwise hard-purge
	//     the row at retention; clearing the marker reactivates processing)
	//   - purged_at is left as-is (purged markets stay purged forever; trades
	//     remain queryable but the market is excluded from collect/backfill)
	// The next BackfillWorker tick picks up missing history because
	// ApplyWhitelist callers re-stamp backfill_status='pending' on resume.
	UpsertMarket(ctx context.Context, arg UpsertMarketParams) (PolymarketMarkets, error)
	UpsertMarketOutcome(ctx context.Context, arg UpsertMarketOutcomeParams) error
	// Insert a trader by wallet address; on conflict bump last_seen_at.
	UpsertTrader(ctx context.Context, walletAddress string) (PolymarketTraders, error)
}

var _ Querier = (*Queries)(nil)
