// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signal_reports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const tryCreatePendingSignalReport = `-- name: TryCreatePendingSignalReport :one
INSERT INTO polymarket_signal_reports (
    period_type, period_start, period_end, scheduled_at,
    status, payload, dedup_key
) VALUES (
    $1::text,
    $2::timestamptz,
    $3::timestamptz,
    $4::timestamptz,
    'pending',
    $5::jsonb,
    $6::text
)
ON CONFLICT (dedup_key) DO NOTHING
RETURNING id
`

type TryCreatePendingSignalReportParams struct {
	PeriodType  string
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
	ScheduledAt pgtype.Timestamptz
	Payload     []byte
	DedupKey    string
}

// Idempotent claim. ON CONFLICT DO NOTHING + RETURNING id means a
// "no row returned" result on a duplicate, mapped to pgx.ErrNoRows by
// the caller — that's the "another worker already inserted" path.
func (q *Queries) TryCreatePendingSignalReport(ctx context.Context, arg TryCreatePendingSignalReportParams) (int64, error) {
	row := q.db.QueryRow(ctx, tryCreatePendingSignalReport,
		arg.PeriodType, arg.PeriodStart, arg.PeriodEnd, arg.ScheduledAt,
		arg.Payload, arg.DedupKey,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markSignalReportSent = `-- name: MarkSignalReportSent :exec
UPDATE polymarket_signal_reports
SET status              = 'sent',
    sent_at             = NOW(),
    telegram_message_id = $2::bigint,
    last_error          = NULL,
    updated_at          = NOW()
WHERE id = $1
`

type MarkSignalReportSentParams struct {
	ID                int64
	TelegramMessageID *int64
}

func (q *Queries) MarkSignalReportSent(ctx context.Context, arg MarkSignalReportSentParams) error {
	_, err := q.db.Exec(ctx, markSignalReportSent, arg.ID, arg.TelegramMessageID)
	return err
}

const markSignalReportFailed = `-- name: MarkSignalReportFailed :exec
UPDATE polymarket_signal_reports
SET status     = 'failed',
    last_error = $2::text,
    updated_at = NOW()
WHERE id = $1
`

type MarkSignalReportFailedParams struct {
	ID        int64
	LastError string
}

func (q *Queries) MarkSignalReportFailed(ctx context.Context, arg MarkSignalReportFailedParams) error {
	_, err := q.db.Exec(ctx, markSignalReportFailed, arg.ID, arg.LastError)
	return err
}

const latestSignalReportByPeriodType = `-- name: LatestSignalReportByPeriodType :one
SELECT id, period_type, period_start, period_end, scheduled_at, sent_at,
       status, telegram_message_id, last_error, payload, dedup_key,
       created_at, updated_at
FROM polymarket_signal_reports
WHERE period_type = $1
ORDER BY period_end DESC
LIMIT 1
`

func (q *Queries) LatestSignalReportByPeriodType(ctx context.Context, periodType string) (PolymarketSignalReports, error) {
	row := q.db.QueryRow(ctx, latestSignalReportByPeriodType, periodType)
	var i PolymarketSignalReports
	err := row.Scan(
		&i.ID, &i.PeriodType, &i.PeriodStart, &i.PeriodEnd, &i.ScheduledAt, &i.SentAt,
		&i.Status, &i.TelegramMessageID, &i.LastError, &i.Payload, &i.DedupKey,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const signalQualityAggregate = `-- name: SignalQualityAggregate :one
SELECT
    COUNT(*)::bigint                                                                     AS total_alerts,
    COUNT(*) FILTER (WHERE outcome_status = 'resolved_correct')::bigint                 AS success_count,
    COUNT(*) FILTER (WHERE outcome_status = 'resolved_wrong')::bigint                   AS failure_count,
    COUNT(*) FILTER (WHERE outcome_status = 'unknown')::bigint                          AS ambiguous_count,
    COUNT(*) FILTER (WHERE outcome_status = 'unavailable')::bigint                      AS unavailable_count,
    COUNT(*) FILTER (WHERE outcome_status = 'pending')::bigint                          AS pending_count,
    COALESCE(AVG(clv_24h) FILTER (WHERE clv_24h IS NOT NULL), 0)::double precision      AS avg_clv_24h,
    COUNT(*) FILTER (WHERE clv_24h IS NOT NULL AND clv_24h > 0)::bigint                 AS positive_clv_24h_count,
    COUNT(*) FILTER (WHERE clv_24h IS NOT NULL)::bigint                                 AS clv_24h_sample_count
FROM polymarket_alerts
WHERE sent_at IS NOT NULL
  AND sent_at >= $1::timestamptz
  AND sent_at <  $2::timestamptz
`

type SignalQualityAggregateParams struct {
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
}

type SignalQualityAggregateRow struct {
	TotalAlerts         int64
	SuccessCount        int64
	FailureCount        int64
	AmbiguousCount      int64
	UnavailableCount    int64
	PendingCount        int64
	AvgClv24h           float64
	PositiveClv24hCount int64
	Clv24hSampleCount   int64
}

func (q *Queries) SignalQualityAggregate(ctx context.Context, arg SignalQualityAggregateParams) (SignalQualityAggregateRow, error) {
	row := q.db.QueryRow(ctx, signalQualityAggregate, arg.PeriodStart, arg.PeriodEnd)
	var i SignalQualityAggregateRow
	err := row.Scan(
		&i.TotalAlerts, &i.SuccessCount, &i.FailureCount, &i.AmbiguousCount,
		&i.UnavailableCount, &i.PendingCount,
		&i.AvgClv24h, &i.PositiveClv24hCount, &i.Clv24hSampleCount,
	)
	return i, err
}

const signalQualityByKind = `-- name: SignalQualityByKind :many
SELECT
    kind,
    COUNT(*)::bigint                                                                  AS total,
    COUNT(*) FILTER (WHERE outcome_status = 'resolved_correct')::bigint              AS success,
    COUNT(*) FILTER (WHERE outcome_status = 'resolved_wrong')::bigint                AS failure,
    COUNT(*) FILTER (WHERE outcome_status IN ('pending','unavailable','unknown'))::bigint AS unresolved
FROM polymarket_alerts
WHERE sent_at IS NOT NULL
  AND sent_at >= $1::timestamptz
  AND sent_at <  $2::timestamptz
GROUP BY kind
ORDER BY total DESC
`

type SignalQualityByKindRow struct {
	Kind       string
	Total      int64
	Success    int64
	Failure    int64
	Unresolved int64
}

func (q *Queries) SignalQualityByKind(ctx context.Context, arg SignalQualityAggregateParams) ([]SignalQualityByKindRow, error) {
	rows, err := q.db.Query(ctx, signalQualityByKind, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []SignalQualityByKindRow{}
	for rows.Next() {
		var r SignalQualityByKindRow
		if err := rows.Scan(&r.Kind, &r.Total, &r.Success, &r.Failure, &r.Unresolved); err != nil {
			return nil, err
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

const signalQualityBySeverity = `-- name: SignalQualityBySeverity :many
SELECT
    severity,
    COUNT(*)::bigint                                                                  AS total,
    COUNT(*) FILTER (WHERE outcome_status = 'resolved_correct')::bigint              AS success,
    COUNT(*) FILTER (WHERE outcome_status = 'resolved_wrong')::bigint                AS failure,
    COUNT(*) FILTER (WHERE outcome_status IN ('pending','unavailable','unknown'))::bigint AS unresolved
FROM polymarket_alerts
WHERE sent_at IS NOT NULL
  AND sent_at >= $1::timestamptz
  AND sent_at <  $2::timestamptz
GROUP BY severity
ORDER BY total DESC
`

type SignalQualityBySeverityRow struct {
	Severity   string
	Total      int64
	Success    int64
	Failure    int64
	Unresolved int64
}

func (q *Queries) SignalQualityBySeverity(ctx context.Context, arg SignalQualityAggregateParams) ([]SignalQualityBySeverityRow, error) {
	rows, err := q.db.Query(ctx, signalQualityBySeverity, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []SignalQualityBySeverityRow{}
	for rows.Next() {
		var r SignalQualityBySeverityRow
		if err := rows.Scan(&r.Severity, &r.Total, &r.Success, &r.Failure, &r.Unresolved); err != nil {
			return nil, err
		}
		out = append(out, r)
	}
	return out, rows.Err()
}
