// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: strategy_shadow.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeMarketRiskScore = `-- name: ActiveMarketRiskScore :one
SELECT condition_id, score_version, ambiguity_score, dispute_risk,
       reasons_json, computed_at
FROM polymarket_market_risk_scores
WHERE condition_id = $1 AND is_active = TRUE
ORDER BY computed_at DESC
LIMIT 1
`

type ActiveMarketRiskScoreRow struct {
	ConditionID    string
	ScoreVersion   int32
	AmbiguityScore float64
	DisputeRisk    float64
	ReasonsJson    []byte
	ComputedAt     pgtype.Timestamptz
}

func (q *Queries) ActiveMarketRiskScore(ctx context.Context, conditionID string) (ActiveMarketRiskScoreRow, error) {
	row := q.db.QueryRow(ctx, activeMarketRiskScore, conditionID)
	var i ActiveMarketRiskScoreRow
	err := row.Scan(
		&i.ConditionID,
		&i.ScoreVersion,
		&i.AmbiguityScore,
		&i.DisputeRisk,
		&i.ReasonsJson,
		&i.ComputedAt,
	)
	return i, err
}

const aggregatePromotionSamples = `-- name: AggregatePromotionSamples :many
SELECT strategy_name,
       COALESCE(strategy_version, '') AS strategy_version,
       COUNT(*)::INTEGER AS sample_size,
       COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY clv_6h), 0)::DOUBLE PRECISION AS median_signed_move_6h,
       COALESCE(AVG(CASE WHEN clv_15m IS NOT NULL AND clv_15m > 0 AND clv_1h IS NOT NULL AND clv_1h <= 0 THEN 1.0 ELSE 0.0 END), 0)::DOUBLE PRECISION AS reversal_15m_ratio,
       (COUNT(*)::DOUBLE PRECISION / GREATEST(EXTRACT(EPOCH FROM (NOW() - MIN(fired_at))) / 86400, 1))::DOUBLE PRECISION AS alerts_per_day
FROM polymarket_strategy_shadow_decisions
WHERE fired_at >= $1
  -- v11.8: exclude probe/test/integration rows so promotion never
  -- promotes a strategy that only ever saw synthetic data.
  AND COALESCE(strategy_version, '') NOT ILIKE '%integration%'
  AND COALESCE(strategy_version, '') NOT ILIKE '%probe%'
  AND COALESCE(strategy_version, '') NOT ILIKE '%test%'
  -- require at least one CLV column to be filled so promotion never
  -- runs on rows the value evaluator hasn't touched yet.
  AND clv_6h IS NOT NULL
GROUP BY strategy_name, strategy_version
`

type AggregatePromotionSamplesRow struct {
	StrategyName       string
	StrategyVersion    string
	SampleSize         int32
	MedianSignedMove6h float64
	Reversal15mRatio   float64
	AlertsPerDay       float64
}

func (q *Queries) AggregatePromotionSamples(ctx context.Context, lookbackStart pgtype.Timestamptz) ([]AggregatePromotionSamplesRow, error) {
	rows, err := q.db.Query(ctx, aggregatePromotionSamples, lookbackStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregatePromotionSamplesRow
	for rows.Next() {
		var i AggregatePromotionSamplesRow
		if err := rows.Scan(
			&i.StrategyName,
			&i.StrategyVersion,
			&i.SampleSize,
			&i.MedianSignedMove6h,
			&i.Reversal15mRatio,
			&i.AlertsPerDay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregatePromotionSamplesByDecisionLevel = `-- name: AggregatePromotionSamplesByDecisionLevel :many

SELECT strategy_name,
       COALESCE(strategy_version, '') AS strategy_version,
       COALESCE(decision_level, 'unknown') AS bucket_key,
       COUNT(*)::INTEGER AS sample_size,
       COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY clv_6h), 0)::DOUBLE PRECISION AS median_signed_move_6h,
       COALESCE(AVG(CASE WHEN clv_15m IS NOT NULL AND clv_15m > 0 AND clv_1h IS NOT NULL AND clv_1h <= 0 THEN 1.0 ELSE 0.0 END), 0)::DOUBLE PRECISION AS reversal_15m_ratio,
       (COUNT(*)::DOUBLE PRECISION / GREATEST(EXTRACT(EPOCH FROM (NOW() - MIN(fired_at))) / 86400, 1))::DOUBLE PRECISION AS alerts_per_day
FROM polymarket_strategy_shadow_decisions
WHERE fired_at >= $1
  AND COALESCE(strategy_version, '') NOT ILIKE '%integration%'
  AND COALESCE(strategy_version, '') NOT ILIKE '%probe%'
  AND COALESCE(strategy_version, '') NOT ILIKE '%test%'
  AND clv_6h IS NOT NULL
GROUP BY strategy_name, strategy_version, decision_level
ORDER BY strategy_name, strategy_version, bucket_key
`

type AggregatePromotionSamplesByDecisionLevelRow struct {
	StrategyName       string
	StrategyVersion    string
	BucketKey          string
	SampleSize         int32
	MedianSignedMove6h float64
	Reversal15mRatio   float64
	AlertsPerDay       float64
}

// v11.10 PART 7 — bucketed promotion samples (decision_level dim).
// Per-(strategy, version, decision_level) sub-aggregate. The Go layer
// joins this with AggregatePromotionSamplesByLinkage to assemble the
// bucket_diagnostics JSONB column on the review row.
func (q *Queries) AggregatePromotionSamplesByDecisionLevel(ctx context.Context, lookbackStart pgtype.Timestamptz) ([]AggregatePromotionSamplesByDecisionLevelRow, error) {
	rows, err := q.db.Query(ctx, aggregatePromotionSamplesByDecisionLevel, lookbackStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregatePromotionSamplesByDecisionLevelRow
	for rows.Next() {
		var i AggregatePromotionSamplesByDecisionLevelRow
		if err := rows.Scan(
			&i.StrategyName,
			&i.StrategyVersion,
			&i.BucketKey,
			&i.SampleSize,
			&i.MedianSignedMove6h,
			&i.Reversal15mRatio,
			&i.AlertsPerDay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregatePromotionSamplesByLinkage = `-- name: AggregatePromotionSamplesByLinkage :many
SELECT strategy_name,
       COALESCE(strategy_version, '') AS strategy_version,
       CASE WHEN linked_alert_dedup_key IS NULL OR linked_alert_dedup_key = ''
            THEN 'standalone' ELSE 'linked' END AS bucket_key,
       COUNT(*)::INTEGER AS sample_size,
       COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY clv_6h), 0)::DOUBLE PRECISION AS median_signed_move_6h,
       COALESCE(AVG(CASE WHEN clv_15m IS NOT NULL AND clv_15m > 0 AND clv_1h IS NOT NULL AND clv_1h <= 0 THEN 1.0 ELSE 0.0 END), 0)::DOUBLE PRECISION AS reversal_15m_ratio,
       (COUNT(*)::DOUBLE PRECISION / GREATEST(EXTRACT(EPOCH FROM (NOW() - MIN(fired_at))) / 86400, 1))::DOUBLE PRECISION AS alerts_per_day
FROM polymarket_strategy_shadow_decisions
WHERE fired_at >= $1
  AND COALESCE(strategy_version, '') NOT ILIKE '%integration%'
  AND COALESCE(strategy_version, '') NOT ILIKE '%probe%'
  AND COALESCE(strategy_version, '') NOT ILIKE '%test%'
  AND clv_6h IS NOT NULL
GROUP BY strategy_name, strategy_version, bucket_key
ORDER BY strategy_name, strategy_version, bucket_key
`

type AggregatePromotionSamplesByLinkageRow struct {
	StrategyName       string
	StrategyVersion    string
	BucketKey          string
	SampleSize         int32
	MedianSignedMove6h float64
	Reversal15mRatio   float64
	AlertsPerDay       float64
}

func (q *Queries) AggregatePromotionSamplesByLinkage(ctx context.Context, lookbackStart pgtype.Timestamptz) ([]AggregatePromotionSamplesByLinkageRow, error) {
	rows, err := q.db.Query(ctx, aggregatePromotionSamplesByLinkage, lookbackStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregatePromotionSamplesByLinkageRow
	for rows.Next() {
		var i AggregatePromotionSamplesByLinkageRow
		if err := rows.Scan(
			&i.StrategyName,
			&i.StrategyVersion,
			&i.BucketKey,
			&i.SampleSize,
			&i.MedianSignedMove6h,
			&i.Reversal15mRatio,
			&i.AlertsPerDay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateWalletThesisLines = `-- name: AggregateWalletThesisLines :many

SELECT COALESCE(tr.wallet_address, '')              AS wallet,
       m.condition_id                               AS condition_id,
       COALESCE(m.event_slug, '')                   AS event_slug,
       t.side::text                                 AS side,
       SUM(t.notional_usd)::DOUBLE PRECISION        AS notional_usd,
       COUNT(*)::INTEGER                            AS trades,
       MAX(t.traded_at)::TIMESTAMPTZ                AS last_traded_at
FROM polymarket_trades t
JOIN polymarket_traders tr ON tr.id = t.trader_id
JOIN polymarket_markets m  ON m.id = t.market_id
WHERE t.traded_at >= $1
  AND tr.wallet_address IS NOT NULL AND tr.wallet_address <> ''
  AND m.event_slug IS NOT NULL AND m.event_slug <> ''
GROUP BY tr.wallet_address, m.condition_id, m.event_slug, t.side
HAVING COUNT(*) >= 2
ORDER BY MAX(t.traded_at) DESC
LIMIT $2
`

type AggregateWalletThesisLinesParams struct {
	Since    pgtype.Timestamptz
	RowLimit int32
}

type AggregateWalletThesisLinesRow struct {
	Wallet       string
	ConditionID  string
	EventSlug    string
	Side         string
	NotionalUsd  float64
	Trades       int32
	LastTradedAt pgtype.Timestamptz
}

// v11.9 PART 5 — thesis lines wallet aggregate.
// Aggregates per (wallet, condition_id) directional exposure across
// linked markets within a lookback window. The orchestration layer
// groups these rows by event_slug to feed thesisaccum.
func (q *Queries) AggregateWalletThesisLines(ctx context.Context, arg AggregateWalletThesisLinesParams) ([]AggregateWalletThesisLinesRow, error) {
	rows, err := q.db.Query(ctx, aggregateWalletThesisLines, arg.Since, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateWalletThesisLinesRow
	for rows.Next() {
		var i AggregateWalletThesisLinesRow
		if err := rows.Scan(
			&i.Wallet,
			&i.ConditionID,
			&i.EventSlug,
			&i.Side,
			&i.NotionalUsd,
			&i.Trades,
			&i.LastTradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeRepricingWindow = `-- name: CloseRepricingWindow :exec
UPDATE polymarket_repricing_windows
SET status         = $1,
    resolved_at    = NOW(),
    observed_move  = $2,
    peer_move      = $3,
    lag_score      = $4,
    notes          = $5
WHERE id = $6
`

type CloseRepricingWindowParams struct {
	Status       string
	ObservedMove *float64
	PeerMove     *float64
	LagScore     *float64
	Notes        string
	ID           int64
}

func (q *Queries) CloseRepricingWindow(ctx context.Context, arg CloseRepricingWindowParams) error {
	_, err := q.db.Exec(ctx, closeRepricingWindow,
		arg.Status,
		arg.ObservedMove,
		arg.PeerMove,
		arg.LagScore,
		arg.Notes,
		arg.ID,
	)
	return err
}

const firstTradePriceForCondition = `-- name: FirstTradePriceForCondition :one
SELECT t.price::DOUBLE PRECISION AS price
FROM polymarket_trades t
JOIN polymarket_markets m ON m.id = t.market_id
WHERE m.condition_id = $1
  AND t.traded_at >= $2
ORDER BY t.traded_at ASC
LIMIT 1
`

type FirstTradePriceForConditionParams struct {
	ConditionID string
	At          pgtype.Timestamptz
}

// Returns the first trade price for (condition_id, traded_at >= @at).
// Used by the repricing close-phase target sampler.
func (q *Queries) FirstTradePriceForCondition(ctx context.Context, arg FirstTradePriceForConditionParams) (float64, error) {
	row := q.db.QueryRow(ctx, firstTradePriceForCondition, arg.ConditionID, arg.At)
	var price float64
	err := row.Scan(&price)
	return price, err
}

const getActiveRiskScoreForCondition = `-- name: GetActiveRiskScoreForCondition :one
SELECT condition_id, ambiguity_score, dispute_risk, reasons_json, computed_at
FROM polymarket_market_risk_scores
WHERE condition_id = $1 AND is_active = TRUE
ORDER BY computed_at DESC
LIMIT 1
`

type GetActiveRiskScoreForConditionRow struct {
	ConditionID    string
	AmbiguityScore float64
	DisputeRisk    float64
	ReasonsJson    []byte
	ComputedAt     pgtype.Timestamptz
}

func (q *Queries) GetActiveRiskScoreForCondition(ctx context.Context, conditionID string) (GetActiveRiskScoreForConditionRow, error) {
	row := q.db.QueryRow(ctx, getActiveRiskScoreForCondition, conditionID)
	var i GetActiveRiskScoreForConditionRow
	err := row.Scan(
		&i.ConditionID,
		&i.AmbiguityScore,
		&i.DisputeRisk,
		&i.ReasonsJson,
		&i.ComputedAt,
	)
	return i, err
}

const insertRepricingWindow = `-- name: InsertRepricingWindow :one

INSERT INTO polymarket_repricing_windows (
    condition_id, event_slug, trigger_kind, trigger_ref,
    opened_at, closes_at, expected_impact_min, expected_impact_max,
    side_bias, baseline_price
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10
)
RETURNING id
`

type InsertRepricingWindowParams struct {
	ConditionID       string
	EventSlug         string
	TriggerKind       string
	TriggerRef        string
	OpenedAt          pgtype.Timestamptz
	ClosesAt          pgtype.Timestamptz
	ExpectedImpactMin *float64
	ExpectedImpactMax *float64
	SideBias          string
	BaselinePrice     *float64
}

// =========================================================================
// Repricing windows
// =========================================================================
func (q *Queries) InsertRepricingWindow(ctx context.Context, arg InsertRepricingWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRepricingWindow,
		arg.ConditionID,
		arg.EventSlug,
		arg.TriggerKind,
		arg.TriggerRef,
		arg.OpenedAt,
		arg.ClosesAt,
		arg.ExpectedImpactMin,
		arg.ExpectedImpactMax,
		arg.SideBias,
		arg.BaselinePrice,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStrategyPromotionReview = `-- name: InsertStrategyPromotionReview :exec

INSERT INTO polymarket_strategy_promotion_reviews (
    strategy_name, strategy_version, sample_size,
    median_signed_move_6h, reversal_15m_ratio, alerts_per_day,
    eligible, reasons_json, bucket_diagnostics, reviewed_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10
)
`

type InsertStrategyPromotionReviewParams struct {
	StrategyName       string
	StrategyVersion    string
	SampleSize         int32
	MedianSignedMove6h float64
	Reversal15mRatio   float64
	AlertsPerDay       float64
	Eligible           bool
	ReasonsJson        []byte
	BucketDiagnostics  []byte
	ReviewedAt         pgtype.Timestamptz
}

// v11.6 PART 7 — promotion review queries.
func (q *Queries) InsertStrategyPromotionReview(ctx context.Context, arg InsertStrategyPromotionReviewParams) error {
	_, err := q.db.Exec(ctx, insertStrategyPromotionReview,
		arg.StrategyName,
		arg.StrategyVersion,
		arg.SampleSize,
		arg.MedianSignedMove6h,
		arg.Reversal15mRatio,
		arg.AlertsPerDay,
		arg.Eligible,
		arg.ReasonsJson,
		arg.BucketDiagnostics,
		arg.ReviewedAt,
	)
	return err
}

const insertStrategyShadowDecision = `-- name: InsertStrategyShadowDecision :one


INSERT INTO polymarket_strategy_shadow_decisions (
    strategy_name, strategy_version, condition_id, event_slug, wallet,
    cohort_id, side, decision_kind, decision_level, score, confidence,
    reasons_json, features_json, shadow_only, linked_alert_dedup_key,
    control_bucket_key
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15,
    $16
)
RETURNING id
`

type InsertStrategyShadowDecisionParams struct {
	StrategyName        string
	StrategyVersion     string
	ConditionID         string
	EventSlug           string
	Wallet              string
	CohortID            *string
	Side                string
	DecisionKind        string
	DecisionLevel       string
	Score               float64
	Confidence          float64
	ReasonsJson         []byte
	FeaturesJson        []byte
	ShadowOnly          bool
	LinkedAlertDedupKey *string
	ControlBucketKey    string
}

// v11.5 Strategy Learning Loop queries (Wave P0).
// =========================================================================
// Shadow decisions
// =========================================================================
func (q *Queries) InsertStrategyShadowDecision(ctx context.Context, arg InsertStrategyShadowDecisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertStrategyShadowDecision,
		arg.StrategyName,
		arg.StrategyVersion,
		arg.ConditionID,
		arg.EventSlug,
		arg.Wallet,
		arg.CohortID,
		arg.Side,
		arg.DecisionKind,
		arg.DecisionLevel,
		arg.Score,
		arg.Confidence,
		arg.ReasonsJson,
		arg.FeaturesJson,
		arg.ShadowOnly,
		arg.LinkedAlertDedupKey,
		arg.ControlBucketKey,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lastTradePriceForCondition = `-- name: LastTradePriceForCondition :one
SELECT t.price::DOUBLE PRECISION AS price
FROM polymarket_trades t
JOIN polymarket_markets m ON m.id = t.market_id
WHERE m.condition_id = $1
  AND t.traded_at <= $2
ORDER BY t.traded_at DESC
LIMIT 1
`

type LastTradePriceForConditionParams struct {
	ConditionID string
	At          pgtype.Timestamptz
}

// Returns the most recent trade price for (condition_id, traded_at <= @at).
func (q *Queries) LastTradePriceForCondition(ctx context.Context, arg LastTradePriceForConditionParams) (float64, error) {
	row := q.db.QueryRow(ctx, lastTradePriceForCondition, arg.ConditionID, arg.At)
	var price float64
	err := row.Scan(&price)
	return price, err
}

const latestHolderSnapshot = `-- name: LatestHolderSnapshot :one
SELECT id, condition_id, outcome_token, snapshot_at, wallet, rank,
       shares, notional_usd, pct_oi, total_oi, created_at
FROM polymarket_holder_snapshots
WHERE condition_id = $1
  AND outcome_token = $2
  AND wallet = $3
ORDER BY snapshot_at DESC
LIMIT 1
`

type LatestHolderSnapshotParams struct {
	ConditionID  string
	OutcomeToken string
	Wallet       string
}

type LatestHolderSnapshotRow struct {
	ID           int64
	ConditionID  string
	OutcomeToken string
	SnapshotAt   pgtype.Timestamptz
	Wallet       string
	Rank         int32
	Shares       float64
	NotionalUsd  float64
	PctOi        float64
	TotalOi      float64
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) LatestHolderSnapshot(ctx context.Context, arg LatestHolderSnapshotParams) (LatestHolderSnapshotRow, error) {
	row := q.db.QueryRow(ctx, latestHolderSnapshot, arg.ConditionID, arg.OutcomeToken, arg.Wallet)
	var i LatestHolderSnapshotRow
	err := row.Scan(
		&i.ID,
		&i.ConditionID,
		&i.OutcomeToken,
		&i.SnapshotAt,
		&i.Wallet,
		&i.Rank,
		&i.Shares,
		&i.NotionalUsd,
		&i.PctOi,
		&i.TotalOi,
		&i.CreatedAt,
	)
	return i, err
}

const listBookbarsCandidates = `-- name: ListBookbarsCandidates :many
SELECT m.condition_id, COALESCE(mo.token_id, '') AS token_id
FROM polymarket_markets m
JOIN polymarket_market_outcomes mo ON mo.market_id = m.id
WHERE m.active = TRUE AND m.closed = FALSE
  AND m.deleted_at IS NULL AND m.purged_at IS NULL
  AND mo.token_id IS NOT NULL AND mo.token_id <> ''
ORDER BY m.last_seen_at DESC NULLS LAST
LIMIT $1
`

type ListBookbarsCandidatesRow struct {
	ConditionID string
	TokenID     string
}

// Active tokens for bookbars worker. Bounded by limit.
func (q *Queries) ListBookbarsCandidates(ctx context.Context, rowLimit int32) ([]ListBookbarsCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listBookbarsCandidates, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookbarsCandidatesRow
	for rows.Next() {
		var i ListBookbarsCandidatesRow
		if err := rows.Scan(&i.ConditionID, &i.TokenID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBucketedMarketTokens = `-- name: ListBucketedMarketTokens :many

WITH pinned AS (
    SELECT m.condition_id, 1::int AS bucket
    FROM polymarket_markets m
    WHERE m.deleted_at IS NULL AND m.purged_at IS NULL
      AND m.condition_id = ANY($1::text[])
    LIMIT $2::int
),
recent_alert AS (
    SELECT DISTINCT pm.condition_id, 2::int AS bucket
    FROM polymarket_alerts a
    JOIN polymarket_markets pm ON pm.id = a.market_id
    WHERE a.created_at > NOW() - INTERVAL '24 hours'
      AND pm.deleted_at IS NULL AND pm.purged_at IS NULL
    LIMIT $3::int
),
catalyst_near AS (
    SELECT DISTINCT pm.condition_id, 3::int AS bucket
    FROM polymarket_event_catalysts c
    JOIN polymarket_markets pm ON pm.event_slug = c.event_slug
    WHERE c.status IN ('active','expected')
      AND pm.deleted_at IS NULL AND pm.purged_at IS NULL
      AND (c.expected_at IS NULL OR c.expected_at <= NOW() + INTERVAL '72 hours')
    LIMIT $4::int
),
linked_to_fired AS (
    SELECT DISTINCT ml.src_condition_id AS condition_id, 4::int AS bucket
    FROM polymarket_market_links ml
    JOIN polymarket_alerts a ON a.created_at > NOW() - INTERVAL '24 hours'
    JOIN polymarket_markets pm_a ON pm_a.id = a.market_id
    WHERE ml.dst_condition_id = pm_a.condition_id
    UNION
    SELECT DISTINCT ml.dst_condition_id, 4::int AS bucket
    FROM polymarket_market_links ml
    JOIN polymarket_alerts a ON a.created_at > NOW() - INTERVAL '24 hours'
    JOIN polymarket_markets pm_a ON pm_a.id = a.market_id
    WHERE ml.src_condition_id = pm_a.condition_id
    LIMIT $5::int
),
liquid AS (
    SELECT q.condition_id, 5::int AS bucket
    FROM (
        SELECT pm.condition_id, MAX(em.liquidity) AS max_liq
        FROM polymarket_event_page_markets em
        JOIN polymarket_markets pm ON pm.condition_id = em.condition_id
        WHERE em.created_at > NOW() - INTERVAL '24 hours'
          AND em.active = TRUE
          AND pm.deleted_at IS NULL AND pm.purged_at IS NULL
        GROUP BY pm.condition_id
    ) q
    ORDER BY q.max_liq DESC NULLS LAST
    LIMIT $6::int
),
fallback_active AS (
    SELECT m.condition_id, 6::int AS bucket
    FROM polymarket_markets m
    WHERE m.active = TRUE AND m.closed = FALSE
      AND m.deleted_at IS NULL AND m.purged_at IS NULL
    ORDER BY m.last_seen_at DESC NULLS LAST
    LIMIT $7::int
),
unioned AS (
    SELECT condition_id, bucket FROM pinned
    UNION ALL SELECT condition_id, bucket FROM recent_alert
    UNION ALL SELECT condition_id, bucket FROM catalyst_near
    UNION ALL SELECT condition_id, bucket FROM linked_to_fired
    UNION ALL SELECT condition_id, bucket FROM liquid
    UNION ALL SELECT condition_id, bucket FROM fallback_active
),
dedup AS (
    SELECT condition_id, MIN(bucket) AS bucket
    FROM unioned
    GROUP BY condition_id
)
SELECT d.condition_id::text   AS condition_id,
       COALESCE(mo.token_id, '')::text AS token_id,
       d.bucket::int          AS bucket
FROM dedup d
JOIN polymarket_markets m ON m.condition_id = d.condition_id
JOIN polymarket_market_outcomes mo ON mo.market_id = m.id
WHERE mo.token_id IS NOT NULL AND mo.token_id <> ''
ORDER BY d.bucket ASC, d.condition_id ASC
`

type ListBucketedMarketTokensParams struct {
	PinnedConditionIds []string
	PinnedLimit        int32
	RecentAlertLimit   int32
	CatalystNearLimit  int32
	LinkedToFiredLimit int32
	LiquidLimit        int32
	FallbackLimit      int32
}

type ListBucketedMarketTokensRow struct {
	ConditionID string
	TokenID     string
	Bucket      int32
}

// v11.10 PART 6 — worker priority-bucket budgeting.
// Returns deduped (condition_id, token_id) pairs annotated with their
// highest-priority bucket. Buckets:
//
//	1 = operator-pinned (explicit condition_ids array)
//	2 = recent-alert (≤24h)
//	3 = catalyst-near (status active/expected, ≤72h ahead)
//	4 = linked-to-fired (market_links neighbour of any recent alert)
//	5 = liquid (top by Polymarket liquidity, recent event-page snapshot)
//	6 = fallback active (last_seen_at DESC)
//
// Each bucket respects its own LIMIT so a fat bucket can't starve the
// others. Dedupe keeps the MIN(bucket) per condition_id — once a
// market is operator-pinned it is not double-counted as fallback.
func (q *Queries) ListBucketedMarketTokens(ctx context.Context, arg ListBucketedMarketTokensParams) ([]ListBucketedMarketTokensRow, error) {
	rows, err := q.db.Query(ctx, listBucketedMarketTokens,
		arg.PinnedConditionIds,
		arg.PinnedLimit,
		arg.RecentAlertLimit,
		arg.CatalystNearLimit,
		arg.LinkedToFiredLimit,
		arg.LiquidLimit,
		arg.FallbackLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBucketedMarketTokensRow
	for rows.Next() {
		var i ListBucketedMarketTokensRow
		if err := rows.Scan(&i.ConditionID, &i.TokenID, &i.Bucket); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalystsForEvent = `-- name: ListCatalystsForEvent :many
SELECT event_slug, COALESCE(catalyst_type, 'generic') AS catalyst_type,
       title, expected_at,
       COALESCE(confidence, 0.5)::DOUBLE PRECISION AS confidence,
       status
FROM polymarket_event_catalysts
WHERE event_slug = $1
  AND status IN ('expected', 'active')
ORDER BY expected_at ASC NULLS LAST
LIMIT $2
`

type ListCatalystsForEventParams struct {
	EventSlug string
	RowLimit  int32
}

type ListCatalystsForEventRow struct {
	EventSlug    string
	CatalystType string
	Title        string
	ExpectedAt   pgtype.Timestamptz
	Confidence   float64
	Status       string
}

func (q *Queries) ListCatalystsForEvent(ctx context.Context, arg ListCatalystsForEventParams) ([]ListCatalystsForEventRow, error) {
	rows, err := q.db.Query(ctx, listCatalystsForEvent, arg.EventSlug, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatalystsForEventRow
	for rows.Next() {
		var i ListCatalystsForEventRow
		if err := rows.Scan(
			&i.EventSlug,
			&i.CatalystType,
			&i.Title,
			&i.ExpectedAt,
			&i.Confidence,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClosedRepricingWindowsForCondition = `-- name: ListClosedRepricingWindowsForCondition :many
SELECT id, condition_id, event_slug, trigger_kind, trigger_ref, opened_at, closes_at,
       status, observed_move, peer_move, lag_score
FROM polymarket_repricing_windows
WHERE condition_id = $1
  AND status IN ('closed_lag_detected', 'closed_no_lag')
  AND opened_at >= $2
ORDER BY opened_at DESC
LIMIT $3
`

type ListClosedRepricingWindowsForConditionParams struct {
	ConditionID string
	Since       pgtype.Timestamptz
	RowLimit    int32
}

type ListClosedRepricingWindowsForConditionRow struct {
	ID           int64
	ConditionID  string
	EventSlug    string
	TriggerKind  string
	TriggerRef   string
	OpenedAt     pgtype.Timestamptz
	ClosesAt     pgtype.Timestamptz
	Status       string
	ObservedMove *float64
	PeerMove     *float64
	LagScore     *float64
}

func (q *Queries) ListClosedRepricingWindowsForCondition(ctx context.Context, arg ListClosedRepricingWindowsForConditionParams) ([]ListClosedRepricingWindowsForConditionRow, error) {
	rows, err := q.db.Query(ctx, listClosedRepricingWindowsForCondition, arg.ConditionID, arg.Since, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClosedRepricingWindowsForConditionRow
	for rows.Next() {
		var i ListClosedRepricingWindowsForConditionRow
		if err := rows.Scan(
			&i.ID,
			&i.ConditionID,
			&i.EventSlug,
			&i.TriggerKind,
			&i.TriggerRef,
			&i.OpenedAt,
			&i.ClosesAt,
			&i.Status,
			&i.ObservedMove,
			&i.PeerMove,
			&i.LagScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventGroupedMarkets = `-- name: ListEventGroupedMarkets :many

SELECT COALESCE(event_slug, '')::TEXT AS event_slug,
       array_agg(condition_id ORDER BY id ASC)::text[] AS condition_ids
FROM polymarket_markets
WHERE event_slug IS NOT NULL AND event_slug <> ''
  AND deleted_at IS NULL
  AND purged_at IS NULL
GROUP BY event_slug
HAVING COUNT(*) >= 2
ORDER BY MAX(updated_at) DESC
LIMIT $1
`

type ListEventGroupedMarketsRow struct {
	EventSlug    string
	ConditionIds []string
}

// v11.7 PART 2 — marketlinks Builder production source.
// Returns market sets grouped by event_slug, capped by limit.
func (q *Queries) ListEventGroupedMarkets(ctx context.Context, rowLimit int32) ([]ListEventGroupedMarketsRow, error) {
	rows, err := q.db.Query(ctx, listEventGroupedMarkets, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventGroupedMarketsRow
	for rows.Next() {
		var i ListEventGroupedMarketsRow
		if err := rows.Scan(&i.EventSlug, &i.ConditionIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketLinksBySource = `-- name: ListMarketLinksBySource :many
SELECT id, src_condition_id, dst_condition_id, link_type, direction,
       confidence, event_slug, series_id, link_version, created_at, updated_at
FROM polymarket_market_links
WHERE src_condition_id = $1
  AND link_version = $2
ORDER BY confidence DESC, link_type ASC
`

type ListMarketLinksBySourceParams struct {
	SrcConditionID string
	LinkVersion    int32
}

func (q *Queries) ListMarketLinksBySource(ctx context.Context, arg ListMarketLinksBySourceParams) ([]PolymarketMarketLinks, error) {
	rows, err := q.db.Query(ctx, listMarketLinksBySource, arg.SrcConditionID, arg.LinkVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketMarketLinks
	for rows.Next() {
		var i PolymarketMarketLinks
		if err := rows.Scan(
			&i.ID,
			&i.SrcConditionID,
			&i.DstConditionID,
			&i.LinkType,
			&i.Direction,
			&i.Confidence,
			&i.EventSlug,
			&i.SeriesID,
			&i.LinkVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketLinksForEvent = `-- name: ListMarketLinksForEvent :many

SELECT src_condition_id, dst_condition_id, link_type, direction, confidence, event_slug
FROM polymarket_market_links
WHERE event_slug = $1 AND link_version = $2
ORDER BY confidence DESC
LIMIT $3
`

type ListMarketLinksForEventParams struct {
	EventSlug   string
	LinkVersion int32
	RowLimit    int32
}

type ListMarketLinksForEventRow struct {
	SrcConditionID string
	DstConditionID string
	LinkType       string
	Direction      string
	Confidence     float64
	EventSlug      string
}

// v11.8 PART 5 — staged input readers.
func (q *Queries) ListMarketLinksForEvent(ctx context.Context, arg ListMarketLinksForEventParams) ([]ListMarketLinksForEventRow, error) {
	rows, err := q.db.Query(ctx, listMarketLinksForEvent, arg.EventSlug, arg.LinkVersion, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketLinksForEventRow
	for rows.Next() {
		var i ListMarketLinksForEventRow
		if err := rows.Scan(
			&i.SrcConditionID,
			&i.DstConditionID,
			&i.LinkType,
			&i.Direction,
			&i.Confidence,
			&i.EventSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenRepricingWindows = `-- name: ListOpenRepricingWindows :many

SELECT id, condition_id, event_slug, trigger_kind, trigger_ref,
       opened_at, closes_at, side_bias, baseline_price
FROM polymarket_repricing_windows
WHERE status = 'open' AND closes_at <= $1
ORDER BY closes_at ASC
LIMIT $2
`

type ListOpenRepricingWindowsParams struct {
	DueBefore pgtype.Timestamptz
	RowLimit  int32
}

type ListOpenRepricingWindowsRow struct {
	ID            int64
	ConditionID   string
	EventSlug     string
	TriggerKind   string
	TriggerRef    string
	OpenedAt      pgtype.Timestamptz
	ClosesAt      pgtype.Timestamptz
	SideBias      string
	BaselinePrice *float64
}

// v11.9 PART 4 — repricing close-phase price sampler.
func (q *Queries) ListOpenRepricingWindows(ctx context.Context, arg ListOpenRepricingWindowsParams) ([]ListOpenRepricingWindowsRow, error) {
	rows, err := q.db.Query(ctx, listOpenRepricingWindows, arg.DueBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenRepricingWindowsRow
	for rows.Next() {
		var i ListOpenRepricingWindowsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConditionID,
			&i.EventSlug,
			&i.TriggerKind,
			&i.TriggerRef,
			&i.OpenedAt,
			&i.ClosesAt,
			&i.SideBias,
			&i.BaselinePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeerConditionsByMarketLinks = `-- name: ListPeerConditionsByMarketLinks :many
SELECT DISTINCT dst_condition_id
FROM polymarket_market_links
WHERE src_condition_id = $1
  AND link_version = $2
LIMIT $3
`

type ListPeerConditionsByMarketLinksParams struct {
	SrcConditionID string
	LinkVersion    int32
	RowLimit       int32
}

// Returns peer condition_ids from polymarket_market_links anchored
// on @src_condition_id. Bounded by the link_version + a row limit.
func (q *Queries) ListPeerConditionsByMarketLinks(ctx context.Context, arg ListPeerConditionsByMarketLinksParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPeerConditionsByMarketLinks, arg.SrcConditionID, arg.LinkVersion, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var dst_condition_id string
		if err := rows.Scan(&dst_condition_id); err != nil {
			return nil, err
		}
		items = append(items, dst_condition_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingValueRows = `-- name: ListPendingValueRows :many

SELECT id, strategy_name, condition_id,
       COALESCE(event_slug, '') AS event_slug,
       COALESCE(wallet, '')     AS wallet,
       COALESCE(side, '')       AS side,
       fired_at,
       clv_15m, clv_1h, clv_6h, clv_24h
FROM polymarket_strategy_shadow_decisions
WHERE (clv_15m IS NULL OR clv_1h IS NULL OR clv_6h IS NULL OR clv_24h IS NULL)
  AND fired_at > $1
ORDER BY fired_at ASC
LIMIT $2
`

type ListPendingValueRowsParams struct {
	MaxAge   pgtype.Timestamptz
	RowLimit int32
}

type ListPendingValueRowsRow struct {
	ID           int64
	StrategyName string
	ConditionID  string
	EventSlug    string
	Wallet       string
	Side         string
	FiredAt      pgtype.Timestamptz
	Clv15m       *float64
	Clv1h        *float64
	Clv6h        *float64
	Clv24h       *float64
}

// v11.6 PART 6 — shadow value evaluator queries.
func (q *Queries) ListPendingValueRows(ctx context.Context, arg ListPendingValueRowsParams) ([]ListPendingValueRowsRow, error) {
	rows, err := q.db.Query(ctx, listPendingValueRows, arg.MaxAge, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingValueRowsRow
	for rows.Next() {
		var i ListPendingValueRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.StrategyName,
			&i.ConditionID,
			&i.EventSlug,
			&i.Wallet,
			&i.Side,
			&i.FiredAt,
			&i.Clv15m,
			&i.Clv1h,
			&i.Clv6h,
			&i.Clv24h,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentShadowDecisionsForCondition = `-- name: ListRecentShadowDecisionsForCondition :many
SELECT id, strategy_name, side, decision_kind, decision_level, score, confidence, fired_at
FROM polymarket_strategy_shadow_decisions
WHERE condition_id = $1
  AND fired_at >= $2
ORDER BY fired_at DESC
LIMIT $3
`

type ListRecentShadowDecisionsForConditionParams struct {
	ConditionID string
	Since       pgtype.Timestamptz
	RowLimit    int32
}

type ListRecentShadowDecisionsForConditionRow struct {
	ID            int64
	StrategyName  string
	Side          string
	DecisionKind  string
	DecisionLevel string
	Score         float64
	Confidence    float64
	FiredAt       pgtype.Timestamptz
}

func (q *Queries) ListRecentShadowDecisionsForCondition(ctx context.Context, arg ListRecentShadowDecisionsForConditionParams) ([]ListRecentShadowDecisionsForConditionRow, error) {
	rows, err := q.db.Query(ctx, listRecentShadowDecisionsForCondition, arg.ConditionID, arg.Since, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentShadowDecisionsForConditionRow
	for rows.Next() {
		var i ListRecentShadowDecisionsForConditionRow
		if err := rows.Scan(
			&i.ID,
			&i.StrategyName,
			&i.Side,
			&i.DecisionKind,
			&i.DecisionLevel,
			&i.Score,
			&i.Confidence,
			&i.FiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepricingTriggers = `-- name: ListRepricingTriggers :many

SELECT c.id, c.event_slug, c.title,
       COALESCE(c.catalyst_type, 'generic') AS catalyst_type,
       c.expected_at,
       COALESCE(c.confidence, 0.5)::DOUBLE PRECISION AS confidence
FROM polymarket_event_catalysts c
WHERE c.expected_at >= $1
  AND c.status IN ('expected', 'active')
ORDER BY c.expected_at DESC
LIMIT $2
`

type ListRepricingTriggersParams struct {
	Since    pgtype.Timestamptz
	RowLimit int32
}

type ListRepricingTriggersRow struct {
	ID           int64
	EventSlug    string
	Title        string
	CatalystType string
	ExpectedAt   pgtype.Timestamptz
	Confidence   float64
}

// v11.7 PART 5 — repricing trigger source.
// New unprocessed catalyst rows over the recent lookback window.
func (q *Queries) ListRepricingTriggers(ctx context.Context, arg ListRepricingTriggersParams) ([]ListRepricingTriggersRow, error) {
	rows, err := q.db.Query(ctx, listRepricingTriggers, arg.Since, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepricingTriggersRow
	for rows.Next() {
		var i ListRepricingTriggersRow
		if err := rows.Scan(
			&i.ID,
			&i.EventSlug,
			&i.Title,
			&i.CatalystType,
			&i.ExpectedAt,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskScoreCandidates = `-- name: ListRiskScoreCandidates :many

SELECT m.id, m.condition_id, m.question,
       COALESCE(m.event_title, '') AS event_title,
       COALESCE(rs.computed_at, '1970-01-01'::timestamptz) AS last_computed
FROM polymarket_markets m
LEFT JOIN polymarket_market_risk_scores rs
  ON rs.condition_id = m.condition_id AND rs.is_active = TRUE
WHERE m.deleted_at IS NULL AND m.purged_at IS NULL
ORDER BY last_computed ASC, m.id DESC
LIMIT $1
`

type ListRiskScoreCandidatesRow struct {
	ID           int64
	ConditionID  string
	Question     string
	EventTitle   string
	LastComputed pgtype.Timestamptz
}

// v11.7 PART 4 — riskscore production source.
// Returns market facts in bounded batches, ordered by stale-first.
func (q *Queries) ListRiskScoreCandidates(ctx context.Context, rowLimit int32) ([]ListRiskScoreCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listRiskScoreCandidates, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiskScoreCandidatesRow
	for rows.Next() {
		var i ListRiskScoreCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConditionID,
			&i.Question,
			&i.EventTitle,
			&i.LastComputed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShadowDecisionsByStrategy = `-- name: ListShadowDecisionsByStrategy :many
SELECT id, strategy_name, strategy_version, condition_id, event_slug,
       wallet, cohort_id, side, decision_kind, decision_level, score,
       confidence, reasons_json, features_json, shadow_only, fired_at,
       linked_alert_dedup_key, control_bucket_key, clv_15m, clv_1h,
       clv_6h, clv_24h, outcome_status, created_at
FROM polymarket_strategy_shadow_decisions
WHERE strategy_name = $1 AND fired_at >= $2
ORDER BY fired_at DESC
LIMIT $3
`

type ListShadowDecisionsByStrategyParams struct {
	StrategyName string
	Since        pgtype.Timestamptz
	RowLimit     int32
}

func (q *Queries) ListShadowDecisionsByStrategy(ctx context.Context, arg ListShadowDecisionsByStrategyParams) ([]PolymarketStrategyShadowDecisions, error) {
	rows, err := q.db.Query(ctx, listShadowDecisionsByStrategy, arg.StrategyName, arg.Since, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketStrategyShadowDecisions
	for rows.Next() {
		var i PolymarketStrategyShadowDecisions
		if err := rows.Scan(
			&i.ID,
			&i.StrategyName,
			&i.StrategyVersion,
			&i.ConditionID,
			&i.EventSlug,
			&i.Wallet,
			&i.CohortID,
			&i.Side,
			&i.DecisionKind,
			&i.DecisionLevel,
			&i.Score,
			&i.Confidence,
			&i.ReasonsJson,
			&i.FeaturesJson,
			&i.ShadowOnly,
			&i.FiredAt,
			&i.LinkedAlertDedupKey,
			&i.ControlBucketKey,
			&i.Clv15m,
			&i.Clv1h,
			&i.Clv6h,
			&i.Clv24h,
			&i.OutcomeStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShadowRowsForOutcomeBackfill = `-- name: ListShadowRowsForOutcomeBackfill :many

SELECT s.id, s.linked_alert_dedup_key,
       COALESCE(a.outcome_status, '') AS alert_outcome
FROM polymarket_strategy_shadow_decisions s
JOIN polymarket_alerts a ON a.dedup_key = s.linked_alert_dedup_key
WHERE s.outcome_status IS NULL
  AND s.linked_alert_dedup_key IS NOT NULL
  AND s.linked_alert_dedup_key <> ''
  AND a.outcome_status IS NOT NULL
  AND a.outcome_status NOT IN ('pending', '')
LIMIT $1
`

type ListShadowRowsForOutcomeBackfillRow struct {
	ID                  int64
	LinkedAlertDedupKey *string
	AlertOutcome        string
}

// v11.7 PART 10 — outcome_status backfill.
// Returns shadow rows linked to alerts that have a terminal outcome.
func (q *Queries) ListShadowRowsForOutcomeBackfill(ctx context.Context, rowLimit int32) ([]ListShadowRowsForOutcomeBackfillRow, error) {
	rows, err := q.db.Query(ctx, listShadowRowsForOutcomeBackfill, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShadowRowsForOutcomeBackfillRow
	for rows.Next() {
		var i ListShadowRowsForOutcomeBackfillRow
		if err := rows.Scan(&i.ID, &i.LinkedAlertDedupKey, &i.AlertOutcome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandaloneResolvedAlertOutcomes = `-- name: ListStandaloneResolvedAlertOutcomes :many

SELECT s.id,
       COALESCE(s.side, '') AS side,
       COALESCE(a.winning_outcome_token, '') AS winning_token,
       COALESCE(a.winning_outcome_label, '') AS winning_label,
       COALESCE(a.outcome_status, '') AS alert_outcome
FROM polymarket_strategy_shadow_decisions s
JOIN polymarket_alerts a ON a.dedup_key = s.linked_alert_dedup_key
WHERE s.outcome_status IS NULL
  AND s.linked_alert_dedup_key IS NOT NULL
  AND s.linked_alert_dedup_key <> ''
  AND a.winning_outcome_token IS NOT NULL
  AND a.winning_outcome_token <> ''
LIMIT $1
`

type ListStandaloneResolvedAlertOutcomesRow struct {
	ID           int64
	Side         string
	WinningToken string
	WinningLabel string
	AlertOutcome string
}

// v11.9 PART 6 — outcome resolver per-side.
// Returns shadow rows linked to an alert with a resolved outcome
// (winning_outcome_token IS NOT NULL). Used by strategyoutcome to
// compute correct/wrong based on the shadow row's Side.
func (q *Queries) ListStandaloneResolvedAlertOutcomes(ctx context.Context, rowLimit int32) ([]ListStandaloneResolvedAlertOutcomesRow, error) {
	rows, err := q.db.Query(ctx, listStandaloneResolvedAlertOutcomes, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStandaloneResolvedAlertOutcomesRow
	for rows.Next() {
		var i ListStandaloneResolvedAlertOutcomesRow
		if err := rows.Scan(
			&i.ID,
			&i.Side,
			&i.WinningToken,
			&i.WinningLabel,
			&i.AlertOutcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandaloneShadowRowsForOutcomeBackfill = `-- name: ListStandaloneShadowRowsForOutcomeBackfill :many
SELECT s.id, s.condition_id, COALESCE(m.closed, FALSE) AS market_closed
FROM polymarket_strategy_shadow_decisions s
LEFT JOIN polymarket_markets m ON m.condition_id = s.condition_id
WHERE s.outcome_status IS NULL
  AND (s.linked_alert_dedup_key IS NULL OR s.linked_alert_dedup_key = '')
  AND m.closed = TRUE
LIMIT $1
`

type ListStandaloneShadowRowsForOutcomeBackfillRow struct {
	ID           int64
	ConditionID  string
	MarketClosed bool
}

func (q *Queries) ListStandaloneShadowRowsForOutcomeBackfill(ctx context.Context, rowLimit int32) ([]ListStandaloneShadowRowsForOutcomeBackfillRow, error) {
	rows, err := q.db.Query(ctx, listStandaloneShadowRowsForOutcomeBackfill, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStandaloneShadowRowsForOutcomeBackfillRow
	for rows.Next() {
		var i ListStandaloneShadowRowsForOutcomeBackfillRow
		if err := rows.Scan(&i.ID, &i.ConditionID, &i.MarketClosed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletCoTradeRows = `-- name: ListWalletCoTradeRows :many

SELECT COALESCE(tr.wallet_address, '')             AS wallet,
       COALESCE(m.event_slug, '')                  AS event_slug,
       t.side::text                                AS side,
       t.traded_at
FROM polymarket_trades t
JOIN polymarket_traders tr ON tr.id = t.trader_id
JOIN polymarket_markets m ON m.id = t.market_id
WHERE t.traded_at >= $1
  AND tr.wallet_address IS NOT NULL
  AND tr.wallet_address <> ''
  AND m.event_slug IS NOT NULL
  AND m.event_slug <> ''
ORDER BY t.traded_at ASC
LIMIT $2
`

type ListWalletCoTradeRowsParams struct {
	Since    pgtype.Timestamptz
	RowLimit int32
}

type ListWalletCoTradeRowsRow struct {
	Wallet    string
	EventSlug string
	Side      string
	TradedAt  pgtype.Timestamptz
}

// v11.7 PART 6 — walletgraph production source.
// Returns recent (wallet, event_slug, side) tuples bounded by lookback.
func (q *Queries) ListWalletCoTradeRows(ctx context.Context, arg ListWalletCoTradeRowsParams) ([]ListWalletCoTradeRowsRow, error) {
	rows, err := q.db.Query(ctx, listWalletCoTradeRows, arg.Since, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWalletCoTradeRowsRow
	for rows.Next() {
		var i ListWalletCoTradeRowsRow
		if err := rows.Scan(
			&i.Wallet,
			&i.EventSlug,
			&i.Side,
			&i.TradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletEdgesForWallet = `-- name: ListWalletEdgesForWallet :many
SELECT wallet_a, wallet_b, edge_kind, similarity_score, co_events_count, last_seen_at
FROM polymarket_wallet_graph_edges
WHERE (wallet_a = $1 OR wallet_b = $1)
  AND edge_version = $2
ORDER BY similarity_score DESC
LIMIT $3
`

type ListWalletEdgesForWalletParams struct {
	Wallet      string
	EdgeVersion int32
	RowLimit    int32
}

type ListWalletEdgesForWalletRow struct {
	WalletA         string
	WalletB         string
	EdgeKind        string
	SimilarityScore float64
	CoEventsCount   int32
	LastSeenAt      pgtype.Timestamptz
}

func (q *Queries) ListWalletEdgesForWallet(ctx context.Context, arg ListWalletEdgesForWalletParams) ([]ListWalletEdgesForWalletRow, error) {
	rows, err := q.db.Query(ctx, listWalletEdgesForWallet, arg.Wallet, arg.EdgeVersion, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWalletEdgesForWalletRow
	for rows.Next() {
		var i ListWalletEdgesForWalletRow
		if err := rows.Scan(
			&i.WalletA,
			&i.WalletB,
			&i.EdgeKind,
			&i.SimilarityScore,
			&i.CoEventsCount,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletThesisLinesForEvent = `-- name: ListWalletThesisLinesForEvent :many
SELECT wallet, condition_id, event_slug, side, notional_usd, trades, last_traded_at
FROM polymarket_wallet_thesis_lines
WHERE event_slug = $1
  AND wallet     = $2
  AND lookback_hours = $3
ORDER BY notional_usd DESC
LIMIT $4
`

type ListWalletThesisLinesForEventParams struct {
	EventSlug     string
	Wallet        string
	LookbackHours int32
	RowLimit      int32
}

type ListWalletThesisLinesForEventRow struct {
	Wallet       string
	ConditionID  string
	EventSlug    string
	Side         string
	NotionalUsd  float64
	Trades       int32
	LastTradedAt pgtype.Timestamptz
}

func (q *Queries) ListWalletThesisLinesForEvent(ctx context.Context, arg ListWalletThesisLinesForEventParams) ([]ListWalletThesisLinesForEventRow, error) {
	rows, err := q.db.Query(ctx, listWalletThesisLinesForEvent,
		arg.EventSlug,
		arg.Wallet,
		arg.LookbackHours,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWalletThesisLinesForEventRow
	for rows.Next() {
		var i ListWalletThesisLinesForEventRow
		if err := rows.Scan(
			&i.Wallet,
			&i.ConditionID,
			&i.EventSlug,
			&i.Side,
			&i.NotionalUsd,
			&i.Trades,
			&i.LastTradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShadowDecisionValues = `-- name: UpdateShadowDecisionValues :exec
UPDATE polymarket_strategy_shadow_decisions
SET clv_15m  = COALESCE(clv_15m,  $1::DOUBLE PRECISION),
    clv_1h   = COALESCE(clv_1h,   $2::DOUBLE PRECISION),
    clv_6h   = COALESCE(clv_6h,   $3::DOUBLE PRECISION),
    clv_24h  = COALESCE(clv_24h,  $4::DOUBLE PRECISION),
    outcome_status = COALESCE(outcome_status, $5::TEXT)
WHERE id = $6
`

type UpdateShadowDecisionValuesParams struct {
	Clv15m        *float64
	Clv1h         *float64
	Clv6h         *float64
	Clv24h        *float64
	OutcomeStatus *string
	ID            int64
}

func (q *Queries) UpdateShadowDecisionValues(ctx context.Context, arg UpdateShadowDecisionValuesParams) error {
	_, err := q.db.Exec(ctx, updateShadowDecisionValues,
		arg.Clv15m,
		arg.Clv1h,
		arg.Clv6h,
		arg.Clv24h,
		arg.OutcomeStatus,
		arg.ID,
	)
	return err
}

const updateShadowOutcomeStatus = `-- name: UpdateShadowOutcomeStatus :exec
UPDATE polymarket_strategy_shadow_decisions
SET outcome_status = $1
WHERE id = $2 AND outcome_status IS NULL
`

type UpdateShadowOutcomeStatusParams struct {
	OutcomeStatus *string
	ID            int64
}

func (q *Queries) UpdateShadowOutcomeStatus(ctx context.Context, arg UpdateShadowOutcomeStatusParams) error {
	_, err := q.db.Exec(ctx, updateShadowOutcomeStatus, arg.OutcomeStatus, arg.ID)
	return err
}

const upsertBookFeatureBar = `-- name: UpsertBookFeatureBar :exec

INSERT INTO polymarket_book_feature_bars (
    condition_id, outcome_token, bar_seconds, bar_start,
    best_bid, best_ask, mid_price,
    bid_depth_top_n, ask_depth_top_n,
    spread, spread_z,
    bid_depth_delta_pct, ask_depth_delta_pct, mid_delta
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11,
    $12, $13, $14
)
ON CONFLICT (condition_id, outcome_token, bar_seconds, bar_start) DO UPDATE
SET best_bid            = EXCLUDED.best_bid,
    best_ask            = EXCLUDED.best_ask,
    mid_price           = EXCLUDED.mid_price,
    bid_depth_top_n     = EXCLUDED.bid_depth_top_n,
    ask_depth_top_n     = EXCLUDED.ask_depth_top_n,
    spread              = EXCLUDED.spread,
    spread_z            = EXCLUDED.spread_z,
    bid_depth_delta_pct = EXCLUDED.bid_depth_delta_pct,
    ask_depth_delta_pct = EXCLUDED.ask_depth_delta_pct,
    mid_delta           = EXCLUDED.mid_delta
`

type UpsertBookFeatureBarParams struct {
	ConditionID      string
	OutcomeToken     string
	BarSeconds       int32
	BarStart         pgtype.Timestamptz
	BestBid          *float64
	BestAsk          *float64
	MidPrice         *float64
	BidDepthTopN     *float64
	AskDepthTopN     *float64
	Spread           *float64
	SpreadZ          *float64
	BidDepthDeltaPct *float64
	AskDepthDeltaPct *float64
	MidDelta         *float64
}

// v11.10 book feature bars upsert.
func (q *Queries) UpsertBookFeatureBar(ctx context.Context, arg UpsertBookFeatureBarParams) error {
	_, err := q.db.Exec(ctx, upsertBookFeatureBar,
		arg.ConditionID,
		arg.OutcomeToken,
		arg.BarSeconds,
		arg.BarStart,
		arg.BestBid,
		arg.BestAsk,
		arg.MidPrice,
		arg.BidDepthTopN,
		arg.AskDepthTopN,
		arg.Spread,
		arg.SpreadZ,
		arg.BidDepthDeltaPct,
		arg.AskDepthDeltaPct,
		arg.MidDelta,
	)
	return err
}

const upsertHolderSnapshot = `-- name: UpsertHolderSnapshot :exec

INSERT INTO polymarket_holder_snapshots (
    condition_id, outcome_token, snapshot_at, wallet, rank, shares,
    notional_usd, pct_oi, total_oi, raw_json
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10
)
ON CONFLICT (condition_id, outcome_token, snapshot_at, wallet) DO UPDATE
SET rank         = EXCLUDED.rank,
    shares       = EXCLUDED.shares,
    notional_usd = EXCLUDED.notional_usd,
    pct_oi       = EXCLUDED.pct_oi,
    total_oi     = EXCLUDED.total_oi,
    raw_json     = EXCLUDED.raw_json
`

type UpsertHolderSnapshotParams struct {
	ConditionID  string
	OutcomeToken string
	SnapshotAt   pgtype.Timestamptz
	Wallet       string
	Rank         int32
	Shares       float64
	NotionalUsd  float64
	PctOi        float64
	TotalOi      float64
	RawJson      []byte
}

// =========================================================================
// Holder snapshots
// =========================================================================
func (q *Queries) UpsertHolderSnapshot(ctx context.Context, arg UpsertHolderSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertHolderSnapshot,
		arg.ConditionID,
		arg.OutcomeToken,
		arg.SnapshotAt,
		arg.Wallet,
		arg.Rank,
		arg.Shares,
		arg.NotionalUsd,
		arg.PctOi,
		arg.TotalOi,
		arg.RawJson,
	)
	return err
}

const upsertMarketLink = `-- name: UpsertMarketLink :exec

INSERT INTO polymarket_market_links (
    src_condition_id, dst_condition_id, link_type, direction,
    confidence, event_slug, series_id, link_version, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, NOW()
)
ON CONFLICT (src_condition_id, dst_condition_id, link_type, link_version) DO UPDATE
SET direction  = EXCLUDED.direction,
    confidence = EXCLUDED.confidence,
    event_slug = EXCLUDED.event_slug,
    series_id  = EXCLUDED.series_id,
    updated_at = NOW()
`

type UpsertMarketLinkParams struct {
	SrcConditionID string
	DstConditionID string
	LinkType       string
	Direction      string
	Confidence     float64
	EventSlug      string
	SeriesID       string
	LinkVersion    int32
}

// =========================================================================
// Market links
// =========================================================================
func (q *Queries) UpsertMarketLink(ctx context.Context, arg UpsertMarketLinkParams) error {
	_, err := q.db.Exec(ctx, upsertMarketLink,
		arg.SrcConditionID,
		arg.DstConditionID,
		arg.LinkType,
		arg.Direction,
		arg.Confidence,
		arg.EventSlug,
		arg.SeriesID,
		arg.LinkVersion,
	)
	return err
}

const upsertMarketRiskScore = `-- name: UpsertMarketRiskScore :exec

INSERT INTO polymarket_market_risk_scores (
    condition_id, score_version, ambiguity_score, dispute_risk,
    reasons_json, is_active
) VALUES (
    $1, $2, $3, $4,
    $5, TRUE
)
ON CONFLICT (condition_id, score_version) DO UPDATE
SET ambiguity_score = EXCLUDED.ambiguity_score,
    dispute_risk    = EXCLUDED.dispute_risk,
    reasons_json    = EXCLUDED.reasons_json,
    is_active       = TRUE,
    computed_at     = NOW()
`

type UpsertMarketRiskScoreParams struct {
	ConditionID    string
	ScoreVersion   int32
	AmbiguityScore float64
	DisputeRisk    float64
	ReasonsJson    []byte
}

// =========================================================================
// Market risk scores
// =========================================================================
func (q *Queries) UpsertMarketRiskScore(ctx context.Context, arg UpsertMarketRiskScoreParams) error {
	_, err := q.db.Exec(ctx, upsertMarketRiskScore,
		arg.ConditionID,
		arg.ScoreVersion,
		arg.AmbiguityScore,
		arg.DisputeRisk,
		arg.ReasonsJson,
	)
	return err
}

const upsertWalletThesisLine = `-- name: UpsertWalletThesisLine :exec

INSERT INTO polymarket_wallet_thesis_lines (
    wallet, condition_id, event_slug, side, notional_usd, trades,
    last_traded_at, lookback_hours, refreshed_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, NOW()
)
ON CONFLICT (wallet, condition_id, side, lookback_hours) DO UPDATE
SET notional_usd   = EXCLUDED.notional_usd,
    trades         = EXCLUDED.trades,
    event_slug     = EXCLUDED.event_slug,
    last_traded_at = EXCLUDED.last_traded_at,
    refreshed_at   = NOW()
`

type UpsertWalletThesisLineParams struct {
	Wallet        string
	ConditionID   string
	EventSlug     string
	Side          string
	NotionalUsd   float64
	Trades        int32
	LastTradedAt  pgtype.Timestamptz
	LookbackHours int32
}

// v11.9 wallet thesis lines.
func (q *Queries) UpsertWalletThesisLine(ctx context.Context, arg UpsertWalletThesisLineParams) error {
	_, err := q.db.Exec(ctx, upsertWalletThesisLine,
		arg.Wallet,
		arg.ConditionID,
		arg.EventSlug,
		arg.Side,
		arg.NotionalUsd,
		arg.Trades,
		arg.LastTradedAt,
		arg.LookbackHours,
	)
	return err
}
