// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trades.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accumulationLineSummary = `-- name: AccumulationLineSummary :one
SELECT
    COUNT(*)::bigint                                                                          AS trade_count,
    COALESCE(SUM(notional_usd), 0)::double precision                                          AS total_notional_usd,
    COALESCE(AVG(notional_usd), 0)::double precision                                          AS mean_notional_usd,
    COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY notional_usd), 0)::double precision  AS median_notional_usd,
    COALESCE(MAX(notional_usd), 0)::double precision                                          AS max_notional_usd,
    COALESCE(MIN(notional_usd), 0)::double precision                                          AS min_notional_usd,
    COALESCE(AVG(price), 0)::double precision                                                 AS avg_price,
    COALESCE(MIN(price), 0)::double precision                                                 AS min_price,
    MIN(traded_at)::timestamptz                                                               AS oldest_at,
    MAX(traded_at)::timestamptz                                                               AS newest_at
FROM polymarket_trades
WHERE trader_id     = $1::bigint
  AND market_id     = $2::bigint
  AND outcome_token = $3::text
  AND side          = $4::text
  AND ($5::timestamptz IS NULL OR traded_at >= $5::timestamptz)
`

type AccumulationLineSummaryParams struct {
	TraderID     int64
	MarketID     int64
	OutcomeToken string
	Side         string
	Since        pgtype.Timestamptz
}

type AccumulationLineSummaryRow struct {
	TradeCount        int64
	TotalNotionalUsd  float64
	MeanNotionalUsd   float64
	MedianNotionalUsd float64
	MaxNotionalUsd    float64
	MinNotionalUsd    float64
	AvgPrice          float64
	MinPrice          float64
	OldestAt          pgtype.Timestamptz
	NewestAt          pgtype.Timestamptz
}

// Server-side aggregate over one wallet's recent trades on a single
// (market, outcome, side) bucket. Powers the same-trader accumulation
// detector — the entire line scoring runs from this one row, with no
// per-trade transfer. Backed by idx_trades_trader_market_outcome_side_time.
//
// $5 is the inclusive lower bound on traded_at; pass NULL to lift the
// bound (use the wallet's full stored history on this bucket).
//
// avg_price is the mean of `price`. Callers convert to mean odds via
// 1/avg_price when price > 0. max_odds is computed server-side as the
// minimum price's inverse (price closest to 0 ⇒ largest odds).
func (q *Queries) AccumulationLineSummary(ctx context.Context, arg AccumulationLineSummaryParams) (AccumulationLineSummaryRow, error) {
	row := q.db.QueryRow(ctx, accumulationLineSummary,
		arg.TraderID,
		arg.MarketID,
		arg.OutcomeToken,
		arg.Side,
		arg.Since,
	)
	var i AccumulationLineSummaryRow
	err := row.Scan(
		&i.TradeCount,
		&i.TotalNotionalUsd,
		&i.MeanNotionalUsd,
		&i.MedianNotionalUsd,
		&i.MaxNotionalUsd,
		&i.MinNotionalUsd,
		&i.AvgPrice,
		&i.MinPrice,
		&i.OldestAt,
		&i.NewestAt,
	)
	return i, err
}

const baselineDistribution = `-- name: BaselineDistribution :one
SELECT
    COUNT(*)::bigint                                                                           AS sample_count,
    COALESCE(SUM(notional_usd), 0)::double precision                                           AS total_notional_usd,
    COALESCE(AVG(notional_usd), 0)::double precision                                           AS mean_notional_usd,
    COALESCE(PERCENTILE_CONT(0.5)  WITHIN GROUP (ORDER BY notional_usd), 0)::double precision  AS median_notional_usd,
    COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY notional_usd), 0)::double precision  AS p95_notional_usd,
    MIN(traded_at)::timestamptz                                                                AS oldest_at,
    MAX(traded_at)::timestamptz                                                                AS newest_at
FROM polymarket_trades
WHERE market_id     = $1::bigint
  AND outcome_token = $2::text
  AND ($3::timestamptz IS NULL OR traded_at >= $3::timestamptz)
`

type BaselineDistributionParams struct {
	MarketID     int64
	OutcomeToken string
	Since        pgtype.Timestamptz
}

type BaselineDistributionRow struct {
	SampleCount       int64
	TotalNotionalUsd  float64
	MeanNotionalUsd   float64
	MedianNotionalUsd float64
	P95NotionalUsd    float64
	OldestAt          pgtype.Timestamptz
	NewestAt          pgtype.Timestamptz
}

// Single-roundtrip statistical summary for the per-bucket reservoir.
// Powers the DB-backed detector's hot path: count + total + mean + median
// + p95 + observed time-span, server-side. PERCENTILE_CONT does the heavy
// lifting so Go code never sorts more than this one row.
//
// $3 is the inclusive lower bound; pass NULL (pgtype.Timestamptz{Valid:false})
// to lift the bound (use all stored history for the bucket).
func (q *Queries) BaselineDistribution(ctx context.Context, arg BaselineDistributionParams) (BaselineDistributionRow, error) {
	row := q.db.QueryRow(ctx, baselineDistribution, arg.MarketID, arg.OutcomeToken, arg.Since)
	var i BaselineDistributionRow
	err := row.Scan(
		&i.SampleCount,
		&i.TotalNotionalUsd,
		&i.MeanNotionalUsd,
		&i.MedianNotionalUsd,
		&i.P95NotionalUsd,
		&i.OldestAt,
		&i.NewestAt,
	)
	return i, err
}

const baselineSpan = `-- name: BaselineSpan :one
SELECT
    COUNT(*)::bigint                                 AS sample_count,
    COALESCE(SUM(notional_usd), 0)::double precision AS total_notional_usd,
    MIN(traded_at)::timestamptz                      AS oldest_at,
    MAX(traded_at)::timestamptz                      AS newest_at
FROM polymarket_trades
WHERE market_id = $1
  AND outcome_token = $2
  AND traded_at >= $3
`

type BaselineSpanParams struct {
	MarketID     int64
	OutcomeToken string
	TradedAt     pgtype.Timestamptz
}

type BaselineSpanRow struct {
	SampleCount      int64
	TotalNotionalUsd float64
	OldestAt         pgtype.Timestamptz
	NewestAt         pgtype.Timestamptz
}

// Compact summary of the per-bucket reservoir without pulling all rows.
// Used by the readiness gate to skip listing when the baseline is plainly
// too thin to bother with.
func (q *Queries) BaselineSpan(ctx context.Context, arg BaselineSpanParams) (BaselineSpanRow, error) {
	row := q.db.QueryRow(ctx, baselineSpan, arg.MarketID, arg.OutcomeToken, arg.TradedAt)
	var i BaselineSpanRow
	err := row.Scan(
		&i.SampleCount,
		&i.TotalNotionalUsd,
		&i.OldestAt,
		&i.NewestAt,
	)
	return i, err
}

const insertTrade = `-- name: InsertTrade :one
INSERT INTO polymarket_trades (
    market_id, trader_id, outcome_token, side,
    price, size_shares, notional_usd,
    traded_at, external_id, tx_hash, dedup_key
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11
)
ON CONFLICT (dedup_key) DO NOTHING
RETURNING id, market_id, trader_id, outcome_token, side, price, size_shares, notional_usd, traded_at, external_id, tx_hash, ingested_at, dedup_key
`

type InsertTradeParams struct {
	MarketID     int64
	TraderID     *int64
	OutcomeToken string
	Side         string
	Price        float64
	SizeShares   float64
	NotionalUsd  float64
	TradedAt     pgtype.Timestamptz
	ExternalID   *string
	TxHash       *string
	DedupKey     string
}

// Insert a single trade. ON CONFLICT (dedup_key) DO NOTHING is the dedup
// primitive — concurrent inserters of the same trade race to the unique
// constraint and exactly one wins. The caller maps pgx.ErrNoRows to
// "already existed".
func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) (PolymarketTrades, error) {
	row := q.db.QueryRow(ctx, insertTrade,
		arg.MarketID,
		arg.TraderID,
		arg.OutcomeToken,
		arg.Side,
		arg.Price,
		arg.SizeShares,
		arg.NotionalUsd,
		arg.TradedAt,
		arg.ExternalID,
		arg.TxHash,
		arg.DedupKey,
	)
	var i PolymarketTrades
	err := row.Scan(
		&i.ID,
		&i.MarketID,
		&i.TraderID,
		&i.OutcomeToken,
		&i.Side,
		&i.Price,
		&i.SizeShares,
		&i.NotionalUsd,
		&i.TradedAt,
		&i.ExternalID,
		&i.TxHash,
		&i.IngestedAt,
		&i.DedupKey,
	)
	return i, err
}

const lastTradeAtBefore = `-- name: LastTradeAtBefore :one
SELECT MAX(traded_at)::timestamptz AS last_at
FROM polymarket_trades
WHERE market_id     = $1::bigint
  AND outcome_token = $2::text
  AND traded_at     < $3::timestamptz
`

type LastTradeAtBeforeParams struct {
	MarketID     int64
	OutcomeToken string
	Before       pgtype.Timestamptz
}

// Returns the most recent traded_at for a (market, outcome) STRICTLY before
// the supplied timestamp. NULL when no prior trade exists. Powers the
// quiet-market wake-up detector — given the current trade's timestamp it
// yields the gap to the previous historical trade so the detector can
// judge "idle for how long?" without re-listing rows.
func (q *Queries) LastTradeAtBefore(ctx context.Context, arg LastTradeAtBeforeParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, lastTradeAtBefore, arg.MarketID, arg.OutcomeToken, arg.Before)
	var last_at pgtype.Timestamptz
	err := row.Scan(&last_at)
	return last_at, err
}

const latestTradeAt = `-- name: LatestTradeAt :one
SELECT MAX(traded_at)::timestamptz AS latest_at
FROM polymarket_trades
WHERE market_id = $1
`

// Used by the collector to advance the per-market sync cursor without
// keeping an in-process map. Returns NULL when no trades yet exist.
func (q *Queries) LatestTradeAt(ctx context.Context, marketID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, latestTradeAt, marketID)
	var latest_at pgtype.Timestamptz
	err := row.Scan(&latest_at)
	return latest_at, err
}

const listBaselineTrades = `-- name: ListBaselineTrades :many
SELECT id, market_id, trader_id, outcome_token, side, price, size_shares, notional_usd, traded_at, external_id, tx_hash, ingested_at, dedup_key FROM polymarket_trades
WHERE market_id = $1
  AND outcome_token = $2
  AND traded_at >= $3
ORDER BY traded_at DESC
LIMIT $4
`

type ListBaselineTradesParams struct {
	MarketID     int64
	OutcomeToken string
	TradedAt     pgtype.Timestamptz
	Limit        int32
}

// Per-(market, outcome) baseline samples within the lookback window.
// Returned newest-first; callers compute median/mean/p95 in domain code
// (deliberately not in SQL so the same statistics live next to the score
// function and can be unit-tested without a database).
func (q *Queries) ListBaselineTrades(ctx context.Context, arg ListBaselineTradesParams) ([]PolymarketTrades, error) {
	rows, err := q.db.Query(ctx, listBaselineTrades,
		arg.MarketID,
		arg.OutcomeToken,
		arg.TradedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketTrades
	for rows.Next() {
		var i PolymarketTrades
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.TraderID,
			&i.OutcomeToken,
			&i.Side,
			&i.Price,
			&i.SizeShares,
			&i.NotionalUsd,
			&i.TradedAt,
			&i.ExternalID,
			&i.TxHash,
			&i.IngestedAt,
			&i.DedupKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusterWindowTrades = `-- name: ListClusterWindowTrades :many
SELECT t.id, t.market_id, t.trader_id, t.outcome_token, t.side, t.price, t.size_shares, t.notional_usd, t.traded_at, t.external_id, t.tx_hash, t.ingested_at, t.dedup_key, m.condition_id AS market_condition_id
FROM polymarket_trades t
JOIN polymarket_markets m ON m.id = t.market_id
WHERE t.market_id = $1
  AND t.traded_at >= $2
ORDER BY t.traded_at DESC
`

type ListClusterWindowTradesParams struct {
	MarketID int64
	TradedAt pgtype.Timestamptz
}

type ListClusterWindowTradesRow struct {
	ID                int64
	MarketID          int64
	TraderID          *int64
	OutcomeToken      string
	Side              string
	Price             float64
	SizeShares        float64
	NotionalUsd       float64
	TradedAt          pgtype.Timestamptz
	ExternalID        *string
	TxHash            *string
	IngestedAt        pgtype.Timestamptz
	DedupKey          string
	MarketConditionID string
}

// All trades in the per-category cluster window. Used by the cluster
// detector to count distinct wallets and total notional.
func (q *Queries) ListClusterWindowTrades(ctx context.Context, arg ListClusterWindowTradesParams) ([]ListClusterWindowTradesRow, error) {
	rows, err := q.db.Query(ctx, listClusterWindowTrades, arg.MarketID, arg.TradedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClusterWindowTradesRow
	for rows.Next() {
		var i ListClusterWindowTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.TraderID,
			&i.OutcomeToken,
			&i.Side,
			&i.Price,
			&i.SizeShares,
			&i.NotionalUsd,
			&i.TradedAt,
			&i.ExternalID,
			&i.TxHash,
			&i.IngestedAt,
			&i.DedupKey,
			&i.MarketConditionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradesForBackfillPage = `-- name: ListTradesForBackfillPage :many
SELECT dedup_key
FROM polymarket_trades
WHERE market_id = $1
  AND dedup_key = ANY($2::text[])
`

type ListTradesForBackfillPageParams struct {
	MarketID  int64
	DedupKeys []string
}

// Used by the BackfillWorker to verify which fetched trade dedup_keys are
// already persisted (defence in depth on top of ON CONFLICT DO NOTHING).
func (q *Queries) ListTradesForBackfillPage(ctx context.Context, arg ListTradesForBackfillPageParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listTradesForBackfillPage, arg.MarketID, arg.DedupKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var dedup_key string
		if err := rows.Scan(&dedup_key); err != nil {
			return nil, err
		}
		items = append(items, dedup_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestTradeAt = `-- name: OldestTradeAt :one
SELECT MIN(traded_at)::timestamptz AS oldest_at
FROM polymarket_trades
WHERE market_id = $1
`

func (q *Queries) OldestTradeAt(ctx context.Context, marketID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, oldestTradeAt, marketID)
	var oldest_at pgtype.Timestamptz
	err := row.Scan(&oldest_at)
	return oldest_at, err
}
