// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: traders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTraderByWallet = `-- name: GetTraderByWallet :one
SELECT id, wallet_address, first_seen_at, last_seen_at FROM polymarket_traders WHERE wallet_address = $1
`

func (q *Queries) GetTraderByWallet(ctx context.Context, walletAddress string) (PolymarketTraders, error) {
	row := q.db.QueryRow(ctx, getTraderByWallet, walletAddress)
	var i PolymarketTraders
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const traderStats = `-- name: TraderStats :one
SELECT
    COUNT(*)::bigint                       AS trade_count,
    COALESCE(SUM(notional_usd),    0)::double precision AS total_notional_usd,
    COALESCE(AVG(notional_usd),    0)::double precision AS mean_notional_usd,
    COALESCE(
        PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY notional_usd),
        0
    )::double precision                    AS median_notional_usd
FROM polymarket_trades
WHERE trader_id = $1
  AND traded_at >= $2
`

type TraderStatsParams struct {
	TraderID *int64
	TradedAt pgtype.Timestamptz
}

type TraderStatsRow struct {
	TradeCount        int64
	TotalNotionalUsd  float64
	MeanNotionalUsd   float64
	MedianNotionalUsd float64
}

// Aggregate stats for one trader since the given timestamp. Used to enrich
// the alert payload ("this wallet's typical bet size over the last 90d").
func (q *Queries) TraderStats(ctx context.Context, arg TraderStatsParams) (TraderStatsRow, error) {
	row := q.db.QueryRow(ctx, traderStats, arg.TraderID, arg.TradedAt)
	var i TraderStatsRow
	err := row.Scan(
		&i.TradeCount,
		&i.TotalNotionalUsd,
		&i.MeanNotionalUsd,
		&i.MedianNotionalUsd,
	)
	return i, err
}

const upsertTrader = `-- name: UpsertTrader :one
INSERT INTO polymarket_traders (wallet_address)
VALUES ($1)
ON CONFLICT (wallet_address) DO UPDATE SET
    last_seen_at = NOW()
RETURNING id, wallet_address, first_seen_at, last_seen_at
`

// Insert a trader by wallet address; on conflict bump last_seen_at.
func (q *Queries) UpsertTrader(ctx context.Context, walletAddress string) (PolymarketTraders, error) {
	row := q.db.QueryRow(ctx, upsertTrader, walletAddress)
	var i PolymarketTraders
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}
