// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTraderByWallet = `-- name: GetTraderByWallet :one
SELECT id, wallet_address, first_seen_at, last_seen_at FROM polymarket_traders WHERE wallet_address = $1
`

func (q *Queries) GetTraderByWallet(ctx context.Context, walletAddress string) (PolymarketTraders, error) {
	row := q.db.QueryRow(ctx, getTraderByWallet, walletAddress)
	var i PolymarketTraders
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const traderMarketSideActivity = `-- name: TraderMarketSideActivity :one
SELECT
    COUNT(*) FILTER (WHERE side = 'BUY')::bigint                                  AS buy_count,
    COUNT(*) FILTER (WHERE side = 'SELL')::bigint                                 AS sell_count,
    COALESCE(SUM(notional_usd) FILTER (WHERE side = 'BUY'), 0)::double precision  AS buy_notional_usd,
    COALESCE(SUM(notional_usd) FILTER (WHERE side = 'SELL'), 0)::double precision AS sell_notional_usd
FROM polymarket_trades
WHERE trader_id     = $1::bigint
  AND market_id     = $2::bigint
  AND outcome_token = $3::text
  AND ($4::timestamptz IS NULL OR traded_at >= $4::timestamptz)
`

type TraderMarketSideActivityParams struct {
	TraderID     int64
	MarketID     int64
	OutcomeToken string
	Since        pgtype.Timestamptz
}

type TraderMarketSideActivityRow struct {
	BuyCount        int64
	SellCount       int64
	BuyNotionalUsd  float64
	SellNotionalUsd float64
}

// Per-(trader, market, outcome) two-sided activity over the supplied
// lookback. Powers the MM/arbitrage suppression filter: a wallet that
// has been hitting BUY and SELL on the same outcome in roughly balanced
// notional is almost certainly a market maker or arbitrageur, not an
// informed-flow candidate, so the detector suppresses single-trade
// alerts on that wallet/market/outcome.
//
// $4 is the inclusive lower bound on traded_at; pass NULL to lift the
// bound (use the trader's full stored history on this bucket).
func (q *Queries) TraderMarketSideActivity(ctx context.Context, arg TraderMarketSideActivityParams) (TraderMarketSideActivityRow, error) {
	row := q.db.QueryRow(ctx, traderMarketSideActivity,
		arg.TraderID,
		arg.MarketID,
		arg.OutcomeToken,
		arg.Since,
	)
	var i TraderMarketSideActivityRow
	err := row.Scan(
		&i.BuyCount,
		&i.SellCount,
		&i.BuyNotionalUsd,
		&i.SellNotionalUsd,
	)
	return i, err
}

const traderStats = `-- name: TraderStats :one
SELECT
    COUNT(*)::bigint                                                                           AS trade_count,
    COALESCE(SUM(notional_usd), 0)::double precision                                           AS total_notional_usd,
    COALESCE(AVG(notional_usd), 0)::double precision                                           AS mean_notional_usd,
    COALESCE(PERCENTILE_CONT(0.5)  WITHIN GROUP (ORDER BY notional_usd), 0)::double precision  AS median_notional_usd,
    COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY notional_usd), 0)::double precision  AS p95_notional_usd,
    COALESCE(PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY notional_usd), 0)::double precision  AS p99_notional_usd,
    MIN(traded_at)::timestamptz                                                                AS oldest_at,
    MAX(traded_at)::timestamptz                                                                AS newest_at
FROM polymarket_trades
WHERE trader_id = $1::bigint
  AND ($2::timestamptz IS NULL OR traded_at >= $2::timestamptz)
`

type TraderStatsParams struct {
	TraderID int64
	Since    pgtype.Timestamptz
}

type TraderStatsRow struct {
	TradeCount        int64
	TotalNotionalUsd  float64
	MeanNotionalUsd   float64
	MedianNotionalUsd float64
	P95NotionalUsd    float64
	P99NotionalUsd    float64
	OldestAt          pgtype.Timestamptz
	NewestAt          pgtype.Timestamptz
}

// Per-wallet distributional summary computed server-side in a single
// roundtrip. Powers the trader-history multiplier in the detector — a
// $50k bet from a wallet whose typical trade is $200 is qualitatively
// different from a $50k bet from a $1M whale, and that distinction is
// what this query exposes. Shape mirrors BaselineDistribution so callers
// can reuse the same readiness gates and Stats type.
//
// $2 is the inclusive lower bound on traded_at; pass NULL to lift the
// bound (use the trader's full stored history).
func (q *Queries) TraderStats(ctx context.Context, arg TraderStatsParams) (TraderStatsRow, error) {
	row := q.db.QueryRow(ctx, traderStats, arg.TraderID, arg.Since)
	var i TraderStatsRow
	err := row.Scan(
		&i.TradeCount,
		&i.TotalNotionalUsd,
		&i.MeanNotionalUsd,
		&i.MedianNotionalUsd,
		&i.P95NotionalUsd,
		&i.P99NotionalUsd,
		&i.OldestAt,
		&i.NewestAt,
	)
	return i, err
}

const upsertTrader = `-- name: UpsertTrader :one
INSERT INTO polymarket_traders (wallet_address)
VALUES ($1)
ON CONFLICT (wallet_address) DO UPDATE SET
    last_seen_at = NOW()
RETURNING id, wallet_address, first_seen_at, last_seen_at
`

// Insert a trader by wallet address; on conflict bump last_seen_at.
func (q *Queries) UpsertTrader(ctx context.Context, walletAddress string) (PolymarketTraders, error) {
	row := q.db.QueryRow(ctx, upsertTrader, walletAddress)
	var i PolymarketTraders
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}
