// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trades.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accumulationLineSummary = `-- name: AccumulationLineSummary :one
SELECT
    COUNT(*)::bigint                                                                          AS trade_count,
    COALESCE(SUM(notional_usd), 0)::double precision                                          AS total_notional_usd,
    COALESCE(AVG(notional_usd), 0)::double precision                                          AS mean_notional_usd,
    COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY notional_usd), 0)::double precision  AS median_notional_usd,
    COALESCE(MAX(notional_usd), 0)::double precision                                          AS max_notional_usd,
    COALESCE(MIN(notional_usd), 0)::double precision                                          AS min_notional_usd,
    COALESCE(AVG(price), 0)::double precision                                                 AS avg_price,
    COALESCE(MIN(price), 0)::double precision                                                 AS min_price,
    MIN(traded_at)::timestamptz                                                               AS oldest_at,
    MAX(traded_at)::timestamptz                                                               AS newest_at
FROM polymarket_trades
WHERE trader_id     = $1::bigint
  AND market_id     = $2::bigint
  AND outcome_token = $3::text
  AND side          = $4::text
  AND ($5::timestamptz IS NULL OR traded_at >= $5::timestamptz)
`

type AccumulationLineSummaryParams struct {
	TraderID     int64
	MarketID     int64
	OutcomeToken string
	Side         string
	Since        pgtype.Timestamptz
}

type AccumulationLineSummaryRow struct {
	TradeCount        int64
	TotalNotionalUsd  float64
	MeanNotionalUsd   float64
	MedianNotionalUsd float64
	MaxNotionalUsd    float64
	MinNotionalUsd    float64
	AvgPrice          float64
	MinPrice          float64
	OldestAt          pgtype.Timestamptz
	NewestAt          pgtype.Timestamptz
}

// Server-side aggregate over one wallet's recent trades on a single
// (market, outcome, side) bucket. Powers the same-trader accumulation
// detector — the entire line scoring runs from this one row, with no
// per-trade transfer. Backed by idx_trades_trader_market_outcome_side_time.
//
// $5 is the inclusive lower bound on traded_at; pass NULL to lift the
// bound (use the wallet's full stored history on this bucket).
//
// avg_price is the mean of `price`. Callers convert to mean odds via
// 1/avg_price when price > 0. max_odds is computed server-side as the
// minimum price's inverse (price closest to 0 ⇒ largest odds).
func (q *Queries) AccumulationLineSummary(ctx context.Context, arg AccumulationLineSummaryParams) (AccumulationLineSummaryRow, error) {
	row := q.db.QueryRow(ctx, accumulationLineSummary,
		arg.TraderID,
		arg.MarketID,
		arg.OutcomeToken,
		arg.Side,
		arg.Since,
	)
	var i AccumulationLineSummaryRow
	err := row.Scan(
		&i.TradeCount,
		&i.TotalNotionalUsd,
		&i.MeanNotionalUsd,
		&i.MedianNotionalUsd,
		&i.MaxNotionalUsd,
		&i.MinNotionalUsd,
		&i.AvgPrice,
		&i.MinPrice,
		&i.OldestAt,
		&i.NewestAt,
	)
	return i, err
}

const baselineDistribution = `-- name: BaselineDistribution :one
SELECT
    COUNT(*)::bigint                                                                           AS sample_count,
    COALESCE(SUM(notional_usd), 0)::double precision                                           AS total_notional_usd,
    COALESCE(AVG(notional_usd), 0)::double precision                                           AS mean_notional_usd,
    COALESCE(PERCENTILE_CONT(0.5)  WITHIN GROUP (ORDER BY notional_usd), 0)::double precision  AS median_notional_usd,
    COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY notional_usd), 0)::double precision  AS p95_notional_usd,
    COALESCE(PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY notional_usd), 0)::double precision  AS p99_notional_usd,
    MIN(traded_at)::timestamptz                                                                AS oldest_at,
    MAX(traded_at)::timestamptz                                                                AS newest_at
FROM polymarket_trades
WHERE market_id     = $1::bigint
  AND outcome_token = $2::text
  AND ($3::timestamptz IS NULL OR traded_at >= $3::timestamptz)
`

type BaselineDistributionParams struct {
	MarketID     int64
	OutcomeToken string
	Since        pgtype.Timestamptz
}

type BaselineDistributionRow struct {
	SampleCount       int64
	TotalNotionalUsd  float64
	MeanNotionalUsd   float64
	MedianNotionalUsd float64
	P95NotionalUsd    float64
	P99NotionalUsd    float64
	OldestAt          pgtype.Timestamptz
	NewestAt          pgtype.Timestamptz
}

// Single-roundtrip statistical summary for the per-bucket reservoir.
// Powers the DB-backed detector's hot path: count + total + mean + median
// + p95 + observed time-span, server-side. PERCENTILE_CONT does the heavy
// lifting so Go code never sorts more than this one row.
//
// $3 is the inclusive lower bound; pass NULL (pgtype.Timestamptz{Valid:false})
// to lift the bound (use all stored history for the bucket).
func (q *Queries) BaselineDistribution(ctx context.Context, arg BaselineDistributionParams) (BaselineDistributionRow, error) {
	row := q.db.QueryRow(ctx, baselineDistribution, arg.MarketID, arg.OutcomeToken, arg.Since)
	var i BaselineDistributionRow
	err := row.Scan(
		&i.SampleCount,
		&i.TotalNotionalUsd,
		&i.MeanNotionalUsd,
		&i.MedianNotionalUsd,
		&i.P95NotionalUsd,
		&i.P99NotionalUsd,
		&i.OldestAt,
		&i.NewestAt,
	)
	return i, err
}

const baselineSpan = `-- name: BaselineSpan :one
SELECT
    COUNT(*)::bigint                                 AS sample_count,
    COALESCE(SUM(notional_usd), 0)::double precision AS total_notional_usd,
    MIN(traded_at)::timestamptz                      AS oldest_at,
    MAX(traded_at)::timestamptz                      AS newest_at
FROM polymarket_trades
WHERE market_id = $1
  AND outcome_token = $2
  AND traded_at >= $3
`

type BaselineSpanParams struct {
	MarketID     int64
	OutcomeToken string
	TradedAt     pgtype.Timestamptz
}

type BaselineSpanRow struct {
	SampleCount      int64
	TotalNotionalUsd float64
	OldestAt         pgtype.Timestamptz
	NewestAt         pgtype.Timestamptz
}

// Compact summary of the per-bucket reservoir without pulling all rows.
// Used by the readiness gate to skip listing when the baseline is plainly
// too thin to bother with.
func (q *Queries) BaselineSpan(ctx context.Context, arg BaselineSpanParams) (BaselineSpanRow, error) {
	row := q.db.QueryRow(ctx, baselineSpan, arg.MarketID, arg.OutcomeToken, arg.TradedAt)
	var i BaselineSpanRow
	err := row.Scan(
		&i.SampleCount,
		&i.TotalNotionalUsd,
		&i.OldestAt,
		&i.NewestAt,
	)
	return i, err
}

const claimUndetectedTrades = `-- name: ClaimUndetectedTrades :many
UPDATE polymarket_trades t
SET detection_claimed_at = NOW(),
    detection_worker_id  = $1::text
FROM (
    SELECT id
    FROM polymarket_trades
    WHERE detected_at IS NULL
      AND (detection_claimed_at IS NULL OR detection_claimed_at < NOW() - $2::interval)
    ORDER BY traded_at DESC, id DESC
    LIMIT $3::integer
    FOR UPDATE SKIP LOCKED
) AS picked
JOIN polymarket_markets m ON TRUE
WHERE t.id = picked.id AND m.id = t.market_id
RETURNING t.id, t.market_id, t.trader_id, t.outcome_token, t.side, t.price,
          t.size_shares, t.notional_usd, t.traded_at, t.external_id,
          t.tx_hash, t.ingested_at, t.dedup_key,
          t.detection_attempts,
          m.condition_id AS market_condition_id
`

type ClaimUndetectedTradesParams struct {
	WorkerID   string
	ClaimTtl   pgtype.Interval
	ClaimLimit int32
}

type ClaimUndetectedTradesRow struct {
	ID                int64
	MarketID          int64
	TraderID          *int64
	OutcomeToken      string
	Side              string
	Price             float64
	SizeShares        float64
	NotionalUsd       float64
	TradedAt          pgtype.Timestamptz
	ExternalID        *string
	TxHash            *string
	IngestedAt        pgtype.Timestamptz
	DedupKey          string
	DetectionAttempts int32
	MarketConditionID string
}

// Atomically lease a batch of trades that need detection processing.
// The UPDATE flips detection_claimed_at to NOW() and stamps the
// worker id; the inner SELECT … FOR UPDATE SKIP LOCKED ensures
// concurrent workers see disjoint batches. A leased row stays in
// 'pending' (detected_at IS NULL) until the worker calls
// MarkTradeDetectionResult; if the worker crashes, ResetStaleDetectionClaims
// reclaims rows whose lease is older than the configured TTL.
func (q *Queries) ClaimUndetectedTrades(ctx context.Context, arg ClaimUndetectedTradesParams) ([]ClaimUndetectedTradesRow, error) {
	rows, err := q.db.Query(ctx, claimUndetectedTrades, arg.WorkerID, arg.ClaimTtl, arg.ClaimLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimUndetectedTradesRow
	for rows.Next() {
		var i ClaimUndetectedTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.TraderID,
			&i.OutcomeToken,
			&i.Side,
			&i.Price,
			&i.SizeShares,
			&i.NotionalUsd,
			&i.TradedAt,
			&i.ExternalID,
			&i.TxHash,
			&i.IngestedAt,
			&i.DedupKey,
			&i.DetectionAttempts,
			&i.MarketConditionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const detectionStatusBreakdown = `-- name: DetectionStatusBreakdown :many
SELECT COALESCE(detection_status, 'pending')::text AS status,
       COUNT(*)::bigint                            AS count
FROM polymarket_trades
GROUP BY 1
ORDER BY 1
`

type DetectionStatusBreakdownRow struct {
	Status string
	Count  int64
}

// /stats break-down: rows by terminal detection state. NULL status is
// reported as 'pending'.
func (q *Queries) DetectionStatusBreakdown(ctx context.Context) ([]DetectionStatusBreakdownRow, error) {
	rows, err := q.db.Query(ctx, detectionStatusBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DetectionStatusBreakdownRow
	for rows.Next() {
		var i DetectionStatusBreakdownRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTrade = `-- name: InsertTrade :one
INSERT INTO polymarket_trades (
    market_id, trader_id, outcome_token, side,
    price, size_shares, notional_usd,
    traded_at, external_id, tx_hash, dedup_key
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11
)
ON CONFLICT (dedup_key) DO NOTHING
RETURNING id, market_id, trader_id, outcome_token, side, price, size_shares, notional_usd, traded_at, external_id, tx_hash, ingested_at, dedup_key, detected_at, detection_status, detection_skip_reason, detection_attempts, last_detection_error, detection_claimed_at, detection_worker_id
`

type InsertTradeParams struct {
	MarketID     int64
	TraderID     *int64
	OutcomeToken string
	Side         string
	Price        float64
	SizeShares   float64
	NotionalUsd  float64
	TradedAt     pgtype.Timestamptz
	ExternalID   *string
	TxHash       *string
	DedupKey     string
}

// Insert a single trade. ON CONFLICT (dedup_key) DO NOTHING is the dedup
// primitive — concurrent inserters of the same trade race to the unique
// constraint and exactly one wins. The caller maps pgx.ErrNoRows to
// "already existed".
func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) (PolymarketTrades, error) {
	row := q.db.QueryRow(ctx, insertTrade,
		arg.MarketID,
		arg.TraderID,
		arg.OutcomeToken,
		arg.Side,
		arg.Price,
		arg.SizeShares,
		arg.NotionalUsd,
		arg.TradedAt,
		arg.ExternalID,
		arg.TxHash,
		arg.DedupKey,
	)
	var i PolymarketTrades
	err := row.Scan(
		&i.ID,
		&i.MarketID,
		&i.TraderID,
		&i.OutcomeToken,
		&i.Side,
		&i.Price,
		&i.SizeShares,
		&i.NotionalUsd,
		&i.TradedAt,
		&i.ExternalID,
		&i.TxHash,
		&i.IngestedAt,
		&i.DedupKey,
		&i.DetectedAt,
		&i.DetectionStatus,
		&i.DetectionSkipReason,
		&i.DetectionAttempts,
		&i.LastDetectionError,
		&i.DetectionClaimedAt,
		&i.DetectionWorkerID,
	)
	return i, err
}

const lastTradeAtBefore = `-- name: LastTradeAtBefore :one
SELECT MAX(traded_at)::timestamptz AS last_at
FROM polymarket_trades
WHERE market_id     = $1::bigint
  AND outcome_token = $2::text
  AND traded_at     < $3::timestamptz
`

type LastTradeAtBeforeParams struct {
	MarketID     int64
	OutcomeToken string
	Before       pgtype.Timestamptz
}

// Returns the most recent traded_at for a (market, outcome) STRICTLY before
// the supplied timestamp. NULL when no prior trade exists. Powers the
// quiet-market wake-up detector — given the current trade's timestamp it
// yields the gap to the previous historical trade so the detector can
// judge "idle for how long?" without re-listing rows.
func (q *Queries) LastTradeAtBefore(ctx context.Context, arg LastTradeAtBeforeParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, lastTradeAtBefore, arg.MarketID, arg.OutcomeToken, arg.Before)
	var last_at pgtype.Timestamptz
	err := row.Scan(&last_at)
	return last_at, err
}

const latestPriceForOutcome = `-- name: LatestPriceForOutcome :one
SELECT price FROM polymarket_trades
WHERE market_id     = $1::bigint
  AND outcome_token = $2::text
ORDER BY traded_at DESC
LIMIT 1
`

type LatestPriceForOutcomeParams struct {
	MarketID     int64
	OutcomeToken string
}

// Most recent observed price for (market, outcome). Used by the
// stable-favorite worker as "current price" since there is no CLOB
// bid/ask wired upstream — the most recent trade is the best proxy
// we have for the implied probability.
func (q *Queries) LatestPriceForOutcome(ctx context.Context, arg LatestPriceForOutcomeParams) (float64, error) {
	row := q.db.QueryRow(ctx, latestPriceForOutcome, arg.MarketID, arg.OutcomeToken)
	var price float64
	err := row.Scan(&price)
	return price, err
}

const latestTradeAt = `-- name: LatestTradeAt :one
SELECT MAX(traded_at)::timestamptz AS latest_at
FROM polymarket_trades
WHERE market_id = $1
`

// Used by the collector to advance the per-market sync cursor without
// keeping an in-process map. Returns NULL when no trades yet exist.
func (q *Queries) LatestTradeAt(ctx context.Context, marketID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, latestTradeAt, marketID)
	var latest_at pgtype.Timestamptz
	err := row.Scan(&latest_at)
	return latest_at, err
}

const listBaselineTrades = `-- name: ListBaselineTrades :many
SELECT id, market_id, trader_id, outcome_token, side, price, size_shares, notional_usd, traded_at, external_id, tx_hash, ingested_at, dedup_key, detected_at, detection_status, detection_skip_reason, detection_attempts, last_detection_error, detection_claimed_at, detection_worker_id FROM polymarket_trades
WHERE market_id = $1
  AND outcome_token = $2
  AND traded_at >= $3
ORDER BY traded_at DESC
LIMIT $4
`

type ListBaselineTradesParams struct {
	MarketID     int64
	OutcomeToken string
	TradedAt     pgtype.Timestamptz
	Limit        int32
}

// Per-(market, outcome) baseline samples within the lookback window.
// Returned newest-first; callers compute median/mean/p95 in domain code
// (deliberately not in SQL so the same statistics live next to the score
// function and can be unit-tested without a database).
func (q *Queries) ListBaselineTrades(ctx context.Context, arg ListBaselineTradesParams) ([]PolymarketTrades, error) {
	rows, err := q.db.Query(ctx, listBaselineTrades,
		arg.MarketID,
		arg.OutcomeToken,
		arg.TradedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketTrades
	for rows.Next() {
		var i PolymarketTrades
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.TraderID,
			&i.OutcomeToken,
			&i.Side,
			&i.Price,
			&i.SizeShares,
			&i.NotionalUsd,
			&i.TradedAt,
			&i.ExternalID,
			&i.TxHash,
			&i.IngestedAt,
			&i.DedupKey,
			&i.DetectedAt,
			&i.DetectionStatus,
			&i.DetectionSkipReason,
			&i.DetectionAttempts,
			&i.LastDetectionError,
			&i.DetectionClaimedAt,
			&i.DetectionWorkerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusterWindowTrades = `-- name: ListClusterWindowTrades :many
SELECT t.id, t.market_id, t.trader_id, t.outcome_token, t.side, t.price, t.size_shares, t.notional_usd, t.traded_at, t.external_id, t.tx_hash, t.ingested_at, t.dedup_key, t.detected_at, t.detection_status, t.detection_skip_reason, t.detection_attempts, t.last_detection_error, t.detection_claimed_at, t.detection_worker_id, m.condition_id AS market_condition_id
FROM polymarket_trades t
JOIN polymarket_markets m ON m.id = t.market_id
WHERE t.market_id = $1
  AND t.traded_at >= $2
ORDER BY t.traded_at DESC
`

type ListClusterWindowTradesParams struct {
	MarketID int64
	TradedAt pgtype.Timestamptz
}

type ListClusterWindowTradesRow struct {
	ID                  int64
	MarketID            int64
	TraderID            *int64
	OutcomeToken        string
	Side                string
	Price               float64
	SizeShares          float64
	NotionalUsd         float64
	TradedAt            pgtype.Timestamptz
	ExternalID          *string
	TxHash              *string
	IngestedAt          pgtype.Timestamptz
	DedupKey            string
	DetectedAt          pgtype.Timestamptz
	DetectionStatus     *string
	DetectionSkipReason *string
	DetectionAttempts   int32
	LastDetectionError  *string
	DetectionClaimedAt  pgtype.Timestamptz
	DetectionWorkerID   *string
	MarketConditionID   string
}

// All trades in the per-category cluster window. Used by the cluster
// detector to count distinct wallets and total notional.
func (q *Queries) ListClusterWindowTrades(ctx context.Context, arg ListClusterWindowTradesParams) ([]ListClusterWindowTradesRow, error) {
	rows, err := q.db.Query(ctx, listClusterWindowTrades, arg.MarketID, arg.TradedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClusterWindowTradesRow
	for rows.Next() {
		var i ListClusterWindowTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.TraderID,
			&i.OutcomeToken,
			&i.Side,
			&i.Price,
			&i.SizeShares,
			&i.NotionalUsd,
			&i.TradedAt,
			&i.ExternalID,
			&i.TxHash,
			&i.IngestedAt,
			&i.DedupKey,
			&i.DetectedAt,
			&i.DetectionStatus,
			&i.DetectionSkipReason,
			&i.DetectionAttempts,
			&i.LastDetectionError,
			&i.DetectionClaimedAt,
			&i.DetectionWorkerID,
			&i.MarketConditionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLateMarketCandidates = `-- name: ListLateMarketCandidates :many
SELECT m.id, m.condition_id, m.slug, m.question, m.event_slug, m.start_date, m.end_date,
       (100.0 * EXTRACT(EPOCH FROM (NOW() - m.start_date)) /
              NULLIF(EXTRACT(EPOCH FROM (m.end_date - m.start_date)), 0))::double precision AS lifecycle_pct
FROM polymarket_markets m
WHERE m.active = TRUE
  AND m.deleted_at IS NULL
  AND m.purged_at  IS NULL
  AND m.start_date IS NOT NULL
  AND m.end_date   IS NOT NULL
  AND m.end_date    > NOW()
  AND (100.0 * EXTRACT(EPOCH FROM (NOW() - m.start_date)) /
             NULLIF(EXTRACT(EPOCH FROM (m.end_date - m.start_date)), 0))::double precision >= $1::double precision
ORDER BY lifecycle_pct DESC
LIMIT $2::integer
`

type ListLateMarketCandidatesParams struct {
	MinLifecyclePct float64
	LimitCount      int32
}

type ListLateMarketCandidatesRow struct {
	ID           int64
	ConditionID  string
	Slug         string
	Question     string
	EventSlug    *string
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	LifecyclePct float64
}

// Active markets whose lifecycle progress has crossed the supplied
// threshold AND haven't been soft-deleted/purged. Returns enough
// context for the stable-favorite worker to build inputs without a
// second roundtrip per row.
//
// The lifecycle math mirrors the in-memory market.LifecyclePct used
// by the per-trade scorer so the two strategies agree on what
// "late-market" means.
func (q *Queries) ListLateMarketCandidates(ctx context.Context, arg ListLateMarketCandidatesParams) ([]ListLateMarketCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listLateMarketCandidates, arg.MinLifecyclePct, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLateMarketCandidatesRow
	for rows.Next() {
		var i ListLateMarketCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConditionID,
			&i.Slug,
			&i.Question,
			&i.EventSlug,
			&i.StartDate,
			&i.EndDate,
			&i.LifecyclePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradesForBackfillPage = `-- name: ListTradesForBackfillPage :many
SELECT dedup_key
FROM polymarket_trades
WHERE market_id = $1
  AND dedup_key = ANY($2::text[])
`

type ListTradesForBackfillPageParams struct {
	MarketID  int64
	DedupKeys []string
}

// Used by the BackfillWorker to verify which fetched trade dedup_keys are
// already persisted (defence in depth on top of ON CONFLICT DO NOTHING).
func (q *Queries) ListTradesForBackfillPage(ctx context.Context, arg ListTradesForBackfillPageParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listTradesForBackfillPage, arg.MarketID, arg.DedupKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var dedup_key string
		if err := rows.Scan(&dedup_key); err != nil {
			return nil, err
		}
		items = append(items, dedup_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTradeDetectionResult = `-- name: MarkTradeDetectionResult :exec
UPDATE polymarket_trades
SET detected_at           = NOW(),
    detection_status      = $1::text,
    detection_skip_reason = $2::text,
    last_detection_error  = $3::text,
    detection_attempts    = detection_attempts + 1,
    detection_claimed_at  = NULL,
    detection_worker_id   = NULL
WHERE id = $4::bigint
`

type MarkTradeDetectionResultParams struct {
	Status       string
	SkipReason   *string
	ErrorMessage *string
	TradeID      int64
}

// Stamp the terminal state for one trade. detected_at = NOW() always.
// detection_status is one of 'analyzed' | 'skipped' | 'failed' (the
// CHECK constraint enforces this). detection_skip_reason is set only
// when status='skipped'; last_detection_error only when status='failed'.
// The lease columns are cleared atomically so a row can never enter a
// "completed but still leased" state.
func (q *Queries) MarkTradeDetectionResult(ctx context.Context, arg MarkTradeDetectionResultParams) error {
	_, err := q.db.Exec(ctx, markTradeDetectionResult,
		arg.Status,
		arg.SkipReason,
		arg.ErrorMessage,
		arg.TradeID,
	)
	return err
}

const oldestTradeAt = `-- name: OldestTradeAt :one
SELECT MIN(traded_at)::timestamptz AS oldest_at
FROM polymarket_trades
WHERE market_id = $1
`

func (q *Queries) OldestTradeAt(ctx context.Context, marketID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, oldestTradeAt, marketID)
	var oldest_at pgtype.Timestamptz
	err := row.Scan(&oldest_at)
	return oldest_at, err
}

const ownershipShares = `-- name: OwnershipShares :one
SELECT
    COALESCE(SUM(size_shares) FILTER (WHERE side = 'BUY'  AND trader_id = $1::bigint), 0)::double precision AS wallet_buy_shares,
    COALESCE(SUM(size_shares) FILTER (WHERE side = 'SELL' AND trader_id = $1::bigint), 0)::double precision AS wallet_sell_shares,
    COALESCE(SUM(size_shares) FILTER (WHERE side = 'BUY'),                                              0)::double precision AS market_buy_shares
FROM polymarket_trades
WHERE market_id     = $2::bigint
  AND outcome_token = $3::text
`

type OwnershipSharesParams struct {
	TraderID     int64
	MarketID     int64
	OutcomeToken string
}

type OwnershipSharesRow struct {
	WalletBuyShares  float64
	WalletSellShares float64
	MarketBuyShares  float64
}

// Server-side aggregate of (wallet, market, outcome) share-count flow
// vs the outcome's total BUY-side flow. Powers the trade-flow
// approximation of market-ownership concentration.
//
// IMPORTANT: this is an APPROXIMATION, not a holders read. The CLOB
// API holders endpoint is not wired upstream. `wallet_buy_shares` and
// `wallet_sell_shares` are summed only over trades the watchtower
// ingested; a wallet that transferred shares off-chain or sold to a
// counterparty whose trade we didn't observe is invisible to this
// query. Treat the percentage as directional, not authoritative.
func (q *Queries) OwnershipShares(ctx context.Context, arg OwnershipSharesParams) (OwnershipSharesRow, error) {
	row := q.db.QueryRow(ctx, ownershipShares, arg.TraderID, arg.MarketID, arg.OutcomeToken)
	var i OwnershipSharesRow
	err := row.Scan(&i.WalletBuyShares, &i.WalletSellShares, &i.MarketBuyShares)
	return i, err
}

const pendingDetectionCount = `-- name: PendingDetectionCount :one
SELECT COUNT(*)::bigint AS pending FROM polymarket_trades WHERE detected_at IS NULL
`

// Diagnostic: how many trades are still pending detection. Used by
// /stats and Grafana so operators can see whether the worker is
// keeping up.
func (q *Queries) PendingDetectionCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, pendingDetectionCount)
	var pending int64
	err := row.Scan(&pending)
	return pending, err
}

const priceWindowStats = `-- name: PriceWindowStats :one
SELECT
    COUNT(*)::bigint                                            AS sample_count,
    COALESCE(AVG(price), 0)::double precision                   AS mean_price,
    COALESCE(STDDEV_POP(price), 0)::double precision            AS stddev_price,
    COALESCE(MIN(price), 0)::double precision                   AS min_price,
    COALESCE(MAX(price), 0)::double precision                   AS max_price,
    COALESCE((array_agg(price ORDER BY traded_at ASC))[1],  0)::double precision AS first_price,
    COALESCE((array_agg(price ORDER BY traded_at DESC))[1], 0)::double precision AS last_price,
    COALESCE(SUM(notional_usd), 0)::double precision            AS volume_usd,
    COALESCE(SUM(notional_usd) FILTER (WHERE side = 'BUY'),  0)::double precision AS buy_volume_usd,
    COALESCE(SUM(notional_usd) FILTER (WHERE side = 'SELL'), 0)::double precision AS sell_volume_usd
FROM polymarket_trades
WHERE market_id     = $1::bigint
  AND outcome_token = $2::text
  AND traded_at    >= $3::timestamptz
`

type PriceWindowStatsParams struct {
	MarketID     int64
	OutcomeToken string
	Since        pgtype.Timestamptz
}

type PriceWindowStatsRow struct {
	SampleCount   int64
	MeanPrice     float64
	StddevPrice   float64
	MinPrice      float64
	MaxPrice      float64
	FirstPrice    float64
	LastPrice     float64
	VolumeUsd     float64
	BuyVolumeUsd  float64
	SellVolumeUsd float64
}

// Per-(market, outcome) price/volume stats over a lookback window.
// Powers the late-market stable-favorite worker — stability,
// adverse-drift, and liquidity gates all read from this one row.
//
// first/last via array_agg(ORDER BY) so a single scan yields both.
// STDDEV_POP (not _SAMP) because we treat the window as the
// population for stability purposes; the worker enforces a minimum
// sample count upstream.
func (q *Queries) PriceWindowStats(ctx context.Context, arg PriceWindowStatsParams) (PriceWindowStatsRow, error) {
	row := q.db.QueryRow(ctx, priceWindowStats, arg.MarketID, arg.OutcomeToken, arg.Since)
	var i PriceWindowStatsRow
	err := row.Scan(
		&i.SampleCount,
		&i.MeanPrice,
		&i.StddevPrice,
		&i.MinPrice,
		&i.MaxPrice,
		&i.FirstPrice,
		&i.LastPrice,
		&i.VolumeUsd,
		&i.BuyVolumeUsd,
		&i.SellVolumeUsd,
	)
	return i, err
}

const resetStaleDetectionClaims = `-- name: ResetStaleDetectionClaims :execrows
UPDATE polymarket_trades
SET detection_claimed_at = NULL,
    detection_worker_id  = NULL
WHERE detected_at IS NULL
  AND detection_claimed_at IS NOT NULL
  AND detection_claimed_at < NOW() - $1::interval
`

// Free leases held longer than the supplied interval, so the next
// claim picks the row back up. Returns the number of rows reset (the
// worker logs this so an operator can spot crash loops).
func (q *Queries) ResetStaleDetectionClaims(ctx context.Context, staleAfter pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, resetStaleDetectionClaims, staleAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const traderFirstSeenAt = `-- name: TraderFirstSeenAt :one
SELECT MIN(t.traded_at)::timestamptz AS first_seen_at
FROM polymarket_trades t
WHERE t.trader_id = $1::bigint
`

// Earliest persisted trade timestamp for a wallet's full history.
// Used by the new-wallet / dormant-wallet context boosters; the
// detection worker calls this when stamping context on a Finding.
func (q *Queries) TraderFirstSeenAt(ctx context.Context, traderID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, traderFirstSeenAt, traderID)
	var first_seen_at pgtype.Timestamptz
	err := row.Scan(&first_seen_at)
	return first_seen_at, err
}

const traderLastSeenBefore = `-- name: TraderLastSeenBefore :one
SELECT MAX(t.traded_at)::timestamptz AS last_at
FROM polymarket_trades t
WHERE t.trader_id = $1::bigint
  AND t.traded_at < $2::timestamptz
`

type TraderLastSeenBeforeParams struct {
	TraderID int64
	Before   pgtype.Timestamptz
}

// Most-recent trade timestamp STRICTLY before the supplied cutoff.
// Used by the dormant-wallet booster to ask "how long has this wallet
// been idle just before this trade?".
func (q *Queries) TraderLastSeenBefore(ctx context.Context, arg TraderLastSeenBeforeParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, traderLastSeenBefore, arg.TraderID, arg.Before)
	var last_at pgtype.Timestamptz
	err := row.Scan(&last_at)
	return last_at, err
}
