// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: trades.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const baselineSpan = `-- name: BaselineSpan :one
SELECT
    COUNT(*)::bigint                                 AS sample_count,
    COALESCE(SUM(notional_usd), 0)::double precision AS total_notional_usd,
    MIN(traded_at)::timestamptz                      AS oldest_at,
    MAX(traded_at)::timestamptz                      AS newest_at
FROM polymarket_trades
WHERE market_id = $1
  AND outcome_token = $2
  AND traded_at >= $3
`

type BaselineSpanParams struct {
	MarketID     int64
	OutcomeToken string
	TradedAt     pgtype.Timestamptz
}

type BaselineSpanRow struct {
	SampleCount      int64
	TotalNotionalUsd float64
	OldestAt         pgtype.Timestamptz
	NewestAt         pgtype.Timestamptz
}

// Compact summary of the per-bucket reservoir without pulling all rows.
// Used by the readiness gate to skip listing when the baseline is plainly
// too thin to bother with.
func (q *Queries) BaselineSpan(ctx context.Context, arg BaselineSpanParams) (BaselineSpanRow, error) {
	row := q.db.QueryRow(ctx, baselineSpan, arg.MarketID, arg.OutcomeToken, arg.TradedAt)
	var i BaselineSpanRow
	err := row.Scan(
		&i.SampleCount,
		&i.TotalNotionalUsd,
		&i.OldestAt,
		&i.NewestAt,
	)
	return i, err
}

const insertTrade = `-- name: InsertTrade :one
INSERT INTO polymarket_trades (
    market_id, trader_id, outcome_token, side,
    price, size_shares, notional_usd,
    traded_at, external_id, tx_hash, dedup_key
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11
)
ON CONFLICT (dedup_key) DO NOTHING
RETURNING id, market_id, trader_id, outcome_token, side, price, size_shares, notional_usd, traded_at, external_id, tx_hash, ingested_at, dedup_key
`

type InsertTradeParams struct {
	MarketID     int64
	TraderID     *int64
	OutcomeToken string
	Side         string
	Price        float64
	SizeShares   float64
	NotionalUsd  float64
	TradedAt     pgtype.Timestamptz
	ExternalID   *string
	TxHash       *string
	DedupKey     string
}

// Insert a single trade. ON CONFLICT (dedup_key) DO NOTHING is the dedup
// primitive — concurrent inserters of the same trade race to the unique
// constraint and exactly one wins. The caller maps pgx.ErrNoRows to
// "already existed".
func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) (PolymarketTrades, error) {
	row := q.db.QueryRow(ctx, insertTrade,
		arg.MarketID,
		arg.TraderID,
		arg.OutcomeToken,
		arg.Side,
		arg.Price,
		arg.SizeShares,
		arg.NotionalUsd,
		arg.TradedAt,
		arg.ExternalID,
		arg.TxHash,
		arg.DedupKey,
	)
	var i PolymarketTrades
	err := row.Scan(
		&i.ID,
		&i.MarketID,
		&i.TraderID,
		&i.OutcomeToken,
		&i.Side,
		&i.Price,
		&i.SizeShares,
		&i.NotionalUsd,
		&i.TradedAt,
		&i.ExternalID,
		&i.TxHash,
		&i.IngestedAt,
		&i.DedupKey,
	)
	return i, err
}

const latestTradeAt = `-- name: LatestTradeAt :one
SELECT MAX(traded_at)::timestamptz AS latest_at
FROM polymarket_trades
WHERE market_id = $1
`

// Used by the collector to advance the per-market sync cursor without
// keeping an in-process map. Returns NULL when no trades yet exist.
func (q *Queries) LatestTradeAt(ctx context.Context, marketID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, latestTradeAt, marketID)
	var latest_at pgtype.Timestamptz
	err := row.Scan(&latest_at)
	return latest_at, err
}

const listBaselineTrades = `-- name: ListBaselineTrades :many
SELECT id, market_id, trader_id, outcome_token, side, price, size_shares, notional_usd, traded_at, external_id, tx_hash, ingested_at, dedup_key FROM polymarket_trades
WHERE market_id = $1
  AND outcome_token = $2
  AND traded_at >= $3
ORDER BY traded_at DESC
LIMIT $4
`

type ListBaselineTradesParams struct {
	MarketID     int64
	OutcomeToken string
	TradedAt     pgtype.Timestamptz
	Limit        int32
}

// Per-(market, outcome) baseline samples within the lookback window.
// Returned newest-first; callers compute median/mean/p95 in domain code
// (deliberately not in SQL so the same statistics live next to the score
// function and can be unit-tested without a database).
func (q *Queries) ListBaselineTrades(ctx context.Context, arg ListBaselineTradesParams) ([]PolymarketTrades, error) {
	rows, err := q.db.Query(ctx, listBaselineTrades,
		arg.MarketID,
		arg.OutcomeToken,
		arg.TradedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketTrades
	for rows.Next() {
		var i PolymarketTrades
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.TraderID,
			&i.OutcomeToken,
			&i.Side,
			&i.Price,
			&i.SizeShares,
			&i.NotionalUsd,
			&i.TradedAt,
			&i.ExternalID,
			&i.TxHash,
			&i.IngestedAt,
			&i.DedupKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusterWindowTrades = `-- name: ListClusterWindowTrades :many
SELECT t.id, t.market_id, t.trader_id, t.outcome_token, t.side, t.price, t.size_shares, t.notional_usd, t.traded_at, t.external_id, t.tx_hash, t.ingested_at, t.dedup_key, m.condition_id AS market_condition_id
FROM polymarket_trades t
JOIN polymarket_markets m ON m.id = t.market_id
WHERE t.market_id = $1
  AND t.traded_at >= $2
ORDER BY t.traded_at DESC
`

type ListClusterWindowTradesParams struct {
	MarketID int64
	TradedAt pgtype.Timestamptz
}

type ListClusterWindowTradesRow struct {
	ID                int64
	MarketID          int64
	TraderID          *int64
	OutcomeToken      string
	Side              string
	Price             float64
	SizeShares        float64
	NotionalUsd       float64
	TradedAt          pgtype.Timestamptz
	ExternalID        *string
	TxHash            *string
	IngestedAt        pgtype.Timestamptz
	DedupKey          string
	MarketConditionID string
}

// All trades in the per-category cluster window. Used by the cluster
// detector to count distinct wallets and total notional.
func (q *Queries) ListClusterWindowTrades(ctx context.Context, arg ListClusterWindowTradesParams) ([]ListClusterWindowTradesRow, error) {
	rows, err := q.db.Query(ctx, listClusterWindowTrades, arg.MarketID, arg.TradedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClusterWindowTradesRow
	for rows.Next() {
		var i ListClusterWindowTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.TraderID,
			&i.OutcomeToken,
			&i.Side,
			&i.Price,
			&i.SizeShares,
			&i.NotionalUsd,
			&i.TradedAt,
			&i.ExternalID,
			&i.TxHash,
			&i.IngestedAt,
			&i.DedupKey,
			&i.MarketConditionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestTradeAt = `-- name: OldestTradeAt :one
SELECT MIN(traded_at)::timestamptz AS oldest_at
FROM polymarket_trades
WHERE market_id = $1
`

func (q *Queries) OldestTradeAt(ctx context.Context, marketID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, oldestTradeAt, marketID)
	var oldest_at pgtype.Timestamptz
	err := row.Scan(&oldest_at)
	return oldest_at, err
}
