// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: v109_unified_intel.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishUnifiedIntelRun = `-- name: FinishUnifiedIntelRun :exec
UPDATE polymarket_unified_intel_runs
SET finished_at   = NOW(),
    status        = $1,
    ai_called     = $2,
    ai_status     = $3,
    sentinel_code = $4,
    ai_cost_usd   = $5,
    telegram_sent = $6,
    selected_count = $7
WHERE id = $8
`

type FinishUnifiedIntelRunParams struct {
	Status        string
	AiCalled      bool
	AiStatus      string
	SentinelCode  string
	AiCostUsd     float64
	TelegramSent  bool
	SelectedCount int32
	ID            int64
}

func (q *Queries) FinishUnifiedIntelRun(ctx context.Context, arg FinishUnifiedIntelRunParams) error {
	_, err := q.db.Exec(ctx, finishUnifiedIntelRun,
		arg.Status,
		arg.AiCalled,
		arg.AiStatus,
		arg.SentinelCode,
		arg.AiCostUsd,
		arg.TelegramSent,
		arg.SelectedCount,
		arg.ID,
	)
	return err
}

const getMarketAICache = `-- name: GetMarketAICache :one


SELECT id, event_slug, condition_id, ai_surface, market_ai_key,
       news_fingerprint, catalyst_fingerprint, repricing_bucket,
       flow_bucket, price_bucket,
       ai_status, sentinel_code, decision_json, summary_text,
       last_ai_at, last_reused_at, reuse_count, created_at, updated_at
FROM polymarket_market_ai_cache
WHERE ai_surface = $1 AND market_ai_key = $2
`

type GetMarketAICacheParams struct {
	AiSurface   string
	MarketAiKey string
}

// v10.9 unified intel queries.
// =========================================================================
// Market AI cache (PART 3)
// =========================================================================
func (q *Queries) GetMarketAICache(ctx context.Context, arg GetMarketAICacheParams) (PolymarketMarketAiCache, error) {
	row := q.db.QueryRow(ctx, getMarketAICache, arg.AiSurface, arg.MarketAiKey)
	var i PolymarketMarketAiCache
	err := row.Scan(
		&i.ID,
		&i.EventSlug,
		&i.ConditionID,
		&i.AiSurface,
		&i.MarketAiKey,
		&i.NewsFingerprint,
		&i.CatalystFingerprint,
		&i.RepricingBucket,
		&i.FlowBucket,
		&i.PriceBucket,
		&i.AiStatus,
		&i.SentinelCode,
		&i.DecisionJson,
		&i.SummaryText,
		&i.LastAiAt,
		&i.LastReusedAt,
		&i.ReuseCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTelegramSemanticDedupe = `-- name: GetTelegramSemanticDedupe :one

SELECT id, surface, dedupe_key, semantic_fingerprint, event_slug,
       condition_id, wallet, last_sent_at, send_count,
       last_notional, last_severity, last_reason, created_at, updated_at
FROM polymarket_telegram_semantic_dedupe
WHERE surface = $1 AND dedupe_key = $2
`

type GetTelegramSemanticDedupeParams struct {
	Surface   string
	DedupeKey string
}

// =========================================================================
// Telegram semantic dedupe (PART 4)
// =========================================================================
func (q *Queries) GetTelegramSemanticDedupe(ctx context.Context, arg GetTelegramSemanticDedupeParams) (PolymarketTelegramSemanticDedupe, error) {
	row := q.db.QueryRow(ctx, getTelegramSemanticDedupe, arg.Surface, arg.DedupeKey)
	var i PolymarketTelegramSemanticDedupe
	err := row.Scan(
		&i.ID,
		&i.Surface,
		&i.DedupeKey,
		&i.SemanticFingerprint,
		&i.EventSlug,
		&i.ConditionID,
		&i.Wallet,
		&i.LastSentAt,
		&i.SendCount,
		&i.LastNotional,
		&i.LastSeverity,
		&i.LastReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMarketPriceSnapshot = `-- name: InsertMarketPriceSnapshot :exec

INSERT INTO polymarket_market_price_snapshots (
    condition_id, event_slug, market_slug, price, best_bid, best_ask, mid, source, sampled_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
`

type InsertMarketPriceSnapshotParams struct {
	ConditionID string
	EventSlug   string
	MarketSlug  string
	Price       *float64
	BestBid     *float64
	BestAsk     *float64
	Mid         *float64
	Source      string
}

// =========================================================================
// Market price snapshots (PART 8)
// =========================================================================
func (q *Queries) InsertMarketPriceSnapshot(ctx context.Context, arg InsertMarketPriceSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertMarketPriceSnapshot,
		arg.ConditionID,
		arg.EventSlug,
		arg.MarketSlug,
		arg.Price,
		arg.BestBid,
		arg.BestAsk,
		arg.Mid,
		arg.Source,
	)
	return err
}

const insertRepricingThesis = `-- name: InsertRepricingThesis :exec

INSERT INTO polymarket_repricing_theses (
    run_id, event_slug, condition_id, current_price, expected_direction,
    expected_price_min, expected_price_max, expected_window,
    trigger_condition, confidence, reason, invalidates_if, source
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12, $13
)
`

type InsertRepricingThesisParams struct {
	RunID             *int64
	EventSlug         string
	ConditionID       string
	CurrentPrice      float64
	ExpectedDirection string
	ExpectedPriceMin  *float64
	ExpectedPriceMax  *float64
	ExpectedWindow    string
	TriggerCondition  string
	Confidence        float64
	Reason            string
	InvalidatesIf     string
	Source            string
}

// =========================================================================
// Repricing theses (PART 9)
// =========================================================================
func (q *Queries) InsertRepricingThesis(ctx context.Context, arg InsertRepricingThesisParams) error {
	_, err := q.db.Exec(ctx, insertRepricingThesis,
		arg.RunID,
		arg.EventSlug,
		arg.ConditionID,
		arg.CurrentPrice,
		arg.ExpectedDirection,
		arg.ExpectedPriceMin,
		arg.ExpectedPriceMax,
		arg.ExpectedWindow,
		arg.TriggerCondition,
		arg.Confidence,
		arg.Reason,
		arg.InvalidatesIf,
		arg.Source,
	)
	return err
}

const insertUnifiedIntelDecision = `-- name: InsertUnifiedIntelDecision :exec
INSERT INTO polymarket_unified_intel_decisions (
    run_id, event_slug, condition_id, decision, regime, class,
    interest_score, confidence, current_price,
    expected_direction, expected_price_min, expected_price_max,
    expected_window, why_market_misprices, what_market_will_understand,
    trigger_condition, invalidates_if, trade_stance, telegram_worthy
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15,
    $16, $17, $18, $19
)
`

type InsertUnifiedIntelDecisionParams struct {
	RunID                    int64
	EventSlug                string
	ConditionID              string
	Decision                 string
	Regime                   string
	Class                    string
	InterestScore            float64
	Confidence               float64
	CurrentPrice             *float64
	ExpectedDirection        string
	ExpectedPriceMin         *float64
	ExpectedPriceMax         *float64
	ExpectedWindow           string
	WhyMarketMisprices       string
	WhatMarketWillUnderstand string
	TriggerCondition         string
	InvalidatesIf            string
	TradeStance              string
	TelegramWorthy           bool
}

func (q *Queries) InsertUnifiedIntelDecision(ctx context.Context, arg InsertUnifiedIntelDecisionParams) error {
	_, err := q.db.Exec(ctx, insertUnifiedIntelDecision,
		arg.RunID,
		arg.EventSlug,
		arg.ConditionID,
		arg.Decision,
		arg.Regime,
		arg.Class,
		arg.InterestScore,
		arg.Confidence,
		arg.CurrentPrice,
		arg.ExpectedDirection,
		arg.ExpectedPriceMin,
		arg.ExpectedPriceMax,
		arg.ExpectedWindow,
		arg.WhyMarketMisprices,
		arg.WhatMarketWillUnderstand,
		arg.TriggerCondition,
		arg.InvalidatesIf,
		arg.TradeStance,
		arg.TelegramWorthy,
	)
	return err
}

const insertUnifiedIntelRun = `-- name: InsertUnifiedIntelRun :one

INSERT INTO polymarket_unified_intel_runs (
    started_at, status, trigger_reason, input_fingerprint,
    news_changed_count, candidates_count, selected_count,
    ai_called, ai_status, sentinel_code, ai_cost_usd, telegram_sent
) VALUES (
    NOW(), 'started', $1, $2,
    $3, $4, $5,
    $6, $7, $8, $9, $10
)
RETURNING id
`

type InsertUnifiedIntelRunParams struct {
	TriggerReason    string
	InputFingerprint string
	NewsChangedCount int32
	CandidatesCount  int32
	SelectedCount    int32
	AiCalled         bool
	AiStatus         string
	SentinelCode     string
	AiCostUsd        float64
	TelegramSent     bool
}

// =========================================================================
// Unified intel runs + decisions (PART 13)
// =========================================================================
func (q *Queries) InsertUnifiedIntelRun(ctx context.Context, arg InsertUnifiedIntelRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertUnifiedIntelRun,
		arg.TriggerReason,
		arg.InputFingerprint,
		arg.NewsChangedCount,
		arg.CandidatesCount,
		arg.SelectedCount,
		arg.AiCalled,
		arg.AiStatus,
		arg.SentinelCode,
		arg.AiCostUsd,
		arg.TelegramSent,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const priceSnapshotAtOrBefore = `-- name: PriceSnapshotAtOrBefore :one
SELECT price, best_bid, best_ask, mid, sampled_at
FROM polymarket_market_price_snapshots
WHERE condition_id = $1 AND sampled_at <= $2
ORDER BY sampled_at DESC LIMIT 1
`

type PriceSnapshotAtOrBeforeParams struct {
	ConditionID string
	Upper       pgtype.Timestamptz
}

type PriceSnapshotAtOrBeforeRow struct {
	Price     *float64
	BestBid   *float64
	BestAsk   *float64
	Mid       *float64
	SampledAt pgtype.Timestamptz
}

func (q *Queries) PriceSnapshotAtOrBefore(ctx context.Context, arg PriceSnapshotAtOrBeforeParams) (PriceSnapshotAtOrBeforeRow, error) {
	row := q.db.QueryRow(ctx, priceSnapshotAtOrBefore, arg.ConditionID, arg.Upper)
	var i PriceSnapshotAtOrBeforeRow
	err := row.Scan(
		&i.Price,
		&i.BestBid,
		&i.BestAsk,
		&i.Mid,
		&i.SampledAt,
	)
	return i, err
}

const touchMarketAICacheReuse = `-- name: TouchMarketAICacheReuse :exec
UPDATE polymarket_market_ai_cache
SET last_reused_at = NOW(),
    reuse_count    = reuse_count + 1,
    updated_at     = NOW()
WHERE ai_surface = $1 AND market_ai_key = $2
`

type TouchMarketAICacheReuseParams struct {
	AiSurface   string
	MarketAiKey string
}

func (q *Queries) TouchMarketAICacheReuse(ctx context.Context, arg TouchMarketAICacheReuseParams) error {
	_, err := q.db.Exec(ctx, touchMarketAICacheReuse, arg.AiSurface, arg.MarketAiKey)
	return err
}

const upsertMarketAICache = `-- name: UpsertMarketAICache :exec
INSERT INTO polymarket_market_ai_cache (
    event_slug, condition_id, ai_surface, market_ai_key,
    news_fingerprint, catalyst_fingerprint, repricing_bucket,
    flow_bucket, price_bucket,
    ai_status, sentinel_code, decision_json, summary_text,
    last_ai_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11, $12, $13,
    NOW(), NOW()
)
ON CONFLICT (ai_surface, market_ai_key) DO UPDATE SET
    news_fingerprint     = EXCLUDED.news_fingerprint,
    catalyst_fingerprint = EXCLUDED.catalyst_fingerprint,
    repricing_bucket     = EXCLUDED.repricing_bucket,
    flow_bucket          = EXCLUDED.flow_bucket,
    price_bucket         = EXCLUDED.price_bucket,
    ai_status            = EXCLUDED.ai_status,
    sentinel_code        = EXCLUDED.sentinel_code,
    decision_json        = EXCLUDED.decision_json,
    summary_text         = EXCLUDED.summary_text,
    last_ai_at           = NOW(),
    updated_at           = NOW()
`

type UpsertMarketAICacheParams struct {
	EventSlug           string
	ConditionID         string
	AiSurface           string
	MarketAiKey         string
	NewsFingerprint     string
	CatalystFingerprint string
	RepricingBucket     string
	FlowBucket          string
	PriceBucket         string
	AiStatus            string
	SentinelCode        string
	DecisionJson        []byte
	SummaryText         string
}

func (q *Queries) UpsertMarketAICache(ctx context.Context, arg UpsertMarketAICacheParams) error {
	_, err := q.db.Exec(ctx, upsertMarketAICache,
		arg.EventSlug,
		arg.ConditionID,
		arg.AiSurface,
		arg.MarketAiKey,
		arg.NewsFingerprint,
		arg.CatalystFingerprint,
		arg.RepricingBucket,
		arg.FlowBucket,
		arg.PriceBucket,
		arg.AiStatus,
		arg.SentinelCode,
		arg.DecisionJson,
		arg.SummaryText,
	)
	return err
}

const upsertTelegramSemanticDedupe = `-- name: UpsertTelegramSemanticDedupe :exec
INSERT INTO polymarket_telegram_semantic_dedupe (
    surface, dedupe_key, semantic_fingerprint, event_slug,
    condition_id, wallet, last_sent_at, send_count,
    last_notional, last_severity, last_reason, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, NOW(), 1,
    $7, $8, $9, NOW()
)
ON CONFLICT (surface, dedupe_key) DO UPDATE SET
    semantic_fingerprint = EXCLUDED.semantic_fingerprint,
    last_sent_at         = NOW(),
    send_count           = polymarket_telegram_semantic_dedupe.send_count + 1,
    last_notional        = EXCLUDED.last_notional,
    last_severity        = EXCLUDED.last_severity,
    last_reason          = EXCLUDED.last_reason,
    updated_at           = NOW()
`

type UpsertTelegramSemanticDedupeParams struct {
	Surface             string
	DedupeKey           string
	SemanticFingerprint string
	EventSlug           string
	ConditionID         string
	Wallet              string
	LastNotional        *float64
	LastSeverity        string
	LastReason          string
}

func (q *Queries) UpsertTelegramSemanticDedupe(ctx context.Context, arg UpsertTelegramSemanticDedupeParams) error {
	_, err := q.db.Exec(ctx, upsertTelegramSemanticDedupe,
		arg.Surface,
		arg.DedupeKey,
		arg.SemanticFingerprint,
		arg.EventSlug,
		arg.ConditionID,
		arg.Wallet,
		arg.LastNotional,
		arg.LastSeverity,
		arg.LastReason,
	)
	return err
}
