// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: v11_news_intel.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishNewsIntelRun = `-- name: FinishNewsIntelRun :exec
UPDATE polymarket_news_intel_runs
SET finished_at        = NOW(),
    status             = $1,
    news_items_count   = $2,
    selected_count     = $3,
    ai_called          = $4,
    ai_status          = $5,
    sentinel_code      = $6,
    ai_cost_usd        = $7,
    output_fingerprint = $8,
    telegram_sent      = $9,
    last_error         = $10
WHERE id = $11
`

type FinishNewsIntelRunParams struct {
	Status            string
	NewsItemsCount    int32
	SelectedCount     int32
	AiCalled          bool
	AiStatus          string
	SentinelCode      string
	AiCostUsd         float64
	OutputFingerprint string
	TelegramSent      bool
	LastError         string
	ID                int64
}

func (q *Queries) FinishNewsIntelRun(ctx context.Context, arg FinishNewsIntelRunParams) error {
	_, err := q.db.Exec(ctx, finishNewsIntelRun,
		arg.Status,
		arg.NewsItemsCount,
		arg.SelectedCount,
		arg.AiCalled,
		arg.AiStatus,
		arg.SentinelCode,
		arg.AiCostUsd,
		arg.OutputFingerprint,
		arg.TelegramSent,
		arg.LastError,
		arg.ID,
	)
	return err
}

const getNewsIntelProcessedItem = `-- name: GetNewsIntelProcessedItem :one

SELECT item_hash, event_slug, title, first_seen_at, last_seen_at,
       processed_at, last_run_id, created_at
FROM polymarket_news_intel_processed_items
WHERE item_hash = $1
`

// =========================================================================
// News intel processed items (dedupe ledger)
// =========================================================================
func (q *Queries) GetNewsIntelProcessedItem(ctx context.Context, itemHash string) (PolymarketNewsIntelProcessedItems, error) {
	row := q.db.QueryRow(ctx, getNewsIntelProcessedItem, itemHash)
	var i PolymarketNewsIntelProcessedItems
	err := row.Scan(
		&i.ItemHash,
		&i.EventSlug,
		&i.Title,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ProcessedAt,
		&i.LastRunID,
		&i.CreatedAt,
	)
	return i, err
}

const insertNewsIntelDecision = `-- name: InsertNewsIntelDecision :exec

INSERT INTO polymarket_news_intel_decisions (
    run_id, news_item_hash, event_slug, condition_id, market_title,
    rank, decision, confidence, impact_direction,
    expected_price_impact_min, expected_price_impact_max, expected_window,
    why_it_matters, what_market_may_miss, trigger_condition, invalidates_if,
    trade_stance, telegram_worthy, affected_markets_json
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19
)
`

type InsertNewsIntelDecisionParams struct {
	RunID                  int64
	NewsItemHash           string
	EventSlug              string
	ConditionID            string
	MarketTitle            string
	Rank                   int32
	Decision               string
	Confidence             float64
	ImpactDirection        string
	ExpectedPriceImpactMin *float64
	ExpectedPriceImpactMax *float64
	ExpectedWindow         string
	WhyItMatters           string
	WhatMarketMayMiss      string
	TriggerCondition       string
	InvalidatesIf          string
	TradeStance            string
	TelegramWorthy         bool
	AffectedMarketsJson    []byte
}

// =========================================================================
// News intel decisions
// =========================================================================
func (q *Queries) InsertNewsIntelDecision(ctx context.Context, arg InsertNewsIntelDecisionParams) error {
	_, err := q.db.Exec(ctx, insertNewsIntelDecision,
		arg.RunID,
		arg.NewsItemHash,
		arg.EventSlug,
		arg.ConditionID,
		arg.MarketTitle,
		arg.Rank,
		arg.Decision,
		arg.Confidence,
		arg.ImpactDirection,
		arg.ExpectedPriceImpactMin,
		arg.ExpectedPriceImpactMax,
		arg.ExpectedWindow,
		arg.WhyItMatters,
		arg.WhatMarketMayMiss,
		arg.TriggerCondition,
		arg.InvalidatesIf,
		arg.TradeStance,
		arg.TelegramWorthy,
		arg.AffectedMarketsJson,
	)
	return err
}

const insertNewsIntelRun = `-- name: InsertNewsIntelRun :one


INSERT INTO polymarket_news_intel_runs (
    started_at, status, lookback_start, lookback_end,
    news_items_count, selected_count, ai_called, ai_status,
    sentinel_code, ai_cost_usd, input_fingerprint, output_fingerprint,
    telegram_sent
) VALUES (
    NOW(), 'started', $1, $2,
    $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11
)
RETURNING id
`

type InsertNewsIntelRunParams struct {
	LookbackStart     pgtype.Timestamptz
	LookbackEnd       pgtype.Timestamptz
	NewsItemsCount    int32
	SelectedCount     int32
	AiCalled          bool
	AiStatus          string
	SentinelCode      string
	AiCostUsd         float64
	InputFingerprint  string
	OutputFingerprint string
	TelegramSent      bool
}

// v11.0 Hourly News Intelligence queries (PART 6).
// =========================================================================
// News intel runs
// =========================================================================
func (q *Queries) InsertNewsIntelRun(ctx context.Context, arg InsertNewsIntelRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertNewsIntelRun,
		arg.LookbackStart,
		arg.LookbackEnd,
		arg.NewsItemsCount,
		arg.SelectedCount,
		arg.AiCalled,
		arg.AiStatus,
		arg.SentinelCode,
		arg.AiCostUsd,
		arg.InputFingerprint,
		arg.OutputFingerprint,
		arg.TelegramSent,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAnnotationsSince = `-- name: ListAnnotationsSince :many

SELECT
    id, event_slug, item_hash, timestamp, unix_time, time_range,
    title, summary, outcome,
    price_before, price_after, price_change,
    source, sources_json, tweets_json, raw_json,
    first_seen_at, last_seen_at
FROM polymarket_event_annotations
WHERE first_seen_at >= $1
   OR last_seen_at  >= $1
ORDER BY first_seen_at DESC, id DESC
LIMIT $2
`

type ListAnnotationsSinceParams struct {
	Since    pgtype.Timestamptz
	RowLimit int32
}

// =========================================================================
// Cross-event annotation feed
// =========================================================================
// Pulls all annotations newer than a threshold across every event. The
// v11.0 news intel worker uses this to enumerate the candidate pool in
// a single roundtrip rather than per-event_slug.
func (q *Queries) ListAnnotationsSince(ctx context.Context, arg ListAnnotationsSinceParams) ([]PolymarketEventAnnotations, error) {
	rows, err := q.db.Query(ctx, listAnnotationsSince, arg.Since, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketEventAnnotations
	for rows.Next() {
		var i PolymarketEventAnnotations
		if err := rows.Scan(
			&i.ID,
			&i.EventSlug,
			&i.ItemHash,
			&i.Timestamp,
			&i.UnixTime,
			&i.TimeRange,
			&i.Title,
			&i.Summary,
			&i.Outcome,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChange,
			&i.Source,
			&i.SourcesJson,
			&i.TweetsJson,
			&i.RawJson,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsIntelDecisionsByRun = `-- name: ListNewsIntelDecisionsByRun :many
SELECT id, run_id, news_item_hash, event_slug, condition_id, market_title,
       rank, decision, confidence, impact_direction,
       expected_price_impact_min, expected_price_impact_max, expected_window,
       why_it_matters, what_market_may_miss, trigger_condition, invalidates_if,
       trade_stance, telegram_worthy, affected_markets_json, created_at
FROM polymarket_news_intel_decisions
WHERE run_id = $1
ORDER BY rank ASC, id ASC
`

func (q *Queries) ListNewsIntelDecisionsByRun(ctx context.Context, runID int64) ([]PolymarketNewsIntelDecisions, error) {
	rows, err := q.db.Query(ctx, listNewsIntelDecisionsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketNewsIntelDecisions
	for rows.Next() {
		var i PolymarketNewsIntelDecisions
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NewsItemHash,
			&i.EventSlug,
			&i.ConditionID,
			&i.MarketTitle,
			&i.Rank,
			&i.Decision,
			&i.Confidence,
			&i.ImpactDirection,
			&i.ExpectedPriceImpactMin,
			&i.ExpectedPriceImpactMax,
			&i.ExpectedWindow,
			&i.WhyItMatters,
			&i.WhatMarketMayMiss,
			&i.TriggerCondition,
			&i.InvalidatesIf,
			&i.TradeStance,
			&i.TelegramWorthy,
			&i.AffectedMarketsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsIntelProcessedHashes = `-- name: ListNewsIntelProcessedHashes :many
SELECT item_hash
FROM polymarket_news_intel_processed_items
WHERE item_hash = ANY($1::TEXT[])
`

func (q *Queries) ListNewsIntelProcessedHashes(ctx context.Context, itemHashes []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listNewsIntelProcessedHashes, itemHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var item_hash string
		if err := rows.Scan(&item_hash); err != nil {
			return nil, err
		}
		items = append(items, item_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentNewsIntelRuns = `-- name: ListRecentNewsIntelRuns :many
SELECT id, started_at, finished_at, status, lookback_start, lookback_end,
       news_items_count, selected_count, ai_called, ai_status,
       sentinel_code, ai_cost_usd, input_fingerprint, output_fingerprint,
       telegram_sent, last_error, created_at
FROM polymarket_news_intel_runs
ORDER BY started_at DESC
LIMIT $1
`

func (q *Queries) ListRecentNewsIntelRuns(ctx context.Context, rowLimit int32) ([]PolymarketNewsIntelRuns, error) {
	rows, err := q.db.Query(ctx, listRecentNewsIntelRuns, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolymarketNewsIntelRuns
	for rows.Next() {
		var i PolymarketNewsIntelRuns
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.LookbackStart,
			&i.LookbackEnd,
			&i.NewsItemsCount,
			&i.SelectedCount,
			&i.AiCalled,
			&i.AiStatus,
			&i.SentinelCode,
			&i.AiCostUsd,
			&i.InputFingerprint,
			&i.OutputFingerprint,
			&i.TelegramSent,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchNewsIntelProcessedItem = `-- name: TouchNewsIntelProcessedItem :exec
UPDATE polymarket_news_intel_processed_items
SET last_seen_at = NOW()
WHERE item_hash = $1
`

func (q *Queries) TouchNewsIntelProcessedItem(ctx context.Context, itemHash string) error {
	_, err := q.db.Exec(ctx, touchNewsIntelProcessedItem, itemHash)
	return err
}

const upsertNewsIntelProcessedItem = `-- name: UpsertNewsIntelProcessedItem :exec
INSERT INTO polymarket_news_intel_processed_items (
    item_hash, event_slug, title, first_seen_at, last_seen_at, processed_at, last_run_id
) VALUES (
    $1, $2, $3, NOW(), NOW(), NOW(), $4
)
ON CONFLICT (item_hash) DO UPDATE SET
    last_seen_at = NOW(),
    processed_at = NOW(),
    last_run_id  = EXCLUDED.last_run_id
`

type UpsertNewsIntelProcessedItemParams struct {
	ItemHash  string
	EventSlug string
	Title     string
	LastRunID *int64
}

func (q *Queries) UpsertNewsIntelProcessedItem(ctx context.Context, arg UpsertNewsIntelProcessedItemParams) error {
	_, err := q.db.Exec(ctx, upsertNewsIntelProcessedItem,
		arg.ItemHash,
		arg.EventSlug,
		arg.Title,
		arg.LastRunID,
	)
	return err
}
