// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: websocket_realtime.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimRealtimeWorkBatch = `-- name: ClaimRealtimeWorkBatch :many
UPDATE polymarket_realtime_work_queue
SET claimed_at = NOW(),
    attempts   = attempts + 1
WHERE id IN (
    SELECT id
    FROM polymarket_realtime_work_queue
    WHERE claimed_at IS NULL
      AND available_at <= NOW()
    ORDER BY priority ASC, available_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
RETURNING id, condition_id, event_slug, reason, priority, dedupe_key, attempts
`

type ClaimRealtimeWorkBatchRow struct {
	ID          int64
	ConditionID *string
	EventSlug   *string
	Reason      string
	Priority    int16
	DedupeKey   string
	Attempts    int32
}

// Atomic claim of up to `limit_count` due rows. Uses SKIP LOCKED so
// multiple drainers can run side-by-side without deadlocks.
func (q *Queries) ClaimRealtimeWorkBatch(ctx context.Context, limitCount int32) ([]ClaimRealtimeWorkBatchRow, error) {
	rows, err := q.db.Query(ctx, claimRealtimeWorkBatch, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimRealtimeWorkBatchRow
	for rows.Next() {
		var i ClaimRealtimeWorkBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.ConditionID,
			&i.EventSlug,
			&i.Reason,
			&i.Priority,
			&i.DedupeKey,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOldRealtimeWork = `-- name: DeleteOldRealtimeWork :exec
DELETE FROM polymarket_realtime_work_queue
WHERE created_at < $1
`

// Periodic cleanup so the queue doesn't grow without bound.
func (q *Queries) DeleteOldRealtimeWork(ctx context.Context, olderThan pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldRealtimeWork, olderThan)
	return err
}

const enqueueRealtimeWork = `-- name: EnqueueRealtimeWork :exec
INSERT INTO polymarket_realtime_work_queue
  (condition_id, event_slug, reason, priority, dedupe_key, available_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (dedupe_key) DO NOTHING
`

type EnqueueRealtimeWorkParams struct {
	ConditionID *string
	EventSlug   *string
	Reason      string
	Priority    int16
	DedupeKey   string
	AvailableAt pgtype.Timestamptz
}

// Idempotent: dedupe_key = condition_id + reason + minute_bucket so a
// burst of WS events for the same market collapses to one queue row.
// Conflicts are silently swallowed via DO NOTHING.
func (q *Queries) EnqueueRealtimeWork(ctx context.Context, arg EnqueueRealtimeWorkParams) error {
	_, err := q.db.Exec(ctx, enqueueRealtimeWork,
		arg.ConditionID,
		arg.EventSlug,
		arg.Reason,
		arg.Priority,
		arg.DedupeKey,
		arg.AvailableAt,
	)
	return err
}

const finishGapRecovery = `-- name: FinishGapRecovery :exec
UPDATE polymarket_ws_gap_recoveries
SET ended_at        = NOW(),
    status          = $1,
    recovered_trades = $2,
    last_error      = $3
WHERE id = $4
`

type FinishGapRecoveryParams struct {
	Status          string
	RecoveredTrades int32
	LastError       *string
	ID              int64
}

func (q *Queries) FinishGapRecovery(ctx context.Context, arg FinishGapRecoveryParams) error {
	_, err := q.db.Exec(ctx, finishGapRecovery,
		arg.Status,
		arg.RecoveredTrades,
		arg.LastError,
		arg.ID,
	)
	return err
}

const getLiveMarketState = `-- name: GetLiveMarketState :one
SELECT condition_id, event_slug, market_slug, best_bid, best_ask, mid,
       last_price, last_trade_at, last_ws_event_at, ws_connected, updated_at
FROM polymarket_live_market_state
WHERE condition_id = $1
`

func (q *Queries) GetLiveMarketState(ctx context.Context, conditionID string) (PolymarketLiveMarketState, error) {
	row := q.db.QueryRow(ctx, getLiveMarketState, conditionID)
	var i PolymarketLiveMarketState
	err := row.Scan(
		&i.ConditionID,
		&i.EventSlug,
		&i.MarketSlug,
		&i.BestBid,
		&i.BestAsk,
		&i.Mid,
		&i.LastPrice,
		&i.LastTradeAt,
		&i.LastWsEventAt,
		&i.WsConnected,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGapRecovery = `-- name: InsertGapRecovery :one
INSERT INTO polymarket_ws_gap_recoveries
  (condition_id, started_at, lookback_start, lookback_end, status, recovered_trades)
VALUES ($1, NOW(), $2, $3, 'started', 0)
RETURNING id
`

type InsertGapRecoveryParams struct {
	ConditionID   string
	LookbackStart pgtype.Timestamptz
	LookbackEnd   pgtype.Timestamptz
}

func (q *Queries) InsertGapRecovery(ctx context.Context, arg InsertGapRecoveryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertGapRecovery, arg.ConditionID, arg.LookbackStart, arg.LookbackEnd)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertWSEvent = `-- name: InsertWSEvent :exec
INSERT INTO polymarket_ws_events
  (received_at, exchange_timestamp, event_type, event_slug, condition_id,
   market_slug, clob_token_id, outcome, price, size, side, side_source,
   side_confidence, best_bid, best_ask, mid, tx_hash, trade_id, wallet,
   sequence, raw_json, raw_hash)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10, $11, $12,
        $13, $14, $15, $16, $17, $18, $19,
        $20, $21, $22)
`

type InsertWSEventParams struct {
	ReceivedAt        pgtype.Timestamptz
	ExchangeTimestamp pgtype.Timestamptz
	EventType         string
	EventSlug         *string
	ConditionID       *string
	MarketSlug        *string
	ClobTokenID       *string
	Outcome           *string
	Price             *float64
	Size              *float64
	Side              *string
	SideSource        string
	SideConfidence    float64
	BestBid           *float64
	BestAsk           *float64
	Mid               *float64
	TxHash            *string
	TradeID           *string
	Wallet            *string
	Sequence          *string
	RawJson           []byte
	RawHash           *string
}

// Append-only audit/correlation row. Fail-open: the WS path
// handles a write error by logging + continuing — never blocks.
func (q *Queries) InsertWSEvent(ctx context.Context, arg InsertWSEventParams) error {
	_, err := q.db.Exec(ctx, insertWSEvent,
		arg.ReceivedAt,
		arg.ExchangeTimestamp,
		arg.EventType,
		arg.EventSlug,
		arg.ConditionID,
		arg.MarketSlug,
		arg.ClobTokenID,
		arg.Outcome,
		arg.Price,
		arg.Size,
		arg.Side,
		arg.SideSource,
		arg.SideConfidence,
		arg.BestBid,
		arg.BestAsk,
		arg.Mid,
		arg.TxHash,
		arg.TradeID,
		arg.Wallet,
		arg.Sequence,
		arg.RawJson,
		arg.RawHash,
	)
	return err
}

const markRealtimeWorkFailed = `-- name: MarkRealtimeWorkFailed :exec
UPDATE polymarket_realtime_work_queue
SET last_error = $1,
    claimed_at = NULL,
    available_at = NOW() + INTERVAL '1 minute'
WHERE id = $2
`

type MarkRealtimeWorkFailedParams struct {
	LastError *string
	ID        int64
}

func (q *Queries) MarkRealtimeWorkFailed(ctx context.Context, arg MarkRealtimeWorkFailedParams) error {
	_, err := q.db.Exec(ctx, markRealtimeWorkFailed, arg.LastError, arg.ID)
	return err
}

const setLiveMarketWSConnected = `-- name: SetLiveMarketWSConnected :exec
UPDATE polymarket_live_market_state
SET ws_connected = $1, updated_at = NOW()
WHERE condition_id = ANY($2::text[])
`

type SetLiveMarketWSConnectedParams struct {
	WsConnected  bool
	ConditionIds []string
}

// Bulk-flip ws_connected on/off when the client connects/disconnects.
// Used by the realtime worker to surface "WS is alive for this market".
func (q *Queries) SetLiveMarketWSConnected(ctx context.Context, arg SetLiveMarketWSConnectedParams) error {
	_, err := q.db.Exec(ctx, setLiveMarketWSConnected, arg.WsConnected, arg.ConditionIds)
	return err
}

const upsertLiveMarketState = `-- name: UpsertLiveMarketState :exec
INSERT INTO polymarket_live_market_state
  (condition_id, event_slug, market_slug, best_bid, best_ask, mid,
   last_price, last_trade_at, last_ws_event_at, ws_connected, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, NOW())
ON CONFLICT (condition_id) DO UPDATE
   SET event_slug       = COALESCE(EXCLUDED.event_slug, polymarket_live_market_state.event_slug),
       market_slug      = COALESCE(EXCLUDED.market_slug, polymarket_live_market_state.market_slug),
       best_bid         = COALESCE(EXCLUDED.best_bid, polymarket_live_market_state.best_bid),
       best_ask         = COALESCE(EXCLUDED.best_ask, polymarket_live_market_state.best_ask),
       mid              = COALESCE(EXCLUDED.mid, polymarket_live_market_state.mid),
       last_price       = COALESCE(EXCLUDED.last_price, polymarket_live_market_state.last_price),
       last_trade_at    = COALESCE(EXCLUDED.last_trade_at, polymarket_live_market_state.last_trade_at),
       last_ws_event_at = COALESCE(EXCLUDED.last_ws_event_at, polymarket_live_market_state.last_ws_event_at),
       ws_connected     = EXCLUDED.ws_connected,
       updated_at       = NOW()
`

type UpsertLiveMarketStateParams struct {
	ConditionID   string
	EventSlug     *string
	MarketSlug    *string
	BestBid       *float64
	BestAsk       *float64
	Mid           *float64
	LastPrice     *float64
	LastTradeAt   pgtype.Timestamptz
	LastWsEventAt pgtype.Timestamptz
	WsConnected   bool
}

// Top-of-book / mid / last-price per condition_id. Updated from both
// WS events and the reconciliation sweep. Idempotent — every write
// bumps updated_at + last_ws_event_at.
func (q *Queries) UpsertLiveMarketState(ctx context.Context, arg UpsertLiveMarketStateParams) error {
	_, err := q.db.Exec(ctx, upsertLiveMarketState,
		arg.ConditionID,
		arg.EventSlug,
		arg.MarketSlug,
		arg.BestBid,
		arg.BestAsk,
		arg.Mid,
		arg.LastPrice,
		arg.LastTradeAt,
		arg.LastWsEventAt,
		arg.WsConnected,
	)
	return err
}
